[template]
src = "ca_config/create-server.sh.tpl"
dest = "ca_config/bin/create-server.sh"
mode = "0700"
keys = [
  "/ca/root/directory",
  "/ca/server/pkey-bits",
  "/ca/pem-encryption",
  "/ca/hashing"
]