dodo: dodo::network::protocol::http::HTTPMessage Class Reference
dodo::network::protocol::http::HTTPMessage Class Reference abstract
Generic HTTPMessage, parent to HTTPRequest and HTTPResponse.
#include <httpmessage.hpp>
Public Member Functions
HTTPMessage ()
Default constructor.
void addHeader (const std::string &key, const std::string &value)
Add a header to the HTTPMessage.
void clearHeaders ()
Clear all headers.
const common::Bytes & getBody () const
Return the HTTTMessage body.
const std::map< std::string, std::string > & getHeaders () const
Return a reference to the headers map.
bool getHeaderValue (const std::string &key, std::string &value) const
Get a header value as a string into value.
bool getHeaderValue (const std::string &key, unsigned long &value) const
Get a header value as an unsigned long into value.
bool hasHeader (const std::string &header) const
void replaceHeader (const std::string &key, const std::string &value)
Replace the value of a header.
virtual common::SystemError send (BaseSocket *socket)=0
void setBody (const std::string &body)
Set the body.
Public Member Functions inherited from dodo::network::protocol::http::HTTPFragment
virtual std::string asString () const =0
Convert the HTTPFragment in a HTTP protocol string.
virtual ParseResult parse (VirtualReadBuffer &buffer)=0
Read a complete HTTPFragment from a VirtualReadBuffer.
Static Public Attributes
static const char charCR = char(13)
CR character.
static const char charHT = char(9)
Horizontal tab character.
static const char charLF = char(10)
LF character.
static const char charSP = char(32)
Space character.
Protected Member Functions
ParseResult eatCRLF (VirtualReadBuffer &data)
Consume a CR LF sequence only when it is there.
virtual ParseResult parseBody (VirtualReadBuffer &data)=0
Parse a body and resturn it as a single string.
ParseResult parseChunkedBody (VirtualReadBuffer &data)
Parse a chunked body (transfer-encoding: chunked) and resturn it as a single string.
ParseResult parseChunkHex (VirtualReadBuffer &data, unsigned long &value)
Parse a hexadecimal chunk size (a hex value followed by CR LF).
ParseResult parseCRLF (VirtualReadBuffer &data)
Consume a CR LF sequence.
ParseResult parseFieldValue (VirtualReadBuffer &data, std::string &value)
Parse a header field value.
ParseResult parseHeaders (VirtualReadBuffer &data)
Parse a header section and update headers_.
ParseResult parseToken (VirtualReadBuffer &buffer, std::string &token)
Parse a token (such as a header field name).
Static Protected Member Functions
static common::SystemError eatSpace (VirtualReadBuffer &data)
Call buffer.next() as long as buffer.get() is whitespace (charSP or charHT).
static bool isCTL (char c)
Check is the char is a CTL character.
static bool isSeparator (char c)
Return true if the char is a separator.
static bool isSP (char c)
Return true if the char is whitespace character (charSP or charHT)
static ParseResult parseUInt (VirtualReadBuffer &data, unsigned int &value)
Parse an unsigned integer.
Protected Attributes
common::Bytes body_
The message body (if any).
std::map< std::string, std::string > headers_
The message headers.
Additional Inherited Members
Public Types inherited from dodo::network::protocol::http::HTTPFragment
enum ParseError : unsigned int {
peOk = 0, peIncomplete, peSystemError, peExpectCRLF,
peUnFinishedToken, peExpectingHeaderColon, peInvalidHeaderFieldValue, peInvalidHeaderListEnd,
peInvalidMethod, peInvalidHTTPVersion, peInvalidRequestLine, peInvalidContentLength,
peUnexpectedBody, peInvalidTransferEncoding, peInvalidChunkHex, peInvalidLastChunk,
peExpectingUnsignedInt
}
Parse results returned by the parse functions.
Static Public Member Functions inherited from dodo::network::protocol::http::HTTPFragment
static std::string getParseResultAsString (ParseError error)
Return the string description of a ParseError.
Detailed Description
Generic HTTPMessage, parent to HTTPRequest and HTTPResponse.
See also
https://tools.ietf.org/html/rfc2616#page-15
Remarks
This class is not thread safe, but does not use any global variables.
Definition at line 40 of file httpmessage.hpp.
Constructor & Destructor Documentation
HTTPMessage()
dodo::network::protocol::http::HTTPMessage::HTTPMessage () inline
Default constructor.
Definition at line 67 of file httpmessage.hpp.
Member Function Documentation
addHeader()
void dodo::network::protocol::http::HTTPMessage::addHeader (const std::string & key, const std::string & value)
Add a header to the HTTPMessage.
Note that multtiple headers may be specified with the same key but are supposed to be equavalent to a comma seperated list, so
addHeader("key", "1");
addHeader("key", "2");
addHeader("key", "3");
is equivalent to
addHeader("key", "1,2,3");
and this class transforms the former into the latter automatically.
Parameters
key The header key.
value The header value.
Definition at line 37 of file httpmessage.cpp.
References headers_.
Referenced by parseHeaders().
clearHeaders()
void dodo::network::protocol::http::HTTPMessage::clearHeaders () inline
Clear all headers.
Definition at line 105 of file httpmessage.hpp.
References headers_.
eatCRLF()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::eatCRLF (VirtualReadBuffer & data) protected
Consume a CR LF sequence only when it is there.
Unlike parseCRLF this function will not fail when the CRLF is not found.
Parameters
data The VirtualReadBuffer to read from.
Returns
peOk or peExpectCRLF or peSystemError. The latter can only be returned when a CR is encountered without a LF after it.
Definition at line 46 of file httpmessage.cpp.
References charCR, charLF, dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPFragment::peExpectCRLF, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
eatSpace()
common::SystemError dodo::network::protocol::http::HTTPMessage::eatSpace (VirtualReadBuffer & data) static protected
Call buffer.next() as long as buffer.get() is whitespace (charSP or charHT).
Parameters
data The VirtualReadBuffer to read from.
Returns
A SystemError, like data tata presenting a CR but no LF after it.
Definition at line 56 of file httpmessage.cpp.
References charHT, charSP, dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), and dodo::network::VirtualReadBuffer::next().
Referenced by dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), and parseHeaders().
getBody()
const common::Bytes& dodo::network::protocol::http::HTTPMessage::getBody () const inline
Return the HTTTMessage body.
Returns
The HTTPMessage body.
Definition at line 128 of file httpmessage.hpp.
References body_.
getHeaders()
const std::map<std::string,std::string>& dodo::network::protocol::http::HTTPMessage::getHeaders () const inline
Return a reference to the headers map.
Returns
A reference to headers_;
Definition at line 98 of file httpmessage.hpp.
References headers_.
getHeaderValue() [1/2]
bool dodo::network::protocol::http::HTTPMessage::getHeaderValue (const std::string & key, std::string & value) const
Get a header value as a string into value.
Parameters
key The header key.
value Receives the header value.
Returns
True if the key was found, false otherwise, in which case value is undefined.
Definition at line 74 of file httpmessage.cpp.
References headers_.
Referenced by dodo::network::protocol::http::HTTPRequest::parseBody(), and dodo::network::protocol::http::HTTPResponse::parseBody().
getHeaderValue() [2/2]
bool dodo::network::protocol::http::HTTPMessage::getHeaderValue (const std::string & key, unsigned long & value) const
Get a header value as an unsigned long into value.
Parameters
key The header key.
value Receives the header value.
Returns
True if the key was found and the value an integer, false otherwise, in which case value is undefined.
Definition at line 64 of file httpmessage.cpp.
References headers_.
isCTL()
static bool dodo::network::protocol::http::HTTPMessage::isCTL (char c) inline static protected
Check is the char is a CTL character.
Parameters
c The character to check.
Returns
true is c is a control character
See also
https://tools.ietf.org/html/rfc2616#page-15
Definition at line 154 of file httpmessage.hpp.
Referenced by parseToken().
isSeparator()
static bool dodo::network::protocol::http::HTTPMessage::isSeparator (char c) inline static protected
Return true if the char is a separator.
Parameters
c The char to check.
Returns
True if c is a separator, false otherwise.
Todo:
the order of checks can be optimized on character frequency.
Definition at line 232 of file httpmessage.hpp.
References charHT, and charSP.
Referenced by parseToken().
isSP()
static bool dodo::network::protocol::http::HTTPMessage::isSP (char c) inline static protected
Return true if the char is whitespace character (charSP or charHT)
Parameters
c The char to check.
Returns
True if c is whitespace, false otherwise.
Todo:
the order of checks can be optimized on character frequency.
Definition at line 245 of file httpmessage.hpp.
References charHT, and charSP.
Referenced by parseFieldValue().
parseBody()
virtual ParseResult dodo::network::protocol::http::HTTPMessage::parseBody (VirtualReadBuffer & data) protected pure virtual
Parse a body and resturn it as a single string.
Note that the content-length header must be present and specify the correct body length.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseError.
Implemented in dodo::network::protocol::http::HTTPResponse, and dodo::network::protocol::http::HTTPRequest.
parseChunkedBody()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseChunkedBody (VirtualReadBuffer & data) protected
Parse a chunked body (transfer-encoding: chunked) and resturn it as a single string.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseError.
Definition at line 224 of file httpmessage.cpp.
References dodo::common::Bytes::append(), body_, dodo::common::SystemError::ecOK, dodo::network::protocol::http::HTTPFragment::ParseResult::eof(), dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), parseChunkHex(), parseCRLF(), dodo::network::protocol::http::HTTPFragment::peInvalidLastChunk, dodo::network::protocol::http::HTTPFragment::peOk, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by dodo::network::protocol::http::HTTPRequest::parseBody(), and dodo::network::protocol::http::HTTPResponse::parseBody().
parseChunkHex()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseChunkHex (VirtualReadBuffer & data, unsigned long & value) protected
Parse a hexadecimal chunk size (a hex value followed by CR LF).
Parameters
data The VirtualReadBuffer to read from.
value The value receiving the chunk size.
Returns
The ParseResult, either peOk, peExpectCRLF or peInvalidChunkHex.
Definition at line 125 of file httpmessage.cpp.
References dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), parseCRLF(), dodo::network::protocol::http::HTTPFragment::peInvalidChunkHex, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by parseChunkedBody().
parseCRLF()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseCRLF (VirtualReadBuffer & data) protected
Consume a CR LF sequence.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseResult
Definition at line 115 of file httpmessage.cpp.
References charCR, charLF, dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPFragment::peExpectCRLF, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by parseChunkedBody(), and parseChunkHex().
parseFieldValue()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseFieldValue (VirtualReadBuffer & data, std::string & value) protected
Parse a header field value.
Parameters
data The VirtualReadBuffer to read from.
value The value receiving the field-value.
Returns
The ParseResult.
Definition at line 141 of file httpmessage.cpp.
References charCR, charLF, charSP, dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), isSP(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPFragment::peExpectCRLF, dodo::network::protocol::http::HTTPFragment::peInvalidHeaderFieldValue, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by parseHeaders().
parseHeaders()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseHeaders (VirtualReadBuffer & data) protected
Parse a header section and update headers_.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseResult.
Definition at line 83 of file httpmessage.cpp.
References addHeader(), charCR, charLF, eatSpace(), dodo::common::SystemError::ecOK, dodo::network::protocol::http::HTTPFragment::ParseResult::eof(), dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), parseFieldValue(), parseToken(), dodo::network::protocol::http::HTTPFragment::peExpectingHeaderColon, dodo::network::protocol::http::HTTPFragment::peInvalidHeaderListEnd, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by dodo::network::protocol::http::HTTPRequest::parse(), and dodo::network::protocol::http::HTTPResponse::parse().
parseToken()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseToken (VirtualReadBuffer & buffer, std::string & token) protected
Parse a token (such as a header field name).
Parameters
buffer The HTTP data source.
token The value receiving the token.
Returns
The ParseResult.
Definition at line 196 of file httpmessage.cpp.
References dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), isCTL(), isSeparator(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPFragment::peOk, dodo::network::protocol::http::HTTPFragment::peUnFinishedToken, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by parseHeaders().
parseUInt()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPMessage::parseUInt (VirtualReadBuffer & data, unsigned int & value) static protected
Parse an unsigned integer.
Parameters
data The VirtualReadBuffer to read from.
value The value receiving the unsigned int.
Returns
The ParseResult.
Definition at line 211 of file httpmessage.cpp.
References dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPFragment::peExpectingUnsignedInt, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse().
replaceHeader()
void dodo::network::protocol::http::HTTPMessage::replaceHeader (const std::string & key, const std::string & value)
Replace the value of a header.
Parameters
key the key to replace.
value the value to set.
Definition at line 244 of file httpmessage.cpp.
References headers_.
Referenced by setBody().
setBody()
void dodo::network::protocol::http::HTTPMessage::setBody (const std::string & body)
Set the body.
Parameters
body The body to set.
Definition at line 248 of file httpmessage.cpp.
References body_, dodo::common::Bytes::getSize(), and replaceHeader().
Field Documentation
body_
common::Bytes dodo::network::protocol::http::HTTPMessage::body_ protected
The message body (if any).
Definition at line 257 of file httpmessage.hpp.
Referenced by dodo::network::protocol::http::HTTPRequest::asString(), dodo::network::protocol::http::HTTPResponse::asString(), getBody(), dodo::network::protocol::http::HTTPRequest::parseBody(), dodo::network::protocol::http::HTTPResponse::parseBody(), parseChunkedBody(), and setBody().
charCR
const char dodo::network::protocol::http::HTTPMessage::charCR = char(13) static
CR character.
Definition at line 47 of file httpmessage.hpp.
Referenced by dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::asString(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::asString(), dodo::network::protocol::http::HTTPRequest::asString(), dodo::network::protocol::http::HTTPResponse::asString(), eatCRLF(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), dodo::network::protocol::http::HTTPResponse::parse(), parseCRLF(), parseFieldValue(), and parseHeaders().
charHT
const char dodo::network::protocol::http::HTTPMessage::charHT = char(9) static
Horizontal tab character.
Definition at line 62 of file httpmessage.hpp.
Referenced by eatSpace(), isSeparator(), and isSP().
charLF
const char dodo::network::protocol::http::HTTPMessage::charLF = char(10) static
LF character.
Definition at line 52 of file httpmessage.hpp.
Referenced by dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::asString(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::asString(), dodo::network::protocol::http::HTTPRequest::asString(), dodo::network::protocol::http::HTTPResponse::asString(), eatCRLF(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), dodo::network::protocol::http::HTTPResponse::parse(), parseCRLF(), parseFieldValue(), and parseHeaders().
charSP
const char dodo::network::protocol::http::HTTPMessage::charSP = char(32) static
Space character.
Definition at line 57 of file httpmessage.hpp.
Referenced by dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::asString(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::asString(), eatSpace(), isSeparator(), isSP(), and parseFieldValue().
headers_
std::map<std::string,std::string> dodo::network::protocol::http::HTTPMessage::headers_ protected
The message headers.
Definition at line 252 of file httpmessage.hpp.
Referenced by addHeader(), dodo::network::protocol::http::HTTPRequest::asString(), dodo::network::protocol::http::HTTPResponse::asString(), clearHeaders(), getHeaders(), getHeaderValue(), and replaceHeader().
The documentation for this class was generated from the following files:
src/include/network/protocol/http/httpmessage.hpp
src/lib/network/protocol/http/httpmessage.cpp