dodo: dodo::store::kvstore::KVStore Class Reference
dodo::store::kvstore::KVStore Class Reference
Key-value store.
#include <kvstore.hpp>
Data Structures
struct IndexHeader
KVStore Index block header.
struct TOCHeader
KVStore TOC block header.
Public Types
typedef std::string Key
Data type for the key of akey-value pair.
enum ShareMode { ShareMode::Private, ShareMode::Shared, ShareMode::Clustered }
The share mode of the KVStore.
Public Member Functions
bool analyze (std::ostream &os)
Analyze the store and produce fiudings to os.
SystemError init (const std::filesystem::path &path, size_t blocksize, size_t blocks, ShareMode mode)
Init the KVStore.
SystemError open (const std::filesystem::path &path, ShareMode mode)
Open the KVStore.
Protected Types
typedef void(KVStore::* waitLockFN) (BlockId blockid)
typedef the lock functions so the lock functions can be initialized depending on the ShareMode and avoid ShareMode detection within the lock functions.
Protected Member Functions
BlockHeader * getBlockAddress (BlockId blockid) const
Return a pointer to the block's BlockHeader.
void waitReadLockPrivate (BlockId blockid)
Wait for and lock the blockid for reading in Private mode.
void waitReadLockShared (BlockId blockid)
Wait for and lock the blockid for reading in Shared mode.
void waitReadUnlockPrivate (BlockId blockid)
Wait for and unlock the blockid for reading in Private mode.
void waitReadUnlockShared (BlockId blockid)
Wait for and unlock the blockid for reading in Shared mode.
void waitWriteLockPrivate (BlockId blockid)
Wait for and lock the blockid for writing in Private mode.
void waitWriteLockShared (BlockId blockid)
Wait for and lock the blockid for writing in Shared mode.
void waitWriteUnlockPrivate (BlockId blockid)
Wait for and unlock the blockid for writing in Private mode.
void waitWriteUnlockShared (BlockId blockid)
Wait for and unlock the blockid for writing in Shared mode.
Protected Attributes
void * address_
The mapped memory address.
size_t blocksize_
The block size.
int fd_
The file descriptor.
const uint64_t magic = 2004196816041969
The file header magic.
const BlockId min_blocks_ = 4
The minimum amount of blocks to allocate - kvstore file cannot be smaller.
const uint16_t version = 000001
The version of this KVStore code, facilitating auto upgrades.
waitLockFN waitReadLock_
The read lock function in use.
waitLockFN waitReadUnlock_
The read unlock function in use.
waitLockFN waitWriteLock_
The Write lock function in use.
waitLockFN waitWriteUnlock_
The Write unlock function in use.
Detailed Description
Key-value store.
Definition at line 43 of file kvstore.hpp.
Member Typedef Documentation
Key
typedef std::string dodo::store::kvstore::KVStore::Key
Data type for the key of akey-value pair.
Definition at line 50 of file kvstore.hpp.
waitLockFN
typedef void(KVStore::* dodo::store::kvstore::KVStore::waitLockFN) (BlockId blockid) protected
typedef the lock functions so the lock functions can be initialized depending on the ShareMode and avoid ShareMode detection within the lock functions.
Definition at line 127 of file kvstore.hpp.
Member Enumeration Documentation
ShareMode
enum dodo::store::kvstore::KVStore::ShareMode strong
The share mode of the KVStore.
Enumerator
Private
Do not share outside process (but sharing between threads possible).
Shared
Share with other processes.
Clustered
Share with other processes on other nodes (which requires a cluster filesystem).
Definition at line 55 of file kvstore.hpp.
Member Function Documentation
analyze()
bool dodo::store::kvstore::KVStore::analyze (std::ostream & os)
Analyze the store and produce fiudings to os.
Parameters
os The stream to write the analysis to.
Returns
true if the KVStore (file) is valid.
Definition at line 170 of file kvstore.cpp.
References address_, dodo::store::kvstore::FileHeader::BlockDef::block_header, dodo::store::kvstore::FileHeader::BlockDef::blocks, dodo::store::kvstore::FileHeader::BlockDef::blocksize, blocksize_, dodo::store::kvstore::BlockHeader::blocktype, dodo::store::kvstore::BlockHeader::calcCRC32(), dodo::store::kvstore::FileHeader::BlockDef::created, fd_, dodo::store::kvstore::FileHeader::getBlock(), dodo::store::kvstore::FileHeader::getInfo(), dodo::store::kvstore::FileHeader::BlockDef::magic, dodo::store::kvstore::Tester::test(), and dodo::store::kvstore::FileHeader::BlockDef::version.
getBlockAddress()
BlockHeader* dodo::store::kvstore::KVStore::getBlockAddress (BlockId blockid) const inline protected
Return a pointer to the block's BlockHeader.
Parameters
blockid the BlockId to get the address for.
Returns
a pointer to the block's BlockHeader.
Definition at line 119 of file kvstore.hpp.
Referenced by init().
init()
SystemError dodo::store::kvstore::KVStore::init (const std::filesystem::path & path, size_t blocksize, size_t blocks, ShareMode mode)
Init the KVStore.
The file must not exist.
Parameters
path The KVStore file path.
blocksize The KVStore block size, ceiled to multiples of 4KiB.
blocks The number of blocks.
mode The ShareMode to apply.
Returns
The SystemError matching errno returned by open (man 2 open) or SystemError::ecOK.
Definition at line 76 of file kvstore.cpp.
References address_, dodo::store::kvstore::FileHeader::BlockDef::block_header, dodo::store::kvstore::KVStore::TOCHeader::block_header, dodo::store::kvstore::BlockHeader::blockid, dodo::store::kvstore::FileHeader::BlockDef::blocks, dodo::store::kvstore::FileHeader::BlockDef::blocksize, blocksize_, dodo::store::kvstore::BlockHeader::blocktype, dodo::store::kvstore::btFileHeader, dodo::store::kvstore::btFree, dodo::store::kvstore::btTOC, dodo::store::kvstore::BlockHeader::calcCRC32(), Clustered, dodo::store::kvstore::FileHeader::BlockDef::contact_sz, dodo::store::kvstore::BlockHeader::crc32, dodo::store::kvstore::FileHeader::BlockDef::created, dodo::store::kvstore::FileHeader::BlockDef::description_sz, dodo::common::SystemError::ecOK, fd_, dodo::store::kvstore::FileHeader::getBlock(), getBlockAddress(), dodo::store::kvstore::FileHeader::BlockDef::magic, magic, min_blocks_, dodo::store::kvstore::FileHeader::BlockDef::name_sz, dodo::store::kvstore::KVStore::TOCHeader::next_toc, open(), Private, dodo::store::kvstore::FileHeader::setInfo(), Shared, throw_SystemException, dodo::store::kvstore::FileHeader::BlockDef::version, version, and dodo::store::kvstore::BlockHeader::zero().
open()
SystemError dodo::store::kvstore::KVStore::open (const std::filesystem::path & path, ShareMode mode)
Open the KVStore.
The file must exist and be valid (correct header and structure).
Parameters
path The KVStore file path.
mode The ShareMode to apply.
Returns
The SystemError matching errno returned by open (man 2 open) or SystemError::ecOK.
Definition at line 51 of file kvstore.cpp.
References address_, Clustered, dodo::common::SystemError::ecOK, fd_, dodo::common::getFileSize(), Private, Shared, throw_SystemException, waitReadLock_, waitReadLockPrivate(), waitReadLockShared(), waitWriteLock_, waitWriteLockPrivate(), and waitWriteLockShared().
Referenced by init().
waitReadLockPrivate()
void dodo::store::kvstore::KVStore::waitReadLockPrivate (BlockId blockid) inline protected
Wait for and lock the blockid for reading in Private mode.
As in private mode there is no need to sync access between clusters or processes, this only uses a Mutex to sync.
Parameters
blockid The blockid to lock.
Definition at line 156 of file kvstore.hpp.
Referenced by open().
waitReadLockShared()
void dodo::store::kvstore::KVStore::waitReadLockShared (BlockId blockid) inline protected
Wait for and lock the blockid for reading in Shared mode.
The file and memory may be shared between processes.
Parameters
blockid The blockid to lock.
Definition at line 187 of file kvstore.hpp.
Referenced by open().
waitReadUnlockPrivate()
void dodo::store::kvstore::KVStore::waitReadUnlockPrivate (BlockId blockid) inline protected
Wait for and unlock the blockid for reading in Private mode.
As in private mode there is no need to sync access between clusters or processes, this only uses a Mutex to sync.
Parameters
blockid The blockid to unlock.
Definition at line 172 of file kvstore.hpp.
waitReadUnlockShared()
void dodo::store::kvstore::KVStore::waitReadUnlockShared (BlockId blockid) inline protected
Wait for and unlock the blockid for reading in Shared mode.
The file and memory may be shared between processes.
Parameters
blockid The blockid to unlock.
Definition at line 202 of file kvstore.hpp.
waitWriteLockPrivate()
void dodo::store::kvstore::KVStore::waitWriteLockPrivate (BlockId blockid) inline protected
Wait for and lock the blockid for writing in Private mode.
As in private mode there is no need to sync access between clusters or processes, this only uses a Mutex to sync.
Parameters
blockid The blockid to lock.
Definition at line 164 of file kvstore.hpp.
Referenced by open().
waitWriteLockShared()
void dodo::store::kvstore::KVStore::waitWriteLockShared (BlockId blockid) inline protected
Wait for and lock the blockid for writing in Shared mode.
As in private mode there is no need to sync access between clusters or processes, this only uses a Mutex to sync.
Parameters
blockid The blockid to lock.
Definition at line 195 of file kvstore.hpp.
Referenced by open().
waitWriteUnlockPrivate()
void dodo::store::kvstore::KVStore::waitWriteUnlockPrivate (BlockId blockid) inline protected
Wait for and unlock the blockid for writing in Private mode.
As in private mode there is no need to sync access between clusters or processes, this only uses a Mutex to sync.
Parameters
blockid The blockid to unlock.
Definition at line 180 of file kvstore.hpp.
waitWriteUnlockShared()
void dodo::store::kvstore::KVStore::waitWriteUnlockShared (BlockId blockid) inline protected
Wait for and unlock the blockid for writing in Shared mode.
As in private mode there is no need to sync access between clusters or processes, this only uses a Mutex to sync.
Parameters
blockid The blockid to unlock.
Definition at line 210 of file kvstore.hpp.
Field Documentation
address_
void* dodo::store::kvstore::KVStore::address_ protected
The mapped memory address.
Definition at line 230 of file kvstore.hpp.
Referenced by analyze(), init(), and open().
blocksize_
size_t dodo::store::kvstore::KVStore::blocksize_ protected
The block size.
Definition at line 221 of file kvstore.hpp.
Referenced by analyze(), and init().
fd_
int dodo::store::kvstore::KVStore::fd_ protected
The file descriptor.
Definition at line 227 of file kvstore.hpp.
Referenced by analyze(), init(), and open().
magic
const uint64_t dodo::store::kvstore::KVStore::magic = 2004196816041969 protected
The file header magic.
Definition at line 218 of file kvstore.hpp.
Referenced by init().
min_blocks_
const BlockId dodo::store::kvstore::KVStore::min_blocks_ = 4 protected
The minimum amount of blocks to allocate - kvstore file cannot be smaller.
Definition at line 224 of file kvstore.hpp.
Referenced by init().
version
const uint16_t dodo::store::kvstore::KVStore::version = 000001 protected
The version of this KVStore code, facilitating auto upgrades.
Format is [major][minor][patch]L where each field is a decimal ranging from 0-99, so 1.2.13 would be 010213L.
Definition at line 215 of file kvstore.hpp.
Referenced by init().
waitReadLock_
waitLockFN dodo::store::kvstore::KVStore::waitReadLock_ protected
The read lock function in use.
Definition at line 133 of file kvstore.hpp.
Referenced by open().
waitReadUnlock_
waitLockFN dodo::store::kvstore::KVStore::waitReadUnlock_ protected
The read unlock function in use.
Definition at line 138 of file kvstore.hpp.
waitWriteLock_
waitLockFN dodo::store::kvstore::KVStore::waitWriteLock_ protected
The Write lock function in use.
Definition at line 143 of file kvstore.hpp.
Referenced by open().
waitWriteUnlock_
waitLockFN dodo::store::kvstore::KVStore::waitWriteUnlock_ protected
The Write unlock function in use.
Definition at line 148 of file kvstore.hpp.
The documentation for this class was generated from the following files:
src/include/store/kvstore/kvstore.hpp
src/lib/store/kvstore/kvstore.cpp