dodo: dodo::network::TCPConnectionData Class Reference
dodo::network::TCPConnectionData Class Reference
Class to track a connection.
#include <tcplistener.hpp>
Public Member Functions
TCPConnectionData ()
Construct.
virtual ~TCPConnectionData ()
Destruct.
void clearBuffer ()
Clears the read_buffer.
const common::Bytes & getReadBuffer () const
Get a reference to the read buffer.
common::SystemError readBuffer (BaseSocket *socket, ssize_t &received)
Reads and appends data to read_buffer.
Protected Attributes
common::Bytes read_buffer
Buffer for (incomplete) request data.
Detailed Description
Class to track a connection.
Definition at line 55 of file tcplistener.hpp.
Constructor & Destructor Documentation
TCPConnectionData()
dodo::network::TCPConnectionData::TCPConnectionData () inline
Construct.
Definition at line 61 of file tcplistener.hpp.
~TCPConnectionData()
virtual dodo::network::TCPConnectionData::~TCPConnectionData () inline virtual
Destruct.
Definition at line 66 of file tcplistener.hpp.
Member Function Documentation
clearBuffer()
void dodo::network::TCPConnectionData::clearBuffer ()
Clears the read_buffer.
Definition at line 62 of file tcplistener.cpp.
getReadBuffer()
const common::Bytes& dodo::network::TCPConnectionData::getReadBuffer () const inline
Get a reference to the read buffer.
Returns
a reference to the read buffer.
Definition at line 85 of file tcplistener.hpp.
References read_buffer.
readBuffer()
common::SystemError dodo::network::TCPConnectionData::readBuffer (BaseSocket * socket, ssize_t & received)
Reads and appends data to read_buffer.
Parameters
socket The socket to read from.
received The number of bytes received.
Returns
The number of bytes read.
Definition at line 38 of file tcplistener.cpp.
References dodo::common::SystemError::asString(), dodo::common::SystemError::ecEAGAIN, dodo::common::SystemError::ecOK, dodo::common::Bytes::getArray(), dodo::network::BaseSocket::getFD(), dodo::common::Bytes::getSize(), dodo::common::Bytes::hexDump(), log_Debug, log_Error, log_Trace, dodo::network::BaseSocket::receive(), and dodo::common::Bytes::reserve().
Referenced by dodo::network::TCPServer::run().
Field Documentation
read_buffer
common::Bytes dodo::network::TCPConnectionData::read_buffer protected
Buffer for (incomplete) request data.
Definition at line 89 of file tcplistener.hpp.
Referenced by getReadBuffer().
The documentation for this class was generated from the following files:
src/include/network/tcplistener.hpp
src/lib/network/tcplistener.cpp