dodo: dodo::network::protocol::http::HTTPRequest Class Reference
dodo::network::protocol::http::HTTPRequest Class Reference
HTTPRequest class represents a HTTP request.
#include <httprequest.hpp>
Data Structures
class HTTPRequestLine
HTTPRequestLine class.
Public Types
enum Method {
meGET, meHEAD, mePOST, mePUT,
mePATCH, meDELETE, meCONNECT, meOPTIONS,
meTRACE, meINVALID
}
The HTTP request method.
Public Types inherited from dodo::network::protocol::http::HTTPFragment
enum ParseError : unsigned int {
peOk = 0, peIncomplete, peSystemError, peExpectCRLF,
peUnFinishedToken, peExpectingHeaderColon, peInvalidHeaderFieldValue, peInvalidHeaderListEnd,
peInvalidMethod, peInvalidHTTPVersion, peInvalidRequestLine, peInvalidContentLength,
peUnexpectedBody, peInvalidTransferEncoding, peInvalidChunkHex, peInvalidLastChunk,
peExpectingUnsignedInt
}
Parse results returned by the parse functions.
Public Member Functions
virtual std::string asString () const
Return the HTTPRequest as a string.
HTTPRequestLine & getRequestLine ()
Get the HTTPRequestLine.
virtual ParseResult parse (VirtualReadBuffer &data)
Read the HTTPRequest from the socket.
virtual ParseResult parseBody (VirtualReadBuffer &data)
Parse a body and resturn it as a single string.
virtual common::SystemError send (BaseSocket *socket)
Send this HTTPMessage to the socket.
void setRequestLine (const HTTPRequestLine &req)
Set the HTTPRequestLine.
common::SystemError write (BaseSocket *socket) const
Write the HTTPRequest to the socket.
Public Member Functions inherited from dodo::network::protocol::http::HTTPMessage
HTTPMessage ()
Default constructor.
void addHeader (const std::string &key, const std::string &value)
Add a header to the HTTPMessage.
void clearHeaders ()
Clear all headers.
const common::Bytes & getBody () const
Return the HTTTMessage body.
const std::map< std::string, std::string > & getHeaders () const
Return a reference to the headers map.
bool getHeaderValue (const std::string &key, std::string &value) const
Get a header value as a string into value.
bool getHeaderValue (const std::string &key, unsigned long &value) const
Get a header value as an unsigned long into value.
bool hasHeader (const std::string &header) const
Return true when this header key exists in this HTTPMessage's headers.
void replaceHeader (const std::string &key, const std::string &value)
Replace the value of a header.
void setBody (const std::string &body)
Set the body.
Static Public Member Functions
static bool methodAllowsBody (Method method)
Return true if the Method allows a body in the message.
static std::string methodAsString (Method method)
Translate a Method enum to a human readable string.
static Method methodFromString (const std::string &s)
Translate an uppercase string ('GET', "POST', ..) into a Method enum.
Static Public Member Functions inherited from dodo::network::protocol::http::HTTPFragment
static std::string getParseResultAsString (ParseError error)
Return the string description of a ParseError.
Protected Attributes
HTTPRequestLine request_line_
The HTTPRequestLine of the HTTPRequest.
Protected Attributes inherited from dodo::network::protocol::http::HTTPMessage
common::Bytes body_
The message body (if any).
std::map< std::string, std::string > headers_
The message headers.
Additional Inherited Members
Static Public Attributes inherited from dodo::network::protocol::http::HTTPMessage
static const char charCR = char(13)
CR character.
static const char charHT = char(9)
Horizontal tab character.
static const char charLF = char(10)
LF character.
static const char charSP = char(32)
Space character.
Protected Member Functions inherited from dodo::network::protocol::http::HTTPMessage
ParseResult eatCRLF (VirtualReadBuffer &data)
Consume a CR LF sequence only when it is there.
ParseResult parseChunkedBody (VirtualReadBuffer &data)
Parse a chunked body (transfer-encoding: chunked) and resturn it as a single string.
ParseResult parseChunkHex (VirtualReadBuffer &data, unsigned long &value)
Parse a hexadecimal chunk size (a hex value followed by CR LF).
ParseResult parseCRLF (VirtualReadBuffer &data)
Consume a CR LF sequence.
ParseResult parseFieldValue (VirtualReadBuffer &data, std::string &value)
Parse a header field value.
ParseResult parseHeaders (VirtualReadBuffer &data)
Parse a header section and update headers_.
ParseResult parseToken (VirtualReadBuffer &buffer, std::string &token)
Parse a token (such as a header field name).
Static Protected Member Functions inherited from dodo::network::protocol::http::HTTPMessage
static common::SystemError eatSpace (VirtualReadBuffer &data)
Call buffer.next() as long as buffer.get() is whitespace (charSP or charHT).
static bool isCTL (char c)
Check is the char is a CTL character.
static bool isSeparator (char c)
Return true if the char is a separator.
static bool isSP (char c)
Return true if the char is whitespace character (charSP or charHT)
static ParseResult parseUInt (VirtualReadBuffer &data, unsigned int &value)
Parse an unsigned integer.
Detailed Description
HTTPRequest class represents a HTTP request.
A HTTPRequest contains
A HTTPRequestLine
An optional body of type common::Bytes.
#include <iostream>
#include <dodo.hpp>
using namespace dodo::network;
using namespace dodo::network::protocol::http;
using namespace dodo::common;
const std::string host = "httpbin.org";
struct RTStats {
  double dns_time = 0.0;
  double handshake_time = 0.0;
  double send_time = 0.0;
  double read_time = 0.0;
  size_t body_bytes = 0;
  size_t underflows = 0;
};
// argv[1] = host
// argv[2] = method
// argv[3] = uri
int main(int argc, char* argv[]) {
  if ( argc < 4 ) return 1;
  int error = 0;
  RTStats rtstats;
  std::string host = argv[1];
  std::string method = argv[2];
  std::string uri = argv[3];
  try {
    dodo::initLibrary();
    StopWatch sw;
    SocketParams sockparams( SocketParams::AddressFamily::afUNSPEC, SocketParams::stSTREAM, SocketParams::pnTCP );
    X509Common::SAN san = {  X509Common::SANType::stDNS, host };
    Address address;
    std::string canonicalname = "";
    sw.start();
    SystemError syserr = Address::getHostAddrInfo( host, sockparams, address, canonicalname );
    rtstats.dns_time = sw.getElapsedSeconds();
    if ( syserr.ok() ) {
      std::cout << host << " = " << address.asString() << std::endl;
      TLSContext tlscontext( TLSContext::PeerVerification::pvVerifyFQDN, TLSContext::TLSVersion::tls1_1, true );
      tlscontext.setOptions( SSL_OP_ALL );
      TLSSocket sock( true, sockparams, tlscontext, san );
      sock.setReceiveBufSize( 8192*100 );
      address.setPort( 443 );
      syserr = sock.connect( address );
      rtstats.handshake_time = sw.getElapsedSeconds();
      if( syserr.ok() ) {
        HTTPRequest req;
        req.getRequestLine().setHTTPVersion( HTTPVersion(1,1) );
        req.getRequestLine().setMethod( HTTPRequest::methodFromString( method ) );
        req.getRequestLine().setRequestURI( uri );
        req.addHeader( "host", host );
        std::cout << "----------------------------------- BEGIN REQ -----------------------------------" << std::endl;
        std::cout << req.asString() << std::endl;
        std::cout << "----------------------------------- END   REQ -----------------------------------" << std::endl;
        //syserr = sock.send( req.asString().c_str(), req.asString().length() );
        syserr = req.send( &sock );
        rtstats.send_time = sw.getElapsedSeconds();
        if ( syserr.ok() ) {
          SocketReadBuffer rbuf( &sock );
          syserr = rbuf.underflow();
          if ( syserr.ok() ) {
            HTTPResponse resp;
            HTTPFragment::ParseResult parse_result = resp.parse( rbuf );
            rtstats.read_time = sw.getElapsedSeconds();
            if ( parse_result.ok() ) {
              rtstats.underflows = rbuf.getUnderflowCount();
              std::cout << "----------------------------------- BEGIN RSP -----------------------------------" << std::endl;
              std::cout << resp.asString() << std::endl;
              rtstats.body_bytes = resp.asString().length();
              std::cout << "----------------------------------- END   RSP -----------------------------------" << std::endl;
            } else {
              std::cerr << "invalid HTTP response: " << parse_result.asString() << std::endl;
              error = 1;
            }
          } else {
            std::cerr << "socket read error: " << syserr.asString() << std::endl;
            error = 1;
          }
          rtstats.read_time = sw.getElapsedSeconds();
        } else {
          std::cerr << "send failed: " << syserr.asString() << std::endl;
          error = 1;
        }
      } else {
        std::cerr << "connect failed: " << syserr.asString() << std::endl;
        error = 1;
      }
    } else {
      std::cerr << "resolving of " << host << " failed : " << syserr.asString() << std::endl;
    }
  }
  catch ( const std::exception &e ) {
    std::cerr << e.what() << std::endl;
    error =  1;
  }
  std::cout << "DNS       " << std::fixed << std::setprecision(3) << rtstats.dns_time*1000 << "ms" << std::endl;
  std::cout << "HANDSHAKE " << std::fixed << std::setprecision(3) << rtstats.handshake_time*1000 << "ms" << std::endl;
  std::cout << "SEND      " << std::fixed << std::setprecision(3) << rtstats.send_time*1000 << "ms" << std::endl;
  std::cout << "RECEIVE   " << std::fixed << std::setprecision(3) << rtstats.read_time*1000 << "ms" << std::endl;
  std::cout << "RSP body size " << std::fixed << std::setprecision(0) << rtstats.body_bytes << "B" << std::endl;
  std::cout << "receive underflows " << std::fixed << std::setprecision(0) << rtstats.underflows << std::endl;
  if ( rtstats.underflows ) std::cout << "receive bytes / roundtrip " << std::fixed << std::setprecision(0) << rtstats.body_bytes/rtstats.underflows << std::endl;
  dodo::closeLibrary();
  return error;
}
Definition at line 42 of file httprequest.hpp.
Member Enumeration Documentation
Method
enum dodo::network::protocol::http::HTTPRequest::Method
The HTTP request method.
Enumerator
meINVALID
The parser was presented an invalid method.
Definition at line 48 of file httprequest.hpp.
Member Function Documentation
asString()
std::string dodo::network::protocol::http::HTTPRequest::asString () const virtual
Return the HTTPRequest as a string.
Returns
the HTTPRequest as a string.
Implements dodo::network::protocol::http::HTTPFragment.
Definition at line 86 of file httprequest.cpp.
References dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::asString(), dodo::common::Bytes::asString(), dodo::network::protocol::http::HTTPMessage::body_, dodo::network::protocol::http::HTTPMessage::charCR, dodo::network::protocol::http::HTTPMessage::charLF, dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::getMethod(), dodo::common::Bytes::getSize(), dodo::network::protocol::http::HTTPMessage::headers_, methodAllowsBody(), and request_line_.
Referenced by write().
getRequestLine()
HTTPRequestLine& dodo::network::protocol::http::HTTPRequest::getRequestLine () inline
Get the HTTPRequestLine.
Returns
The HTTPRequestLine.
Definition at line 170 of file httprequest.hpp.
References request_line_.
methodAllowsBody()
bool dodo::network::protocol::http::HTTPRequest::methodAllowsBody (Method method) static
Return true if the Method allows a body in the message.
Parameters
method the Method to check.
Returns
if the Method allows a body.
Definition at line 60 of file httprequest.cpp.
Referenced by asString(), and send().
methodAsString()
std::string dodo::network::protocol::http::HTTPRequest::methodAsString (Method method) static
Translate a Method enum to a human readable string.
Parameters
method The method to translate.
Returns
the string.
Definition at line 32 of file httprequest.cpp.
Referenced by dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::asString().
methodFromString()
HTTPRequest::Method dodo::network::protocol::http::HTTPRequest::methodFromString (const std::string & s) static
Translate an uppercase string ('GET', "POST', ..) into a Method enum.
Parameters
s The uppercase string to translate.
Returns
the Method (and meINVALID if the string is not a Method).
Definition at line 47 of file httprequest.cpp.
References meINVALID.
Referenced by dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse().
parse()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPRequest::parse (VirtualReadBuffer & data) virtual
Read the HTTPRequest from the socket.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseResult.
Implements dodo::network::protocol::http::HTTPFragment.
Definition at line 114 of file httprequest.cpp.
References dodo::network::protocol::http::HTTPMessage::charCR, dodo::network::protocol::http::HTTPMessage::charLF, dodo::common::SystemError::ecOK, dodo::network::protocol::http::HTTPFragment::ParseResult::eof(), dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), parseBody(), dodo::network::protocol::http::HTTPMessage::parseHeaders(), dodo::network::protocol::http::HTTPFragment::peOk, request_line_, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
parseBody()
HTTPMessage::ParseResult dodo::network::protocol::http::HTTPRequest::parseBody (VirtualReadBuffer & data) virtual
Parse a body and resturn it as a single string.
Note that the content-length header must be present and specify the correct body length.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseError.
Implements dodo::network::protocol::http::HTTPMessage.
Definition at line 139 of file httprequest.cpp.
References dodo::common::Bytes::append(), dodo::network::protocol::http::HTTPMessage::body_, dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), dodo::network::protocol::http::HTTPMessage::getHeaderValue(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPMessage::parseChunkedBody(), dodo::network::protocol::http::HTTPFragment::peInvalidTransferEncoding, dodo::network::protocol::http::HTTPFragment::peUnexpectedBody, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by parse().
send()
common::SystemError dodo::network::protocol::http::HTTPRequest::send (BaseSocket * socket) virtual
Send this HTTPMessage to the socket.
Parameters
socket The socket to write to.
Returns
The commonSystemError that might accour.
Implements dodo::network::protocol::http::HTTPMessage.
Definition at line 99 of file httprequest.cpp.
References dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::asString(), dodo::network::protocol::http::HTTPMessage::body_, dodo::network::protocol::http::HTTPMessage::charCR, dodo::network::protocol::http::HTTPMessage::charLF, dodo::common::Bytes::getArray(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::getMethod(), dodo::common::Bytes::getSize(), dodo::network::protocol::http::HTTPMessage::headers_, methodAllowsBody(), dodo::common::SystemError::ok(), request_line_, and dodo::network::BaseSocket::send().
setRequestLine()
void dodo::network::protocol::http::HTTPRequest::setRequestLine (const HTTPRequestLine & req)
Set the HTTPRequestLine.
Parameters
req The HTTPRequestLine to set.
write()
common::SystemError dodo::network::protocol::http::HTTPRequest::write (BaseSocket * socket) const
Write the HTTPRequest to the socket.
Parameters
socket The BaseSocket to write to.
Returns
The SystemError.
Definition at line 249 of file httprequest.cpp.
References asString(), and dodo::network::BaseSocket::send().
Field Documentation
request_line_
HTTPRequestLine dodo::network::protocol::http::HTTPRequest::request_line_ protected
The HTTPRequestLine of the HTTPRequest.
Definition at line 208 of file httprequest.hpp.
Referenced by asString(), getRequestLine(), parse(), and send().
The documentation for this class was generated from the following files:
src/include/network/protocol/http/httprequest.hpp
src/lib/network/protocol/http/httprequest.cpp