dodo: dodo::network::TLSSocket Class Reference
dodo::network::TLSSocket Class Reference
Socket for TLS encrypted traffic between trusted endpoints.
#include <tlssocket.hpp>
Public Member Functions
TLSSocket (bool blocking, SocketParams params, TLSContext &tlscontext, const X509Common::SAN &peer_name)
Construct from scratch.
TLSSocket (int socket, TLSContext &tlscontext, const X509Common::SAN &peer_name)
Construct from existing socket file descriptor.
virtual ~TLSSocket ()
Destructor.
virtual TLSSocket * accept ()
Accept a connection.
virtual SystemError connect (const Address &address)
Connect to the Address.
X509 * getPeerCertificate () const
Get the peer's certificate.
string getTLSCurrentCipherName () const
Return the negotiated cipher name.
int getTLSProtocolVersion () const
return the negotiated TLS (SSL) protocol version.
string getTLSProtocolVersionString () const
Return the negotiated TLS (SSL) protocol version.
bool operator< (const TLSSocket &socket) const
Ordering.
TLSSocket & operator= (const TLSSocket &socket)
Assign from Socket.
bool operator== (const TLSSocket &socket) const
Identity.
virtual SystemError receive (void *buf, ssize_t request, ssize_t &received)
Receive data.
virtual SystemError send (const void *buf, ssize_t len, bool more=false)
Send data.
Public Member Functions inherited from dodo::network::BaseSocket
BaseSocket ()
Default constructor creates an invalid socket.
BaseSocket (bool blocking, SocketParams params)
Construct from SocketParams.
BaseSocket (int socket)
Construct from a socket descriptor.
virtual ~BaseSocket ()
Destructs this Socket, but does not call close().
SystemError bind (const Address &address)
Bind the socket to the Address.
virtual void close ()
Closes the socket, causing the connection, if it exists, to be terminated.
virtual std::string debugDetail () const
Return debug object state as a string.
Address getAddress () const
Get the local address for this socket.
SocketParams::AddressFamily getAddressFamily () const
Get the SocketParams::AddressFamily of the socket.
virtual bool getBlocking () const
Rerurn true if the socket is operating in blocking mode.
int getFD () const
Return the socket file descriptor.
Address getPeerAddress () const
Get the peer (remote) address for this socket.
SocketParams::ProtocolNumber getProtocolNumber () const
Get the SocketParams::ProtocolNumber of the socket.
virtual socklen_t getReceiveBufSize () const
Get the maximum buffer length for receive.
socklen_t getSendBufSize () const
Get the maximum buffer length for send.
SocketParams getSocketParams () const
Return the SocketParams.
SocketParams::SocketType getSocketType () const
Get the SocketParams::SocketType of the socket.
int getTTL () const
Get the Socket TTL (time to live) or the max number of packet hops.
bool isValid () const
Return true when the socket descriptor is a valid, hence 'possible' descriptor.
SystemError listen (const Address &address, int backlog)
Sets up a listening socket on Address.
bool operator< (const BaseSocket &socket) const
Add ordering.
BaseSocket & operator= (const BaseSocket &socket)
Assign from Socket.
BaseSocket & operator= (int socket)
Assign from existing socket descriptor (int).
bool operator== (const BaseSocket &socket) const
Add identity.
SystemError receiveInt16 (int16_t &value)
receive an int16_t
SystemError receiveInt32 (int32_t &value)
receive an int32_t
SystemError receiveInt64 (int64_t &value)
receive an int64_t
SystemError receiveInt8 (int8_t &value)
receive an int8_t
SystemError receiveLine (string &s)
receive a stream of characters until a '
' is read (consumed from the socket read buffer but not added to s).
SystemError receiveString (string &s)
Receive a std::string as sent by sendString(const std::string&).
SystemError receiveUInt16 (uint16_t &value)
receive an uint16_t
SystemError receiveUInt32 (uint32_t &value)
receive an uint32_t
SystemError receiveUInt64 (uint64_t &value)
receive an uint64_t
SystemError receiveUInt8 (uint8_t &value)
receive an uint8_t
SystemError sendInt16 (int16_t value, bool more=false)
Send an int16_t.
SystemError sendInt32 (int32_t value, bool more=false)
Send an int32_t.
SystemError sendInt64 (int64_t value, bool more=false)
Send an int64_t.
SystemError sendInt8 (int8_t value, bool more=false)
Send an int8_t.
SystemError sendLine (const std::string &s, bool more)
Sends the std::string terminated by a '
'.
SystemError sendString (const std::string &s, bool more=false)
Sends the std::string as understood by receiveString().
SystemError sendUInt16 (uint16_t value, bool more=false)
Send an uint16_t.
SystemError sendUInt32 (uint32_t value, bool more=false)
Send an uint32_t.
SystemError sendUInt64 (uint64_t value, bool more=false)
Send an sendUInt64.
SystemError sendUInt8 (uint8_t value, bool more=false)
Send an uint8_t.
void setBlocking (bool blocking)
Set the Socket blocking mode.
void setReceiveBufSize (socklen_t size)
Set the size of the receive buffer.
void setReceiveTimeout (double sec)
Set the receive timeout - a receive will fail if there is no data received before the timeout expires.
void setReUseAddress ()
Enable the socket to re-use an address when listen/bind is called.
void setReUsePort ()
Make the socket re-use a port when listen is called.
void setSendBufSize (socklen_t size)
Set the size of the send buffer.
void setSendTimeout (double sec)
Set the send timeout - a send will fail if there is no data send before the timeout expires.
void setTCPKeepAlive (bool enable)
Enable or disable TCP keep-alive on the socket.
void setTCPNoDelay (bool set)
Set TCP_NODELAY.
void setTTL (int ttl)
Set the Socket TTL (Time to Live).
Public Member Functions inherited from dodo::common::DebugObject
DebugObject ()
Default constructor does nothing.
virtual ~DebugObject ()
Destructor does nothing.
std::string debugString () const
Return the object dump to string.
Protected Attributes
X509Common::SAN peer_name_
The peer name connected to, for TLS CN and SubjectAltName matching.
SSL * ssl_
The SSL object.
TLSContext & tlscontext_
The TLSContext.
Protected Attributes inherited from dodo::network::BaseSocket
int socket_
The socket file decsriptor.
Additional Inherited Members
Protected Member Functions inherited from dodo::common::DebugObject
std::string debugHeader () const
Generates a debug header (address of this object and a demangled class name.
Detailed Description
Socket for TLS encrypted traffic between trusted endpoints.
Secure sockets
Definition at line 42 of file tlssocket.hpp.
Constructor & Destructor Documentation
TLSSocket() [1/2]
dodo::network::TLSSocket::TLSSocket (int socket, TLSContext & tlscontext, const X509Common::SAN & peer_name)
Construct from existing socket file descriptor.
Parameters
socket The socket file descriptor.
tlscontext The TLSContext to apply.
peer_name The peer name to validate against the peer certificate CN and SubjectAltNames. Only used when the tlscontext has pvVerifyFQDN set (and possibly when pvCustom is set).
Definition at line 32 of file tlssocket.cpp.
Referenced by accept().
TLSSocket() [2/2]
dodo::network::TLSSocket::TLSSocket (bool blocking, SocketParams params, TLSContext & tlscontext, const X509Common::SAN & peer_name)
Construct from scratch.
Parameters
blocking If true, operate in blocking mode.
params The SocketParams to apply.
tlscontext The TLSContext to apply.
peer_name The peer name to validate against the peer certificate CN and SubjectAltNames. Only used when the tlscontext has pvVerifyFQDN set (and possibly when pvCustom is set).
Definition at line 39 of file tlssocket.cpp.
References dodo::common::getSSLErrors(), dodo::network::TLSContext::isSNIEnabled(), peer_name_, dodo::network::X509Common::SAN::san_name, dodo::network::BaseSocket::socket_, ssl_, and throw_Exception.
~TLSSocket()
dodo::network::TLSSocket::~TLSSocket () virtual
Destructor.
Definition at line 52 of file tlssocket.cpp.
References ssl_.
Member Function Documentation
accept()
TLSSocket * dodo::network::TLSSocket::accept () virtual
Accept a connection.
Returns
The SystemError.
Implements dodo::network::BaseSocket.
Definition at line 82 of file tlssocket.cpp.
References dodo::common::getSSLErrors(), log_Error, ssl_, dodo::network::X509Common::stDNS, tlscontext_, and TLSSocket().
connect()
SystemError dodo::network::TLSSocket::connect (const Address & address) virtual
Connect to the Address.
Parameters
address The address to connect to.
Returns
The SystemError code.
Reimplemented from dodo::network::BaseSocket.
Definition at line 56 of file tlssocket.cpp.
References dodo::network::BaseSocket::connect(), dodo::common::SystemError::ecOK, dodo::common::SystemError::ecSSL_ERROR_NONE, dodo::common::SystemError::ecSSL_ERROR_PEERVERIFICATION, dodo::common::SystemError::ecSSL_ERROR_WANT_ACCEPT, dodo::common::SystemError::ecSSL_ERROR_WANT_CONNECT, dodo::common::SystemError::ecSSL_ERROR_WANT_READ, dodo::common::SystemError::ecSSL_ERROR_WANT_WRITE, dodo::common::SystemError::ecSSL_ERROR_WANT_X509_LOOKUP, dodo::common::SystemError::ecSSL_ERROR_ZERO_RETURN, getPeerCertificate(), dodo::network::TLSContext::getPeerVerification(), dodo::common::getSSLErrors(), peer_name_, dodo::network::TLSContext::pvVerifyFQDN, dodo::network::X509Common::SAN::san_name, ssl_, dodo::network::X509Common::stDNS, throw_Exception, tlscontext_, and dodo::network::X509Certificate::verifySAN().
getPeerCertificate()
X509 * dodo::network::TLSSocket::getPeerCertificate () const
Get the peer's certificate.
Returns
A pointer to the peer certificate (must not be freed).
Definition at line 95 of file tlssocket.cpp.
References ssl_.
Referenced by connect().
getTLSCurrentCipherName()
string dodo::network::TLSSocket::getTLSCurrentCipherName () const inline
Return the negotiated cipher name.
This is only meaningful after a connect returned SystemError::ecOK.
Returns
the TLS (SSL) protocol version.
Definition at line 154 of file tlssocket.hpp.
References ssl_.
getTLSProtocolVersion()
int dodo::network::TLSSocket::getTLSProtocolVersion () const inline
return the negotiated TLS (SSL) protocol version.
This is only meaningfull after a connect returned SystemError::ecOK.
Returns
the TLS (SSL) protocol version.
Definition at line 136 of file tlssocket.hpp.
References ssl_.
getTLSProtocolVersionString()
string dodo::network::TLSSocket::getTLSProtocolVersionString () const inline
Return the negotiated TLS (SSL) protocol version.
This is only meaningful after a connect returned SystemError::ecOK.
Returns
the TLS (SSL) protocol version.
Definition at line 145 of file tlssocket.hpp.
References ssl_.
operator<()
bool dodo::network::TLSSocket::operator< (const TLSSocket & socket) const inline
Ordering.
Parameters
socket The socket to compare to.
Returns
True if this Socket has a smaller socket descriptor than socket.
Definition at line 122 of file tlssocket.hpp.
References dodo::network::BaseSocket::socket_.
operator=()
TLSSocket & dodo::network::TLSSocket::operator= (const TLSSocket & socket)
Assign from Socket.
Parameters
socket The Socket to assign/copy to this Socket.
Returns
this TLSSocket.
Definition at line 136 of file tlssocket.cpp.
References dodo::network::BaseSocket::socket_, ssl_, and tlscontext_.
operator==()
bool dodo::network::TLSSocket::operator== (const TLSSocket & socket) const inline
Identity.
Parameters
socket The socket to compare to.
Returns
True if both sockets are equal and have the same value in socket_.
Definition at line 115 of file tlssocket.hpp.
References dodo::network::BaseSocket::socket_.
receive()
SystemError dodo::network::TLSSocket::receive (void * buf, ssize_t request, ssize_t & received) virtual
Receive data.
Parameters
buf Buffer to receive in
request Max bytes to receive in buf
received Actual received bytes
Returns
The SystemError code.
Implements dodo::network::BaseSocket.
Definition at line 117 of file tlssocket.cpp.
References dodo::common::SystemError::ecOK, dodo::common::SystemError::ecSSL_ERROR_NONE, dodo::common::SystemError::ecSSL_ERROR_WANT_ACCEPT, dodo::common::SystemError::ecSSL_ERROR_WANT_CONNECT, dodo::common::SystemError::ecSSL_ERROR_WANT_READ, dodo::common::SystemError::ecSSL_ERROR_WANT_WRITE, dodo::common::SystemError::ecSSL_ERROR_WANT_X509_LOOKUP, dodo::common::SystemError::ecSSL_ERROR_ZERO_RETURN, dodo::common::getSSLErrors(), ssl_, and throw_Exception.
send()
SystemError dodo::network::TLSSocket::send (const void * buf, ssize_t len, bool more = false) virtual
Send data.
Parameters
buf Data to send
len Size of data in buf
more If true, do not force a send buffer flush, more data will follow
Returns
The SystemError code.
Implements dodo::network::BaseSocket.
Definition at line 99 of file tlssocket.cpp.
References dodo::common::SystemError::ecOK, dodo::common::SystemError::ecSSL_ERROR_NONE, dodo::common::SystemError::ecSSL_ERROR_WANT_ACCEPT, dodo::common::SystemError::ecSSL_ERROR_WANT_CONNECT, dodo::common::SystemError::ecSSL_ERROR_WANT_READ, dodo::common::SystemError::ecSSL_ERROR_WANT_WRITE, dodo::common::SystemError::ecSSL_ERROR_WANT_X509_LOOKUP, dodo::common::SystemError::ecSSL_ERROR_ZERO_RETURN, dodo::common::getSSLErrors(), ssl_, and throw_Exception.
Field Documentation
peer_name_
X509Common::SAN dodo::network::TLSSocket::peer_name_ protected
The peer name connected to, for TLS CN and SubjectAltName matching.
Definition at line 173 of file tlssocket.hpp.
Referenced by connect(), and TLSSocket().
ssl_
SSL* dodo::network::TLSSocket::ssl_ protected
The SSL object.
Definition at line 163 of file tlssocket.hpp.
Referenced by accept(), connect(), getPeerCertificate(), getTLSCurrentCipherName(), getTLSProtocolVersion(), getTLSProtocolVersionString(), operator=(), receive(), send(), TLSSocket(), and ~TLSSocket().
tlscontext_
TLSContext& dodo::network::TLSSocket::tlscontext_ protected
The TLSContext.
Definition at line 168 of file tlssocket.hpp.
Referenced by accept(), connect(), and operator=().
The documentation for this class was generated from the following files:
src/include/network/tlssocket.hpp
src/lib/network/tlssocket.cpp