dodo: dodo::persist::sqlite::DDL Class Reference
dodo::persist::sqlite::DDL Class Reference
Data Definition Language, SQL that takes no parameters, returns no data such as CREATE TABLE.
#include <sqlite.hpp>
Public Member Functions
DDL (const Database &db)
Constructor.
virtual ~DDL ()
Destructor.
void execute ()
execute, throws Oops on error.
int execute_r ()
execute and return result code.
Public Member Functions inherited from dodo::persist::sqlite::Statement
Statement (const Database &db)
Constructor.
virtual ~Statement ()
Destructor.
void close ()
A statement handle can be explicitly closed without deleting the Statement object itself.
void prepare (const std::string &sql)
Prepare a SQL statement.
void reset (bool clear=true)
Reset a SQL statement for re-execute or even re-prepare.
Additional Inherited Members
Protected Attributes inherited from dodo::persist::sqlite::Statement
sqlite3 * database_
database handle on which the stmt_ is created.
sqlite3_stmt * stmt_
statement handle.
Detailed Description
Data Definition Language, SQL that takes no parameters, returns no data such as CREATE TABLE.
Definition at line 261 of file sqlite.hpp.
Constructor & Destructor Documentation
DDL()
dodo::persist::sqlite::DDL::DDL (const Database & db) inline
Constructor.
Parameters
db Yhe database context.
Definition at line 268 of file sqlite.hpp.
~DDL()
virtual dodo::persist::sqlite::DDL::~DDL () inline virtual
Destructor.
Parameters
db Yhe database context.
Definition at line 274 of file sqlite.hpp.
Member Function Documentation
execute()
void dodo::persist::sqlite::DDL::execute ()
execute, throws Oops on error.
See also
execute_r
Definition at line 393 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::database_, dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
Referenced by dodo::persist::sqlite::Database::beginExclusiveTransaction(), dodo::persist::sqlite::Database::beginImmediateTransaction(), dodo::persist::sqlite::Database::beginTransaction(), dodo::persist::sqlite::Database::commit(), dodo::persist::sqlite::Database::createSavepoint(), dodo::persist::KVStore::createSchema(), dodo::persist::KVStore::optimize(), dodo::persist::KVStore::prepareSQL(), dodo::persist::sqlite::Database::releaseSavepoint(), dodo::persist::sqlite::Database::rollback(), dodo::persist::sqlite::Database::setUserVersion(), dodo::persist::KVStore::startTransaction(), and dodo::persist::KVStore::vacuum().
execute_r()
int dodo::persist::sqlite::DDL::execute_r ()
execute and return result code.
Returns
the SQLite error code.
See also
execute
Definition at line 400 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::stmt_.
The documentation for this class was generated from the following files:
src/include/persist/sqlite/sqlite.hpp
src/lib/persist/sqlite/sqlite.cpp