dodo: dodo::common::DebugObject Class Reference
dodo::common::DebugObject Class Reference
Interface to objects that support dumping their state to a string.
#include <exception.hpp>
Public Member Functions
DebugObject ()
Default constructor does nothing.
virtual ~DebugObject ()
Destructor does nothing.
std::string debugString () const
Return the object dump to string.
Protected Member Functions
virtual std::string debugDetail () const
Descendant classes can override to dump details specific to the class.
std::string debugHeader () const
Generates a debug header (address of this object and a demangled class name.
Detailed Description
Interface to objects that support dumping their state to a string.
Definition at line 39 of file exception.hpp.
Constructor & Destructor Documentation
DebugObject()
dodo::common::DebugObject::DebugObject () inline
Default constructor does nothing.
Definition at line 45 of file exception.hpp.
~DebugObject()
virtual dodo::common::DebugObject::~DebugObject () inline virtual
Destructor does nothing.
Definition at line 50 of file exception.hpp.
Member Function Documentation
debugDetail()
virtual std::string dodo::common::DebugObject::debugDetail () const inline protected virtual
Descendant classes can override to dump details specific to the class.
By default, returns nothing.
Returns
The string.
Reimplemented in dodo::network::BaseSocket.
Definition at line 66 of file exception.hpp.
Referenced by debugString().
debugHeader()
std::string dodo::common::DebugObject::debugHeader () const protected
Generates a debug header (address of this object and a demangled class name.
Returns
The string.
Definition at line 39 of file exception.cpp.
Referenced by debugString().
debugString()
std::string dodo::common::DebugObject::debugString () const
Return the object dump to string.
debugHeader() and debugDetail() is integrated in the dump.
Returns
that string.
See also
debugHeader()
debugDetail()
Definition at line 32 of file exception.cpp.
References debugDetail(), and debugHeader().
Referenced by dodo::common::Exception::Exception(), dodo::network::TCPListener::pollAdd(), dodo::network::TCPListener::pollDel(), dodo::network::TCPListener::pollMod(), dodo::network::TCPListener::popWork(), dodo::network::TCPListener::pushWork(), dodo::network::TCPListener::releaseWork(), dodo::network::TCPServer::run(), and dodo::network::TCPListener::run().
The documentation for this class was generated from the following files:
src/include/common/exception.hpp
src/lib/common/exception.cpp