dodo: dodo::network::SocketParams Class Reference
dodo::network::SocketParams Class Reference
Socket parameters - the family (domain), socket type and protocol triplet.
#include <socketparams.hpp>
Public Types
enum AddressFamily {
afLOCAL = AF_LOCAL, afINET = AF_INET, afINET6 = AF_INET6, afIPX = AF_IPX,
afNETLINK = AF_NETLINK, afX25 = AF_X25, afAX25 = AF_AX25, afATMPVC = AF_ATMPVC,
afAPPLETALK = AF_APPLETALK, afPACKET = AF_PACKET, afALG = AF_ALG, afUNSPEC = AF_UNSPEC
}
Addres family type.
enum ProtocolNumber {
pnHOPOPT = 0, pnICMP = IPPROTO_ICMP, pnICMPV6 = IPPROTO_ICMPV6, pnIGMP = 2,
pnGGP = 3, pnIPv4 = 4, pnST = 5, pnTCP = 6,
pnCBT = 7, pnEGP = 8, pnIGP = 9, pnBBN_RCC_MON = 10,
pnNVP_II = 11, pnPUP = 12, pnARGUS = 13, pnEMCON = 14,
pnXNET = 15, pnCHAOS = 16, pnUDP = 17, pnMUX = 18,
pnDCN_MEAS = 19, pnHMP = 20, pnPRM = 21, pnXNS_IDP = 22,
pnTRUNK_1 = 23, pnTRUNK_2 = 24, pnLEAF_1 = 25, pnLEAF_2 = 26,
pnRDP = 27, pnIRTP = 28, pnISO_TP4 = 29, pnNETBLT = 30,
pnMFE_NSP = 31, pnMERIT_INP = 32, pnDCCP = 33, pn3PC = 34,
pnIDPR = 35, pnXTP = 36, pnDDP = 37, pnIDPR_CMTP = 38
}
IANA Protocol number.
enum SocketType {
stSTREAM = SOCK_STREAM, stDGRAM = SOCK_DGRAM, stSEQPACKET = SOCK_SEQPACKET, stRAW = SOCK_RAW,
stRDM = SOCK_RDM, stPACKET = SOCK_PACKET
}
Socket Type type.
Public Member Functions
SocketParams ()
Default constructor to AF_INET6, SOCK_STREAM, protocol pnHOPOPT.
SocketParams (AddressFamily family)
Constructor only sets the AddressFamily.
SocketParams (AddressFamily family, SocketType sockettype)
Constructor sets the AddressFamily and SocketType.
SocketParams (AddressFamily family, SocketType sockettype, ProtocolNumber protocol)
Constructor sets the AddressFamily, SocketType and ProtocolNumber.
std::string asString () const
Return the parameters as a string.
AddressFamily getAddressFamily () const
Get the AddressFamily.
ProtocolNumber getProtocol () const
Get the ProtocolNumber.
SocketType getSocketType () const
Get the SocketType.
void setAddressFamily (AddressFamily family)
Set the AddressFamily.
void setProtocol (ProtocolNumber protocol)
Set the ProtocolNumber.
void setSocketType (SocketType sockettype)
Set the SocketType.
Static Public Member Functions
static std::string familyString (AddressFamily family)
Return the AddressFamily name as a string.
static std::string protocolString (ProtocolNumber protocol)
Return the ProtocolNumber name as a string.
static std::string socketTypeString (SocketType sockettype)
Return the SocketType name as a string.
Private Attributes
AddressFamily family_
The address family.
ProtocolNumber protocol_
The protocol.
SocketType sockettype_
The socket type.
Detailed Description
Socket parameters - the family (domain), socket type and protocol triplet.
Definition at line 35 of file socketparams.hpp.
Member Enumeration Documentation
AddressFamily
enum dodo::network::SocketParams::AddressFamily
Addres family type.
Definition at line 41 of file socketparams.hpp.
ProtocolNumber
enum dodo::network::SocketParams::ProtocolNumber
IANA Protocol number.
https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
Definition at line 73 of file socketparams.hpp.
SocketType
enum dodo::network::SocketParams::SocketType
Socket Type type.
Definition at line 59 of file socketparams.hpp.
Constructor & Destructor Documentation
SocketParams() [1/4]
dodo::network::SocketParams::SocketParams () inline
Default constructor to AF_INET6, SOCK_STREAM, protocol pnHOPOPT.
Definition at line 119 of file socketparams.hpp.
SocketParams() [2/4]
dodo::network::SocketParams::SocketParams (AddressFamily family) inline
Constructor only sets the AddressFamily.
Parameters
family The AddressFamily.
Definition at line 125 of file socketparams.hpp.
SocketParams() [3/4]
dodo::network::SocketParams::SocketParams (AddressFamily family, SocketType sockettype) inline
Constructor sets the AddressFamily and SocketType.
Parameters
family The AddressFamily.
sockettype The SocketType.
Definition at line 132 of file socketparams.hpp.
SocketParams() [4/4]
dodo::network::SocketParams::SocketParams (AddressFamily family, SocketType sockettype, ProtocolNumber protocol) inline
Constructor sets the AddressFamily, SocketType and ProtocolNumber.
Parameters
family The AddressFamily.
sockettype The SocketType.
protocol The ProtocolNumber.
Definition at line 141 of file socketparams.hpp.
Member Function Documentation
asString()
std::string dodo::network::SocketParams::asString () const inline
Return the parameters as a string.
Returns
The string.
Definition at line 184 of file socketparams.hpp.
References family_, familyString(), protocol_, protocolString(), sockettype_, and socketTypeString().
Referenced by dodo::network::AddrInfoItem::asString().
familyString()
static std::string dodo::network::SocketParams::familyString (AddressFamily family) inline static
Return the AddressFamily name as a string.
Parameters
family The AddressFamily to convert.
Returns
The string.
Definition at line 198 of file socketparams.hpp.
Referenced by asString().
getAddressFamily()
AddressFamily dodo::network::SocketParams::getAddressFamily () const inline
Get the AddressFamily.
Returns
The AddressFamily.
Definition at line 148 of file socketparams.hpp.
References family_.
Referenced by dodo::network::BaseSocket::BaseSocket(), and dodo::network::Address::getHostAddrInfo().
getProtocol()
ProtocolNumber dodo::network::SocketParams::getProtocol () const inline
Get the ProtocolNumber.
Returns
The ProtocolNumber.
Definition at line 160 of file socketparams.hpp.
References protocol_.
Referenced by dodo::network::BaseSocket::BaseSocket(), and dodo::network::Address::getHostAddrInfo().
getSocketType()
SocketType dodo::network::SocketParams::getSocketType () const inline
Get the SocketType.
Returns
The SocketType.
Definition at line 154 of file socketparams.hpp.
References sockettype_.
Referenced by dodo::network::BaseSocket::BaseSocket(), and dodo::network::Address::getHostAddrInfo().
protocolString()
static std::string dodo::network::SocketParams::protocolString (ProtocolNumber protocol) inline static
Return the ProtocolNumber name as a string.
Parameters
protocol The ProtocolNumber to convert.
Returns
The string.
Definition at line 243 of file socketparams.hpp.
Referenced by asString().
setAddressFamily()
void dodo::network::SocketParams::setAddressFamily (AddressFamily family) inline
Set the AddressFamily.
Parameters
family The AddressFamily.
Definition at line 166 of file socketparams.hpp.
References family_.
Referenced by dodo::network::Address::getHostAddrInfo().
setProtocol()
void dodo::network::SocketParams::setProtocol (ProtocolNumber protocol) inline
Set the ProtocolNumber.
Parameters
protocol The ProtocolNumber.
Definition at line 178 of file socketparams.hpp.
References protocol_.
Referenced by dodo::network::Address::getHostAddrInfo().
setSocketType()
void dodo::network::SocketParams::setSocketType (SocketType sockettype) inline
Set the SocketType.
Parameters
sockettype The SocketType.
Definition at line 172 of file socketparams.hpp.
References sockettype_.
Referenced by dodo::network::Address::getHostAddrInfo().
socketTypeString()
static std::string dodo::network::SocketParams::socketTypeString (SocketType sockettype) inline static
Return the SocketType name as a string.
Parameters
sockettype The SocketType to convert.
Returns
The string.
Definition at line 223 of file socketparams.hpp.
Referenced by asString().
Field Documentation
family_
AddressFamily dodo::network::SocketParams::family_ private
The address family.
Definition at line 270 of file socketparams.hpp.
Referenced by asString(), getAddressFamily(), and setAddressFamily().
protocol_
ProtocolNumber dodo::network::SocketParams::protocol_ private
The protocol.
Definition at line 286 of file socketparams.hpp.
Referenced by asString(), getProtocol(), and setProtocol().
sockettype_
SocketType dodo::network::SocketParams::sockettype_ private
The socket type.
Definition at line 281 of file socketparams.hpp.
Referenced by asString(), getSocketType(), and setSocketType().
The documentation for this class was generated from the following file:
src/include/network/socketparams.hpp