dodo: dodo::threads::Thread Class Reference
dodo::threads::Thread Class Reference abstract
Abstract Thread class.
#include <thread.hpp>
Public Member Functions
Thread ()
Constructor.
virtual ~Thread ()
Destructor.
double getAvgBlkInRate ()
Get the average block in rate since thread start()
double getAvgBlkOutRate ()
Get the average block out rate since thread start()
double getAvgICtx ()
Get the average involuntary context switch rate since thread start()
double getAvgMajFltRate ()
Get the average major fault rate since thread start()
double getAvgMinFltRate ()
Get the average minor fault rate since thread start()
double getAvgSysCPU ()
Get the average system mode cpu (cpu seconds/second) since thread start()
double getAvgUserCPU ()
Get the average user mode cpu (cpu seconds/second) since thread start()
double getAvgVCtx ()
Get the average voluntary context switch rate since thread start()
std::thread::id getId () const
Get the thread id.
double getLastBlkInRate ()
Get last block in rate since last sample.
double getLastBlkOutRate ()
Get last block out rate since last sample.
double getLastICtx ()
Get involuntary context switch rate since last sample.
double getLastMajFltRate ()
Get the major fault rate since last sample.
double getLastMinFltRate ()
Get the minor fault rate since last sample.
double getLastSysCPU ()
Get the system mode cpu (cpu seconds/second) since last sample.
double getLastUserCPU ()
Get the user mode cpu (cpu seconds/second) since last sample.
double getLastVCtx ()
Get voluntary context switch rate since last sample.
long getMaxRSS ()
Get the maximum resident set size seen on the thread.
double getRunTime ()
Time, in seconds, since thread start.
double getSnapDiffTime ()
Time, in seconds, since last statistic update.
pid_t getTID () const
Return the tid.
void snapRUsage ()
Take a snapshot of the thread's resource usage.
void start ()
Start the thread.
void wait ()
Wait for the thread to join the current thread / wait for the thread to finish.
Protected Member Functions
virtual void run ()=0
Decsendants must override the run function.
Protected Attributes
struct rusage prev_rusage_
Previous statistics.
struct timeval prev_snap_time_
Time of previous statistics snapshot.
struct rusage rusage_
Last statistics.
struct timeval snap_time_
Time of last statistics snapshot.
struct timeval start_time_
Time Thread started.
std::thread * thread_
The std::tread object.
Static Private Member Functions
static void * thread_method (void *context)
Posix thread method - calls dodo::threads::Thread:::run().
Private Attributes
pid_t tid_
The linux tid.
Detailed Description
Abstract Thread class.
Inherit and implement pure virtual run() to run threaded code.
Definition at line 38 of file thread.hpp.
Constructor & Destructor Documentation
Thread()
dodo::threads::Thread::Thread ()
Constructor.
Definition at line 42 of file thread.cpp.
References prev_rusage_, prev_snap_time_, rusage_, snap_time_, and start_time_.
~Thread()
dodo::threads::Thread::~Thread () virtual
Destructor.
Definition at line 51 of file thread.cpp.
References thread_.
Member Function Documentation
getAvgBlkInRate()
double dodo::threads::Thread::getAvgBlkInRate ()
Get the average block in rate since thread start()
Returns
that rate.
Definition at line 93 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgBlkOutRate()
double dodo::threads::Thread::getAvgBlkOutRate ()
Get the average block out rate since thread start()
Returns
that rate.
Definition at line 97 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgICtx()
double dodo::threads::Thread::getAvgICtx ()
Get the average involuntary context switch rate since thread start()
Returns
that rate.
Definition at line 105 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgMajFltRate()
double dodo::threads::Thread::getAvgMajFltRate ()
Get the average major fault rate since thread start()
Returns
that rate.
Definition at line 89 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgMinFltRate()
double dodo::threads::Thread::getAvgMinFltRate ()
Get the average minor fault rate since thread start()
Returns
that rate.
Definition at line 85 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgSysCPU()
double dodo::threads::Thread::getAvgSysCPU ()
Get the average system mode cpu (cpu seconds/second) since thread start()
Returns
that utilization.
Definition at line 81 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgUserCPU()
double dodo::threads::Thread::getAvgUserCPU ()
Get the average user mode cpu (cpu seconds/second) since thread start()
Returns
that utilization.
Definition at line 77 of file thread.cpp.
References getRunTime(), and rusage_.
getAvgVCtx()
double dodo::threads::Thread::getAvgVCtx ()
Get the average voluntary context switch rate since thread start()
Returns
that rate.
Definition at line 101 of file thread.cpp.
References getRunTime(), and rusage_.
getId()
std::thread::id dodo::threads::Thread::getId () const
Get the thread id.
Returns
that id.
Definition at line 72 of file thread.cpp.
References thread_.
getLastBlkInRate()
double dodo::threads::Thread::getLastBlkInRate ()
Get last block in rate since last sample.
Returns
that rate.
Definition at line 133 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastBlkOutRate()
double dodo::threads::Thread::getLastBlkOutRate ()
Get last block out rate since last sample.
Returns
that rate.
Definition at line 138 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastICtx()
double dodo::threads::Thread::getLastICtx ()
Get involuntary context switch rate since last sample.
Returns
that rate.
Definition at line 148 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastMajFltRate()
double dodo::threads::Thread::getLastMajFltRate ()
Get the major fault rate since last sample.
Returns
that rate.
Definition at line 128 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastMinFltRate()
double dodo::threads::Thread::getLastMinFltRate ()
Get the minor fault rate since last sample.
Returns
that rate.
Definition at line 123 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastSysCPU()
double dodo::threads::Thread::getLastSysCPU ()
Get the system mode cpu (cpu seconds/second) since last sample.
Returns
that utilization.
Definition at line 118 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastUserCPU()
double dodo::threads::Thread::getLastUserCPU ()
Get the user mode cpu (cpu seconds/second) since last sample.
Returns
that utilization.
Definition at line 113 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getLastVCtx()
double dodo::threads::Thread::getLastVCtx ()
Get voluntary context switch rate since last sample.
Returns
that rate.
Definition at line 143 of file thread.cpp.
References getSnapDiffTime(), prev_rusage_, and rusage_.
Referenced by dodo::network::TCPListener::logStats().
getMaxRSS()
long dodo::threads::Thread::getMaxRSS ()
Get the maximum resident set size seen on the thread.
Returns
that size.
Definition at line 109 of file thread.cpp.
References rusage_.
Referenced by dodo::network::TCPListener::logStats().
getRunTime()
double dodo::threads::Thread::getRunTime ()
Time, in seconds, since thread start.
Returns
that time.
Definition at line 153 of file thread.cpp.
References dodo::common::getSecondDiff(), snap_time_, and start_time_.
Referenced by getAvgBlkInRate(), getAvgBlkOutRate(), getAvgICtx(), getAvgMajFltRate(), getAvgMinFltRate(), getAvgSysCPU(), getAvgUserCPU(), and getAvgVCtx().
getSnapDiffTime()
double dodo::threads::Thread::getSnapDiffTime ()
Time, in seconds, since last statistic update.
Returns
that time.
Definition at line 157 of file thread.cpp.
References dodo::common::getSecondDiff(), prev_snap_time_, and snap_time_.
Referenced by getLastBlkInRate(), getLastBlkOutRate(), getLastICtx(), getLastMajFltRate(), getLastMinFltRate(), getLastSysCPU(), getLastUserCPU(), and getLastVCtx().
getTID()
pid_t dodo::threads::Thread::getTID () const inline
Return the tid.
Returns
the TID.
Definition at line 190 of file thread.hpp.
References tid_.
Referenced by dodo::network::TCPListener::cleanStoppedServers().
run()
virtual void dodo::threads::Thread::run () protected pure virtual
Decsendants must override the run function.
Returns
nothing
Implemented in dodo::network::TCPListener, dodo::network::TCPServer, and dodo::network::TCPListenerTimer.
Referenced by thread_method().
snapRUsage()
void dodo::threads::Thread::snapRUsage ()
Take a snapshot of the thread's resource usage.
Definition at line 65 of file thread.cpp.
References prev_rusage_, prev_snap_time_, rusage_, and snap_time_.
Referenced by dodo::network::TCPListener::logStats(), dodo::network::TCPServer::run(), and thread_method().
start()
void dodo::threads::Thread::start ()
Start the thread.
Definition at line 55 of file thread.cpp.
References thread_, and thread_method().
Referenced by dodo::network::TCPListener::addServers(), dodo::network::TCPListener::cleanStoppedServers(), and dodo::network::TCPListener::run().
thread_method()
void * dodo::threads::Thread::thread_method (void * context) static private
Posix thread method - calls dodo::threads::Thread:::run().
Parameters
context Is used to pass a Thread* so that its run() method can be called.
Returns
nullptr (always)
Definition at line 33 of file thread.cpp.
References run(), snapRUsage(), start_time_, and tid_.
Referenced by start().
wait()
void dodo::threads::Thread::wait ()
Wait for the thread to join the current thread / wait for the thread to finish.
Definition at line 61 of file thread.cpp.
References thread_.
Referenced by dodo::network::TCPListener::cleanStoppedServers().
Field Documentation
prev_rusage_
struct rusage dodo::threads::Thread::prev_rusage_ protected
Previous statistics.
Definition at line 223 of file thread.hpp.
Referenced by getLastBlkInRate(), getLastBlkOutRate(), getLastICtx(), getLastMajFltRate(), getLastMinFltRate(), getLastSysCPU(), getLastUserCPU(), getLastVCtx(), snapRUsage(), and Thread().
prev_snap_time_
struct timeval dodo::threads::Thread::prev_snap_time_ protected
Time of previous statistics snapshot.
Definition at line 213 of file thread.hpp.
Referenced by getSnapDiffTime(), snapRUsage(), and Thread().
rusage_
struct rusage dodo::threads::Thread::rusage_ protected
Last statistics.
Definition at line 228 of file thread.hpp.
Referenced by getAvgBlkInRate(), getAvgBlkOutRate(), getAvgICtx(), getAvgMajFltRate(), getAvgMinFltRate(), getAvgSysCPU(), getAvgUserCPU(), getAvgVCtx(), getLastBlkInRate(), getLastBlkOutRate(), getLastICtx(), getLastMajFltRate(), getLastMinFltRate(), getLastSysCPU(), getLastUserCPU(), getLastVCtx(), getMaxRSS(), snapRUsage(), and Thread().
snap_time_
struct timeval dodo::threads::Thread::snap_time_ protected
Time of last statistics snapshot.
Definition at line 218 of file thread.hpp.
Referenced by getRunTime(), getSnapDiffTime(), snapRUsage(), and Thread().
start_time_
struct timeval dodo::threads::Thread::start_time_ protected
Time Thread started.
Definition at line 208 of file thread.hpp.
Referenced by getRunTime(), Thread(), and thread_method().
thread_
std::thread* dodo::threads::Thread::thread_ protected
The std::tread object.
Definition at line 203 of file thread.hpp.
Referenced by getId(), start(), wait(), and ~Thread().
tid_
pid_t dodo::threads::Thread::tid_ private
The linux tid.
Definition at line 242 of file thread.hpp.
Referenced by getTID(), and thread_method().
The documentation for this class was generated from the following files:
src/include/threads/thread.hpp
src/lib/threads/thread.cpp