dodo: dodo::common::UnitTest Class Reference
dodo::common::UnitTest Class Reference abstract
Unit test assitence class.
#include <unittest.hpp>
Public Member Functions
UnitTest (const string &name, const string &description, ostream *out)
Create a test.
virtual ~UnitTest ()
Destructor.
bool run ()
Run the test.
Protected Member Functions
virtual void doRun ()=0
Virtual to implement the test.
bool writeSubTestResult (const string &name, const string &description, bool passed)
Write the subtest result.
Private Member Functions
void writeUnitTestHeader ()
Write the header.
void writeUnitTestSummary ()
Write the summary.
Private Attributes
string description_
The test description.
size_t failed_
The total number of failed tests.
string name_
The test name.
ostream * out_
The output destination.
size_t total_
The total number of tests.
Detailed Description
Unit test assitence class.
Definition at line 36 of file unittest.hpp.
Constructor & Destructor Documentation
UnitTest()
dodo::common::UnitTest::UnitTest (const string & name, const string & description, ostream * out)
Create a test.
Parameters
name The name of the test.
description The description of the test.
out The ostream to write to.
Definition at line 27 of file unittest.cpp.
~UnitTest()
virtual dodo::common::UnitTest::~UnitTest () inline virtual
Destructor.
Definition at line 50 of file unittest.hpp.
Member Function Documentation
doRun()
virtual void dodo::common::UnitTest::doRun () protected pure virtual
Virtual to implement the test.
Returns
nothing
Referenced by run().
run()
bool dodo::common::UnitTest::run ()
Run the test.
Returns
True if the test passed.
Definition at line 35 of file unittest.cpp.
References doRun(), failed_, writeUnitTestHeader(), and writeUnitTestSummary().
writeSubTestResult()
bool dodo::common::UnitTest::writeSubTestResult (const string & name, const string & description, bool passed) protected
Write the subtest result.
Parameters
name The name of the test.
description The description of the test.
passed True if the test passed.
Returns
The value of parameter passed.
Definition at line 55 of file unittest.cpp.
References failed_, out_, and total_.
writeUnitTestHeader()
void dodo::common::UnitTest::writeUnitTestHeader () private
Write the header.
Definition at line 42 of file unittest.cpp.
References description_, name_, and out_.
Referenced by run().
writeUnitTestSummary()
void dodo::common::UnitTest::writeUnitTestSummary () private
Write the summary.
Definition at line 49 of file unittest.cpp.
References failed_, out_, and total_.
Referenced by run().
Field Documentation
description_
string dodo::common::UnitTest::description_ private
The test description.
Definition at line 87 of file unittest.hpp.
Referenced by writeUnitTestHeader().
failed_
size_t dodo::common::UnitTest::failed_ private
The total number of failed tests.
Definition at line 96 of file unittest.hpp.
Referenced by run(), writeSubTestResult(), and writeUnitTestSummary().
name_
string dodo::common::UnitTest::name_ private
The test name.
Definition at line 84 of file unittest.hpp.
Referenced by writeUnitTestHeader().
out_
ostream* dodo::common::UnitTest::out_ private
The output destination.
Definition at line 90 of file unittest.hpp.
Referenced by writeSubTestResult(), writeUnitTestHeader(), and writeUnitTestSummary().
total_
size_t dodo::common::UnitTest::total_ private
The total number of tests.
Definition at line 93 of file unittest.hpp.
Referenced by writeSubTestResult(), and writeUnitTestSummary().
The documentation for this class was generated from the following files:
src/include/common/unittest.hpp
src/lib/common/unittest.cpp