dodo: dodo::common::Bytes Class Reference
dodo::common::Bytes Class Reference
An array of Octets with size elements.
#include <bytes.hpp>
Public Types
enum MatchType { MatchType::Mismatch, MatchType::Contained, MatchType::Contains, MatchType::Full }
The way in which two Bytes instances match.
Public Member Functions
Bytes ()
Construct an empty Bytes.
Bytes (const std::string &s)
Construct and fill from a std::string, not including the NULL terminator (so size will be string.length()).
Bytes (Octet *data, size_t size)
Construct an Bytes by taking ownership of existing data (which will be freed when this object is destructed).
virtual ~Bytes ()
Destruct and clean.
void append (const Bytes &src)
Append another Bytes.
void append (const Bytes &src, size_t n)
Append the first n Octets from Bytes.
void append (const Octet *src, size_t n)
Append from arbitrary memory areas.
void append (Octet src)
Append a single Octet.
std::string asString () const
Convert to a std::string.
Bytes & decodeBase64 (const std::string &src)
Decodes the base64 string into this Bytes.
std::string encodeBase64 () const
Encodes the this Bytes into a base64-encoded string.
void free ()
Free and clear data.
Octet * getArray () const
Return the array.
Octet getOctet (size_t index) const
Return the Octet at index.
size_t getSize () const
Return the array size.
std::string hexDump (size_t n) const
hex dump the first n octets of the data.
MatchType match (const Bytes &other, size_t index, size_t &octets)
Match this Bytes from index to the other array (entirely).
Bytes & operator= (const std::string &s)
Assign from std::string, not including a NULL terminator (so size will be string.length()).
void random (size_t octets)
Generate a random set of Octets.
void reserve (size_t size)
Reserve memory in the Bytes.
Data Fields
const size_t alloc_block = 32
Always allocate chunks of this size.
Private Attributes
size_t allocated_size
The allocated size, always >= size.
Octet * array_
The Octet array.
size_t size_
The array size in Octets (using an int as that is what OpenSSL uses)
Detailed Description
An array of Octets with size elements.
Provides base64 conversion, random data generation, appending of data from various other sources. Memory management is implicit, resizing allocates at least a chunk.
Note that Bytes objects are not thread safe, and that in general the pointer returned by getArray() may be invalidated by subjequent calls to append(), which could possibly realloc memory, invalidating the previously returned pointer.
Definition at line 44 of file bytes.hpp.
Member Enumeration Documentation
MatchType
enum dodo::common::Bytes::MatchType strong
The way in which two Bytes instances match.
Enumerator
Mismatch
The local array does not match the other array.
Contained
The local array is contained in the other array, but the other array has more data.
Contains
The local array contains the other array, but the local array has more data.
Full
The local and other array are equal in content and size.
Definition at line 118 of file bytes.hpp.
Constructor & Destructor Documentation
Bytes() [1/3]
dodo::common::Bytes::Bytes () inline
Construct an empty Bytes.
Definition at line 51 of file bytes.hpp.
Bytes() [2/3]
dodo::common::Bytes::Bytes (Octet * data, size_t size) inline
Construct an Bytes by taking ownership of existing data (which will be freed when this object is destructed).
Parameters
data The data.
size The size of the data.
Definition at line 58 of file bytes.hpp.
References array_.
Bytes() [3/3]
dodo::common::Bytes::Bytes (const std::string & s) inline
Construct and fill from a std::string, not including the NULL terminator (so size will be string.length()).
Parameters
s The source string.
Definition at line 67 of file bytes.hpp.
~Bytes()
virtual dodo::common::Bytes::~Bytes () inline virtual
Destruct and clean.
Definition at line 74 of file bytes.hpp.
References free().
Member Function Documentation
append() [1/4]
void dodo::common::Bytes::append (const Bytes & src)
Append another Bytes.
Parameters
src The Bytes to append.
Definition at line 65 of file bytes.cpp.
References array_, reserve(), and size_.
Referenced by dodo::common::DataCrypt::decrypt(), dodo::network::protocol::stomp::Connect::generate(), dodo::persist::sqlite::Query::getBytes(), dodo::network::protocol::http::HTTPRequest::parseBody(), dodo::network::protocol::http::HTTPResponse::parseBody(), and dodo::network::protocol::http::HTTPMessage::parseChunkedBody().
append() [2/4]
void dodo::common::Bytes::append (const Bytes & src, size_t n)
Append the first n Octets from Bytes.
Parameters
src The Bytes to append from.
n The number of octets to append.
Definition at line 71 of file bytes.cpp.
References array_, reserve(), size_, and throw_Exception.
append() [3/4]
void dodo::common::Bytes::append (const Octet * src, size_t n)
Append from arbitrary memory areas.
Parameters
src The memory to append from.
n The number of octets to append.
Definition at line 78 of file bytes.cpp.
References array_, reserve(), and size_.
append() [4/4]
void dodo::common::Bytes::append (Octet src)
Append a single Octet.
Parameters
src The Octet to append.
Definition at line 84 of file bytes.cpp.
References array_, reserve(), and size_.
asString()
std::string dodo::common::Bytes::asString () const
Convert to a std::string.
If the Octects contain an intermediate zero, an common::Exception is thrown, unless the zero is the last Octet. So use this only when you are sure the Bytes data is also a string.
Returns
the Byte data as a std::string.
Definition at line 98 of file bytes.cpp.
References array_, size_, and throw_Exception.
Referenced by dodo::network::protocol::http::HTTPRequest::asString(), dodo::network::protocol::http::HTTPResponse::asString(), and dodo::network::TLSContext::TLSContext().
decodeBase64()
Bytes & dodo::common::Bytes::decodeBase64 (const std::string & src)
Decodes the base64 string into this Bytes.
Parameters
src The base64-encoded source string.
Returns
A reference to this Bytes
Definition at line 115 of file bytes.cpp.
References array_, reserve(), and throw_Exception.
Referenced by dodo::common::DataCrypt::decrypt().
encodeBase64()
std::string dodo::common::Bytes::encodeBase64 () const
Encodes the this Bytes into a base64-encoded string.
Returns
The base64 encoded data of the Bytes.
Definition at line 137 of file bytes.cpp.
References array_, size_, and throw_Exception.
Referenced by dodo::common::DataCrypt::encrypt().
free()
void dodo::common::Bytes::free ()
Free and clear data.
Definition at line 56 of file bytes.cpp.
References allocated_size, array_, and size_.
Referenced by dodo::network::protocol::stomp::Connect::generate(), dodo::persist::sqlite::Query::getBytes(), and ~Bytes().
getArray()
Octet* dodo::common::Bytes::getArray () const inline
Return the array.
Note that this pointer may be invalidated by subsequent calls to append (which implictly calls reserve, which may ralloc the memory block). Avoid using this method.
Returns
a pointer to the array of Octets.
Definition at line 186 of file bytes.hpp.
References array_.
Referenced by dodo::persist::sqlite::DML::bind(), dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), dodo::network::TCPConnectionData::readBuffer(), dodo::network::protocol::http::HTTPRequest::send(), and dodo::network::protocol::http::HTTPResponse::send().
getOctet()
Octet dodo::common::Bytes::getOctet (size_t index) const inline
Return the Octet at index.
Only in debug builds the index is asserted to be within range.
Parameters
index The index of the Octet
Returns
The Octet.
Definition at line 199 of file bytes.hpp.
References array_, and size_.
Referenced by dodo::network::protocol::stomp::Frame::readCommand().
getSize()
size_t dodo::common::Bytes::getSize () const inline
Return the array size.
Returns
the array size.
Definition at line 192 of file bytes.hpp.
References size_.
Referenced by dodo::network::protocol::http::HTTPRequest::asString(), dodo::network::protocol::http::HTTPResponse::asString(), dodo::persist::sqlite::DML::bind(), dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), dodo::network::TCPConnectionData::readBuffer(), dodo::network::protocol::stomp::Frame::readCommand(), dodo::network::protocol::http::HTTPRequest::send(), dodo::network::protocol::http::HTTPResponse::send(), and dodo::network::protocol::http::HTTPMessage::setBody().
hexDump()
std::string dodo::common::Bytes::hexDump (size_t n) const
hex dump the first n octets of the data.
Parameters
n The number of octets to dump.
Returns
a string with hex numbers.
Definition at line 184 of file bytes.cpp.
References array_, and size_.
Referenced by dodo::network::TCPConnectionData::readBuffer().
match()
Bytes::MatchType dodo::common::Bytes::match (const Bytes & other, size_t index, size_t & octets)
Match this Bytes from index to the other array (entirely).
Parameters
other The other Bytes.
index The start index into the local array to match from.
octets The number of Octets, from the start of the arrays, that match.
Returns
The MatchType.
Definition at line 163 of file bytes.cpp.
References array_, Contained, Contains, Full, Mismatch, and size_.
operator=()
Bytes & dodo::common::Bytes::operator= (const std::string & s)
Assign from std::string, not including a NULL terminator (so size will be string.length()).
Parameters
s The base64 string to assign from.
Returns
This Bytes.
Definition at line 89 of file bytes.cpp.
References array_, and reserve().
random()
void dodo::common::Bytes::random (size_t octets)
Generate a random set of Octets.
Parameters
octets The number of random Octets.
Definition at line 107 of file bytes.cpp.
References array_, reserve(), and size_.
Referenced by dodo::common::DataCrypt::encrypt().
reserve()
void dodo::common::Bytes::reserve (size_t size)
Reserve memory in the Bytes.
Parameters
size The size in bytes to allocate .
Definition at line 33 of file bytes.cpp.
References alloc_block, allocated_size, array_, size_, and throw_SystemException.
Referenced by append(), decodeBase64(), dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), operator=(), random(), and dodo::network::TCPConnectionData::readBuffer().
Field Documentation
alloc_block
const size_t dodo::common::Bytes::alloc_block = 32
Always allocate chunks of this size.
Any Bytes that has been called with reserve(n > 1) will at least allocate 1 chunk of alloc_block bytes. Avoids frequent calls to realloc when using many append calls with small amount of data such as append(Octet).
Definition at line 178 of file bytes.hpp.
Referenced by reserve().
allocated_size
size_t dodo::common::Bytes::allocated_size private
The allocated size, always >= size.
Definition at line 215 of file bytes.hpp.
Referenced by free(), and reserve().
array_
Octet* dodo::common::Bytes::array_ private
The Octet array.
Definition at line 205 of file bytes.hpp.
Referenced by append(), asString(), Bytes(), decodeBase64(), encodeBase64(), free(), getArray(), getOctet(), hexDump(), match(), operator=(), random(), and reserve().
size_
size_t dodo::common::Bytes::size_ private
The array size in Octets (using an int as that is what OpenSSL uses)
Definition at line 210 of file bytes.hpp.
Referenced by append(), asString(), encodeBase64(), free(), getOctet(), getSize(), hexDump(), match(), random(), and reserve().
The documentation for this class was generated from the following files:
src/include/common/bytes.hpp
src/lib/common/bytes.cpp