dodo: dodo::persist::sqlite::DML Class Reference
dodo::persist::sqlite::DML Class Reference
Data Modification Language statements can take bind values.
#include <sqlite.hpp>
Public Member Functions
DML (const Database &db)
Constructor.
virtual ~DML ()
Destructor.
void bind (const std::string &name, const common::Bytes &value)
Bind a string value to the bind by name.
void bind (const std::string &name, const std::string &value)
Bind a string value to the bind by name.
void bind (const std::string &name, double value)
Bind a string value to the bind by name.
void bind (const std::string &name, int value)
Bind a string value to the bind by name.
void bind (const std::string &name, int64_t value)
Bind a string value to the bind by name.
void bind (int position, const common::Bytes &value)
Bind an Bytes value to the bind at position.
void bind (int position, const std::string &value)
Bind a string value to the bind at position.
void bind (int position, double value)
Bind a double value to the bind at position.
void bind (int position, int value)
Bind an int value to the bind at position.
void bind (int position, int64_t value)
Bind a int64_t value to the bind at position.
int execute ()
Execute and return the number of rows affected.
Public Member Functions inherited from dodo::persist::sqlite::Statement
Statement (const Database &db)
Constructor.
virtual ~Statement ()
Destructor.
void close ()
A statement handle can be explicitly closed without deleting the Statement object itself.
void prepare (const std::string &sql)
Prepare a SQL statement.
void reset (bool clear=true)
Reset a SQL statement for re-execute or even re-prepare.
Additional Inherited Members
Protected Attributes inherited from dodo::persist::sqlite::Statement
sqlite3 * database_
database handle on which the stmt_ is created.
sqlite3_stmt * stmt_
statement handle.
Detailed Description
Data Modification Language statements can take bind values.
Note that calling reset leaves set bind values intact.
Definition at line 294 of file sqlite.hpp.
Constructor & Destructor Documentation
DML()
dodo::persist::sqlite::DML::DML (const Database & db)
Constructor.
Parameters
db Yhe database context.
Definition at line 376 of file sqlite.cpp.
~DML()
virtual dodo::persist::sqlite::DML::~DML () inline virtual
Destructor.
Definition at line 304 of file sqlite.hpp.
Member Function Documentation
bind() [1/10]
void dodo::persist::sqlite::DML::bind (const std::string & name, const common::Bytes & value)
Bind a string value to the bind by name.
Note that this is less efficient than binding by index/position.
Parameters
name The name of the bind parameter.
value the value to bind.
Definition at line 446 of file sqlite.cpp.
References bind(), dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [2/10]
void dodo::persist::sqlite::DML::bind (const std::string & name, const std::string & value)
Bind a string value to the bind by name.
Note that this is less efficient than binding by index/position.
Parameters
name The name of the bind parameter.
value the value to bind.
Definition at line 440 of file sqlite.cpp.
References bind(), dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [3/10]
void dodo::persist::sqlite::DML::bind (const std::string & name, double value)
Bind a string value to the bind by name.
Note that this is less efficient than binding by index/position.
Parameters
name The name of the bind parameter.
value the value to bind.
Definition at line 422 of file sqlite.cpp.
References bind(), dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [4/10]
void dodo::persist::sqlite::DML::bind (const std::string & name, int value)
Bind a string value to the bind by name.
Note that this is less efficient than binding by index/position.
Parameters
name The name of the bind parameter.
value the value to bind.
Definition at line 428 of file sqlite.cpp.
References bind(), dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [5/10]
void dodo::persist::sqlite::DML::bind (const std::string & name, int64_t value)
Bind a string value to the bind by name.
Note that this is less efficient than binding by index/position.
Parameters
name The name of the bind parameter.
value the value to bind.
Definition at line 434 of file sqlite.cpp.
References bind(), dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [6/10]
void dodo::persist::sqlite::DML::bind (int position, const common::Bytes & value)
Bind an Bytes value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 415 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::database_, dodo::common::Bytes::getArray(), dodo::common::Bytes::getSize(), dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [7/10]
void dodo::persist::sqlite::DML::bind (int position, const std::string & value)
Bind a string value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 408 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::database_, dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [8/10]
void dodo::persist::sqlite::DML::bind (int position, double value)
Bind a double value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 387 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::database_, dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
Referenced by bind(), dodo::persist::KVStore::deleteKey(), dodo::persist::KVStore::exists(), dodo::persist::KVStore::filterKeys(), dodo::persist::KVStore::getMetaData(), dodo::persist::KVStore::getValue(), dodo::persist::KVStore::insertKey(), and dodo::persist::KVStore::setKey().
bind() [9/10]
void dodo::persist::sqlite::DML::bind (int position, int value)
Bind an int value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
Definition at line 394 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::database_, dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
bind() [10/10]
void dodo::persist::sqlite::DML::bind (int position, int64_t value)
Bind a int64_t value to the bind at position.
Parameters
position the bind position in the SQL (start with 1)
value the value to bind.
execute()
int dodo::persist::sqlite::DML::execute ()
Execute and return the number of rows affected.
Returns
The number of rows affected by the DML statement.
Definition at line 379 of file sqlite.cpp.
References dodo::persist::sqlite::Statement::database_, dodo::persist::sqlite::Statement::stmt_, and throw_Exception.
Referenced by dodo::persist::KVStore::deleteKey(), dodo::persist::KVStore::insertKey(), and dodo::persist::KVStore::setKey().
The documentation for this class was generated from the following files:
src/include/persist/sqlite/sqlite.hpp
src/lib/persist/sqlite/sqlite.cpp