dodo: dodo::store::kvstore::FileHeader Class Reference
dodo::store::kvstore::FileHeader Class Reference
The first block in the file.
#include <header.hpp>
Data Structures
struct BlockDef
The block definition.
Public Member Functions
FileHeader (void *address)
Construct against an existing address.
BlockDef & getBlock ()
Provide access to the block.
void getInfo (std::string &name, std::string &description, std::string &contact)
Get the name, description and contact information.
void setInfo (const std::string &name, const std::string &description, const std::string &contact)
Set the name, description and contact information.
Protected Attributes
BlockDef * block_
The interpreted block.
Detailed Description
The first block in the file.
Definition at line 35 of file header.hpp.
Constructor & Destructor Documentation
FileHeader()
dodo::store::kvstore::FileHeader::FileHeader (void * address) inline
Construct against an existing address.
Parameters
address The address to interpret as a FileHeader.
Definition at line 67 of file header.hpp.
References block_.
Member Function Documentation
getBlock()
BlockDef& dodo::store::kvstore::FileHeader::getBlock () inline
Provide access to the block.
Returns
A reference to the FileHeader::BlockDef
Definition at line 73 of file header.hpp.
References block_.
Referenced by dodo::store::kvstore::KVStore::analyze(), and dodo::store::kvstore::KVStore::init().
getInfo()
void dodo::store::kvstore::FileHeader::getInfo (std::string & name, std::string & description, std::string & contact)
Get the name, description and contact information.
Parameters
name The name of the store.
description Brief description of the contents and purpose of the store.
contact The contact for issues with the store.
Definition at line 50 of file header.cpp.
References block_, dodo::store::kvstore::FileHeader::BlockDef::contact_sz, dodo::store::kvstore::FileHeader::BlockDef::description_sz, and dodo::store::kvstore::FileHeader::BlockDef::name_sz.
Referenced by dodo::store::kvstore::KVStore::analyze().
setInfo()
void dodo::store::kvstore::FileHeader::setInfo (const std::string & name, const std::string & description, const std::string & contact)
Set the name, description and contact information.
Parameters
name The name of the store.
description Brief description of the contents and purpose of the store.
contact The contact for issues with the store.
Definition at line 29 of file header.cpp.
References block_, dodo::store::kvstore::FileHeader::BlockDef::contact_sz, dodo::store::kvstore::FileHeader::BlockDef::description_sz, and dodo::store::kvstore::FileHeader::BlockDef::name_sz.
Referenced by dodo::store::kvstore::KVStore::init().
Field Documentation
block_
BlockDef* dodo::store::kvstore::FileHeader::block_ protected
The interpreted block.
Definition at line 101 of file header.hpp.
Referenced by FileHeader(), getBlock(), getInfo(), and setInfo().
The documentation for this class was generated from the following files:
src/include/store/kvstore/blockdefs/header.hpp
src/lib/store/kvstore/blockdefs/header.cpp