dodo: dodo::network::Socket Class Reference
dodo::network::Socket Class Reference
A Linux socket.
#include <socket.hpp>
Public Member Functions
Socket ()
Default constructor creates an invalid socket.
Socket (bool blocking)
Construct with default SocketParams.
Socket (bool blocking, SocketParams params)
Construct from SocketParams.
Socket (const Socket &socket)
Construct a copy of another Socket.
Socket (int socket)
Construct from a socket descriptor.
virtual ~Socket ()
Destructs this Socket, but does not call close().
virtual Socket * accept ()
Accepts a connection request and return a pointer to a new Socket for the new connection, the caller will own the new Socket object.
virtual SystemError receive (void *buf, ssize_t request, ssize_t &received)
Receive bytes.
virtual SystemError send (const void *buf, ssize_t len, bool more=false)
Send len bytes as a bytestream.
virtual SystemError sendTo (const Address &address, const void *buf, ssize_t len)
Send raw packets to the given Address.
Public Member Functions inherited from dodo::network::BaseSocket
BaseSocket ()
Default constructor creates an invalid socket.
BaseSocket (bool blocking, SocketParams params)
Construct from SocketParams.
BaseSocket (int socket)
Construct from a socket descriptor.
virtual ~BaseSocket ()
Destructs this Socket, but does not call close().
SystemError bind (const Address &address)
Bind the socket to the Address.
virtual void close ()
Closes the socket, causing the connection, if it exists, to be terminated.
virtual SystemError connect (const Address &address)
Connect to the address.
virtual std::string debugDetail () const
Return debug object state as a string.
Address getAddress () const
Get the local address for this socket.
SocketParams::AddressFamily getAddressFamily () const
Get the SocketParams::AddressFamily of the socket.
virtual bool getBlocking () const
Rerurn true if the socket is operating in blocking mode.
int getFD () const
Return the socket file descriptor.
Address getPeerAddress () const
Get the peer (remote) address for this socket.
SocketParams::ProtocolNumber getProtocolNumber () const
Get the SocketParams::ProtocolNumber of the socket.
virtual socklen_t getReceiveBufSize () const
Get the maximum buffer length for receive.
socklen_t getSendBufSize () const
Get the maximum buffer length for send.
SocketParams getSocketParams () const
Return the SocketParams.
SocketParams::SocketType getSocketType () const
Get the SocketParams::SocketType of the socket.
int getTTL () const
Get the Socket TTL (time to live) or the max number of packet hops.
bool isValid () const
Return true when the socket descriptor is a valid, hence 'possible' descriptor.
SystemError listen (const Address &address, int backlog)
Sets up a listening socket on Address.
bool operator< (const BaseSocket &socket) const
Add ordering.
BaseSocket & operator= (const BaseSocket &socket)
Assign from Socket.
BaseSocket & operator= (int socket)
Assign from existing socket descriptor (int).
bool operator== (const BaseSocket &socket) const
Add identity.
SystemError receiveInt16 (int16_t &value)
receive an int16_t
SystemError receiveInt32 (int32_t &value)
receive an int32_t
SystemError receiveInt64 (int64_t &value)
receive an int64_t
SystemError receiveInt8 (int8_t &value)
receive an int8_t
SystemError receiveLine (string &s)
receive a stream of characters until a '
' is read (consumed from the socket read buffer but not added to s).
SystemError receiveString (string &s)
Receive a std::string as sent by sendString(const std::string&).
SystemError receiveUInt16 (uint16_t &value)
receive an uint16_t
SystemError receiveUInt32 (uint32_t &value)
receive an uint32_t
SystemError receiveUInt64 (uint64_t &value)
receive an uint64_t
SystemError receiveUInt8 (uint8_t &value)
receive an uint8_t
SystemError sendInt16 (int16_t value, bool more=false)
Send an int16_t.
SystemError sendInt32 (int32_t value, bool more=false)
Send an int32_t.
SystemError sendInt64 (int64_t value, bool more=false)
Send an int64_t.
SystemError sendInt8 (int8_t value, bool more=false)
Send an int8_t.
SystemError sendLine (const std::string &s, bool more)
Sends the std::string terminated by a '
'.
SystemError sendString (const std::string &s, bool more=false)
Sends the std::string as understood by receiveString().
SystemError sendUInt16 (uint16_t value, bool more=false)
Send an uint16_t.
SystemError sendUInt32 (uint32_t value, bool more=false)
Send an uint32_t.
SystemError sendUInt64 (uint64_t value, bool more=false)
Send an sendUInt64.
SystemError sendUInt8 (uint8_t value, bool more=false)
Send an uint8_t.
void setBlocking (bool blocking)
Set the Socket blocking mode.
void setReceiveBufSize (socklen_t size)
Set the size of the receive buffer.
void setReceiveTimeout (double sec)
Set the receive timeout - a receive will fail if there is no data received before the timeout expires.
void setReUseAddress ()
Enable the socket to re-use an address when listen/bind is called.
void setReUsePort ()
Make the socket re-use a port when listen is called.
void setSendBufSize (socklen_t size)
Set the size of the send buffer.
void setSendTimeout (double sec)
Set the send timeout - a send will fail if there is no data send before the timeout expires.
void setTCPKeepAlive (bool enable)
Enable or disable TCP keep-alive on the socket.
void setTCPNoDelay (bool set)
Set TCP_NODELAY.
void setTTL (int ttl)
Set the Socket TTL (Time to Live).
Public Member Functions inherited from dodo::common::DebugObject
DebugObject ()
Default constructor does nothing.
virtual ~DebugObject ()
Destructor does nothing.
std::string debugString () const
Return the object dump to string.
Static Public Attributes
static Socket SocketInvalid = Socket()
An invalid SocketInvalid for comparison convenience - initialized to a Socket with socket fd=-1.
Additional Inherited Members
Protected Member Functions inherited from dodo::common::DebugObject
std::string debugHeader () const
Generates a debug header (address of this object and a demangled class name.
Protected Attributes inherited from dodo::network::BaseSocket
int socket_
The socket file decsriptor.
Detailed Description
A Linux socket.
Socket objects refer to, but do not own a particular socket descriptor. The programmer controls closing the socket by calling close(), the Socket destructor does not do this implicitly, as two Socket objects may refer to the same socket descriptor.
The Socket operates either in blocking or non-blocking mode. In blocking mode, calls to listen() or receive() will block until data is received. Moreover, in blocking mode, there is no limit to the amount of data that can be sent or received in one go. In non-blocking mode, the send and receive sizes per call must fit in Socket::getSendBufSize() or Socket::getReceiveBufSize().
Definition at line 52 of file socket.hpp.
Constructor & Destructor Documentation
Socket() [1/5]
dodo::network::Socket::Socket () inline
Default constructor creates an invalid socket.
Definition at line 59 of file socket.hpp.
Referenced by accept().
Socket() [2/5]
dodo::network::Socket::Socket (int socket) inline
Construct from a socket descriptor.
Parameters
socket The socket file descriptor.
Definition at line 65 of file socket.hpp.
Socket() [3/5]
dodo::network::Socket::Socket (bool blocking, SocketParams params) inline
Construct from SocketParams.
Parameters
blocking If true, create the socket in blocking mode.
params The SocketParams to use.
Definition at line 72 of file socket.hpp.
Socket() [4/5]
dodo::network::Socket::Socket (bool blocking) inline
Construct with default SocketParams.
Parameters
blocking If true, create the socket in blocking mode.
Definition at line 78 of file socket.hpp.
Socket() [5/5]
dodo::network::Socket::Socket (const Socket & socket)
Construct a copy of another Socket.
Parameters
socket The other socket.
Definition at line 100 of file socket.cpp.
References dodo::network::BaseSocket::getFD(), and dodo::network::BaseSocket::socket_.
~Socket()
virtual dodo::network::Socket::~Socket () inline virtual
Destructs this Socket, but does not call close().
Definition at line 89 of file socket.hpp.
Member Function Documentation
accept()
Socket * dodo::network::Socket::accept () virtual
Accepts a connection request and return a pointer to a new Socket for the new connection, the caller will own the new Socket object.
Returns
The accepted socket.
Implements dodo::network::BaseSocket.
Definition at line 104 of file socket.cpp.
References Socket(), dodo::network::BaseSocket::socket_, SocketInvalid, and throw_SystemExceptionObject.
receive()
SystemError dodo::network::Socket::receive (void * buf, ssize_t request, ssize_t & received) virtual
Receive bytes.
Parameters
buf The buffer to receive the data into.
request The number of bytes to receive (request <= sizeof(buf)).
received The number of bytes actuially received
Returns
The error code:
SystemError::ecOK
SystemError::ecEAGAIN
SystemError::ecENOTCONN
SystemError::ecECONNREFUSED On other errors returned by the internal call to recv, an exception is thrown.
Implements dodo::network::BaseSocket.
Definition at line 83 of file socket.cpp.
References dodo::common::SystemError::ecEAGAIN, dodo::common::SystemError::ecECONNREFUSED, dodo::common::SystemError::ecENOTCONN, dodo::common::SystemError::ecOK, dodo::network::BaseSocket::socket_, and throw_SystemExceptionObject.
send()
SystemError dodo::network::Socket::send (const void * buf, ssize_t len, bool more = false) virtual
Send len bytes as a bytestream.
connect must have been called first.
Parameters
buf The bytes to send.
len The number of bytes to send from buf.
more If true, do no forec a network send right away, but wait until send buffer full or a subsequent call with more set to false.
Returns
SystemError::ecOK or
SystemError::ecEAGAIN: For non-blocking sockets, neither failure nor succces, try again.
SystemError::ecECONNRESET : The peer has disconnected during the send.
See also
sendTo()
Implements dodo::network::BaseSocket.
Definition at line 38 of file socket.cpp.
References dodo::common::SystemError::ecEAGAIN, dodo::common::SystemError::ecECONNRESET, dodo::common::SystemError::ecOK, dodo::network::BaseSocket::socket_, and throw_SystemExceptionObject.
sendTo()
SystemError dodo::network::Socket::sendTo (const Address & address, const void * buf, ssize_t len) virtual
Send raw packets to the given Address.
Parameters
address The destination Address
buf The bytes to send
len The number of bytes to send.
Returns
The SystemError.
Definition at line 61 of file socket.cpp.
References dodo::network::Address::addr_, dodo::common::SystemError::ecEAGAIN, dodo::common::SystemError::ecECONNRESET, dodo::common::SystemError::ecOK, dodo::network::BaseSocket::socket_, and throw_SystemExceptionObject.
Field Documentation
SocketInvalid
Socket dodo::network::Socket::SocketInvalid = Socket() static
An invalid SocketInvalid for comparison convenience - initialized to a Socket with socket fd=-1.
Definition at line 137 of file socket.hpp.
Referenced by accept().
The documentation for this class was generated from the following files:
src/include/network/socket.hpp
src/lib/network/socket.cpp