dodo: dodo::network::Address Class Reference
dodo::network::Address Class Reference
Generic network Address, supporting ipv4 and ipv6 transparently.
#include <address.hpp>
Public Member Functions
Address ()
Construct an invalid (unspecified) address.
Address (const Address &address)
Copy from Address.
Address (const sockaddr *address, socklen_t len)
Construct from sockaddr *.
Address (const sockaddr_storage &address)
Construct from sockaddr_storage.
Address (const string &ip)
Construct from ip, do not set port (only a listening socket needs a port preset).
Address (const string &ip, uint16_t port)
Construct from "ip", port.
string asString (bool withport=false) const
Return a string representation of this Address.
const sockaddr_storage * getAddress () const
Get to the underlying sockaddr_storage.
SocketParams::AddressFamily getAddressFamily () const
Get this Address family.
SystemError getNameInfo (std::string &hostname) const
Do a reverse DNS lookup on this Address and return in hostname.
SystemError getNameInfo (std::string &hostname, std::string &service) const
Do a reverse DNS lookup on this Address and its port, and return in hostname and service.
SystemError getNameInfo (std::string &hostname, uint16_t &port) const
Do a reverse DNS lookup on this Address and its port, and return in hostname and port.
uint16_t getPort () const
Return the port number.
bool isValid () const
True if this Address is valid.
Address & operator= (const Address &address)
Assign (copy) from Address.
Address & operator= (const sockaddr_storage &address)
Assign from sockaddr_storage.
Address & operator= (const string &address)
Assign from "ip" string.
bool operator== (const Address &address) const
Test for equality.
void setPort (uint16_t port)
Set the port number.
Public Member Functions inherited from dodo::common::DebugObject
DebugObject ()
Default constructor does nothing.
virtual ~DebugObject ()
Destructor does nothing.
std::string debugString () const
Return the object dump to string.
Static Public Member Functions
static SystemError getHostAddrInfo (const std::string &hostname, AddrInfo &info)
Get Address information on a host in a AddrInfo struct.
static SystemError getHostAddrInfo (const std::string &hostname, SocketParams &params, Address &address, std::string &canonicalname)
Return the first hit on SocketParams in address and canonicalname.
Private Member Functions
struct sockaddr_in * asIPv4Address () const
Explicit cast of addr_ as sockaddr_in*.
struct sockaddr_in6 * asIPv6Address () const
Explicit cast of addr_ as sockaddr_in6*.
void init ()
Initialize the internals.
Private Attributes
struct sockaddr_storage addr_
The address storage (for either ipv4 or ipv6).
Friends
class BaseSocket
BaseSocket may access this class directly.
class Socket
Socket may access this class directly.
Additional Inherited Members
Protected Member Functions inherited from dodo::common::DebugObject
virtual std::string debugDetail () const
Descendent classes can override to dump details speciufic to the class.
std::string debugHeader () const
Generates a debug header (address of this object and a demangled class name.
Detailed Description
Generic network Address, supporting ipv4 and ipv6 transparently.
Typical client use is to first resolve a host name. We specify SocketParams::afUNSPEC for the address family, allowing for both ipv4 and ipv6 and specify the TCP protocol (stSTRAM + pnTCP).
using namespace dodo::common;
using namespace dodo::network;
Address address;
SocketParams sock_params = SocketParams(SocketParams::afUNSPEC,
                                         SocketParams::stSTREAM,
                                         SocketParams::pnTCP );
std::string canonicalname;
SystemError error = Address::getHostAddrInfo("httpbin.org", sock_params, address, canonicalname);
The canonical name is set and may differ from the host name passed to getHostAddrInfo.
After the getHostAddrInfo (if error == SystemError::ecOK) the sock_params will have its address family set to either network::SocketParams::afINET or network::SocketParams::afINET6, depending on what the server (httpbin.org) supports. But we can continue to connect without any reference to the actual address family being used:
if (error == SystemError::ecOK) {
  address.setPort( 443 );
  Socket socket( true, sock_params );
  error = socket.connect( address );
  if ( error == SystemError::ecOK ) {
    // connected
  }
}
There are two prototypes for getHostAddrInfo, one returns the preferred Address (as above), the other a list of addresses (an AddrInfo structure), the preferred address the first in the list. Subsequent calls do not necessarily (under DNS round robin for example) return the same address as preferred address.
As the getHostAddrInfo calls are quite expensive, prefer reuse of obtained Address objects where possible.
Special addresses ipv4 ipv6
INADDR_ANY 0.0.0.0 ::0
localhost 127.0.0.1 ::1
Definition at line 92 of file address.hpp.
Constructor & Destructor Documentation
Address() [1/6]
dodo::network::Address::Address () inline
Construct an invalid (unspecified) address.
Definition at line 98 of file address.hpp.
Referenced by getHostAddrInfo().
Address() [2/6]
dodo::network::Address::Address (const string & ip, uint16_t port)
Construct from "ip", port.
Parameters
ip The string representation of the ip, either ipv4 or ipv6.
port The port number (only specified for listen addresses).
Definition at line 43 of file address.cpp.
References init(), and setPort().
Address() [3/6]
dodo::network::Address::Address (const string & ip)
Construct from ip, do not set port (only a listening socket needs a port preset).
Parameters
ip The string representation of the ip, either ipv4 or ipv6.
Definition at line 38 of file address.cpp.
References init().
Address() [4/6]
dodo::network::Address::Address (const sockaddr_storage & address)
Construct from sockaddr_storage.
Parameters
address A sockaddr_storage structure.
Definition at line 49 of file address.cpp.
References addr_.
Address() [5/6]
dodo::network::Address::Address (const sockaddr * address, socklen_t len)
Construct from sockaddr *.
Parameters
address A const sockaddr*
len And its length.
Definition at line 54 of file address.cpp.
References addr_.
Address() [6/6]
dodo::network::Address::Address (const Address & address)
Copy from Address.
Parameters
address Source address to copy from.
Definition at line 59 of file address.cpp.
References addr_.
Member Function Documentation
asIPv4Address()
struct sockaddr_in* dodo::network::Address::asIPv4Address () const inline private
Explicit cast of addr_ as sockaddr_in*.
Returns
The pointer.
Definition at line 280 of file address.hpp.
Referenced by asString(), getPort(), operator=(), operator==(), and setPort().
asIPv6Address()
struct sockaddr_in6* dodo::network::Address::asIPv6Address () const inline private
Explicit cast of addr_ as sockaddr_in6*.
Returns
The pointer.
Definition at line 286 of file address.hpp.
Referenced by asString(), getPort(), operator=(), operator==(), and setPort().
asString()
string dodo::network::Address::asString (bool withport = false) const
Return a string representation of this Address.
Parameters
withport If true, append ':' + port number.
Returns
string representation of this Address.
Definition at line 110 of file address.cpp.
References addr_, asIPv4Address(), asIPv6Address(), getPort(), and throw_SystemExceptionObject.
Referenced by dodo::network::AddrInfoItem::asString(), dodo::network::BaseSocket::bind(), dodo::network::TCPListener::construct(), dodo::network::BaseSocket::listen(), dodo::network::TCPServer::run(), and dodo::network::TCPListener::run().
getAddress()
const sockaddr_storage* dodo::network::Address::getAddress () const inline
Get to the underlying sockaddr_storage.
Returns
A pointer to the underlying socket storage.
Definition at line 167 of file address.hpp.
Referenced by dodo::network::BaseSocket::connect().
getAddressFamily()
SocketParams::AddressFamily dodo::network::Address::getAddressFamily () const inline
Get this Address family.
Returns
The address family of this Address.
Definition at line 161 of file address.hpp.
Referenced by dodo::network::TCPListener::construct(), and getHostAddrInfo().
getHostAddrInfo() [1/2]
SystemError dodo::network::Address::getHostAddrInfo (const std::string & hostname, AddrInfo & info) static
Get Address information on a host in a AddrInfo struct.
Could return the following SystemError
SystemError::ecOK
SystemError::ecEAI_ADDRFAMILY (The hosts exists but has not address in the requested address family)
SystemError::ecEAI_NODATA (The hosts exists in DNS but has no addresses)
SystemError::ecEAI_NONAME (The hosts does not exist in DNS)
Parameters
hostname The host name to lookup.
info The AddrInfo structure to fill.
Returns
SystemError::ecOK if the lookup resulted in at least one address.
Definition at line 147 of file address.cpp.
References Address(), dodo::network::AddrInfoItem::address, dodo::network::AddrInfo::canonicalname, dodo::common::SystemError::ecEAI_ADDRFAMILY, dodo::common::SystemError::ecEAI_NODATA, dodo::common::SystemError::ecEAI_NONAME, dodo::common::SystemError::ecOK, dodo::network::AddrInfo::items, dodo::network::AddrInfoItem::params, dodo::network::SocketParams::setAddressFamily(), dodo::network::SocketParams::setProtocol(), dodo::network::SocketParams::setSocketType(), and throw_SystemException.
Referenced by getHostAddrInfo().
getHostAddrInfo() [2/2]
SystemError dodo::network::Address::getHostAddrInfo (const std::string & hostname, SocketParams & params, Address & address, std::string & canonicalname) static
Return the first hit on SocketParams in address and canonicalname.
Could return the following SystemError
SystemError::ecOK
SystemError::ecEAI_ADDRFAMILY (The hosts exists but has not address in the requested address family)
SystemError::ecEAI_NODATA (The hosts exists in DNS but has no addresses)
SystemError::ecEAI_NONAME (The hosts does not exist in DNS)
Parameters
hostname The host name to lookup.
params The SocketParams the entry must match to.
address The result address (set to invalid when this call returns an error).
canonicalname The canonicalname of hostname (set to "" when this call returns an error).
Returns
SystemError::ecOK if the lookup resulted in an address.
Definition at line 180 of file address.cpp.
References Address(), dodo::network::AddrInfo::canonicalname, dodo::common::SystemError::ecEAI_NODATA, dodo::common::SystemError::ecOK, dodo::network::SocketParams::getAddressFamily(), getAddressFamily(), getHostAddrInfo(), dodo::network::SocketParams::getProtocol(), dodo::network::SocketParams::getSocketType(), dodo::network::AddrInfo::items, and dodo::network::SocketParams::setAddressFamily().
getNameInfo() [1/3]
SystemError dodo::network::Address::getNameInfo (std::string & hostname) const
Do a reverse DNS lookup on this Address and return in hostname.
Could return the following SystemError
SystemError::ecOK
SystemError::ecEAI_AGAIN
SystemError::ecEAI_BADFLAGS
SystemError::ecEAI_FAIL
SystemError::ecEAI_FAMILY
SystemError::ecEAI_MEMORY
SystemError::ecEAI_NONAME
SystemError::ecEAI_OVERFLOW
SystemError::ecEAI_SYSTEM is silently replaced by errno
Parameters
hostname The string to receive the hostname.
Returns
The error or SystemError::ecOK on success.
Definition at line 203 of file address.cpp.
References addr_, and dodo::common::SystemError::ecEAI_SYSTEM.
getNameInfo() [2/3]
SystemError dodo::network::Address::getNameInfo (std::string & hostname, std::string & service) const
Do a reverse DNS lookup on this Address and its port, and return in hostname and service.
Parameters
hostname The string variable to receive the hostname.
service The string variable to receive the service name.
Returns
The error or SystemError::ecOK on success.
See also
getNameInfo() for a full list of possible errors returned.
Definition at line 217 of file address.cpp.
References addr_, and dodo::common::SystemError::ecEAI_SYSTEM.
getNameInfo() [3/3]
SystemError dodo::network::Address::getNameInfo (std::string & hostname, uint16_t & port) const
Do a reverse DNS lookup on this Address and its port, and return in hostname and port.
Parameters
hostname The string variable to receive the hostname.
port The uint16_t variable to receive the port number.
Returns
The error or SystemError::ecOK on success.
See also
getNameInfo() for a full list of possible errors returned.
Definition at line 232 of file address.cpp.
References addr_, dodo::common::SystemError::ecEAI_SYSTEM, and throw_SystemException.
getPort()
uint16_t dodo::network::Address::getPort () const
Return the port number.
Returns
The port number.
Definition at line 130 of file address.cpp.
References addr_, asIPv4Address(), and asIPv6Address().
Referenced by asString().
init()
void dodo::network::Address::init () private
Initialize the internals.
Definition at line 64 of file address.cpp.
References addr_.
Referenced by Address().
isValid()
bool dodo::network::Address::isValid () const inline
True if this Address is valid.
Returns
true when this Address is valid.
Definition at line 136 of file address.hpp.
Referenced by dodo::network::TCPListener::construct(), dodo::network::TCPListener::TCPListener(), and dodo::network::X509Certificate::verifyIP().
operator=() [1/3]
Address & dodo::network::Address::operator= (const Address & address)
Assign (copy) from Address.
Parameters
address The Address to assign.
Returns
This Address.
Definition at line 85 of file address.cpp.
References addr_.
operator=() [2/3]
Address & dodo::network::Address::operator= (const sockaddr_storage & address)
Assign from sockaddr_storage.
Parameters
address The address to assign in sockaddr_storage form.
Returns
This Address.
Definition at line 90 of file address.cpp.
References addr_.
operator=() [3/3]
Address & dodo::network::Address::operator= (const string & address)
Assign from "ip" string.
Parameters
address The address to assign in string form.
Returns
This Address.
Definition at line 69 of file address.cpp.
References addr_, asIPv4Address(), and asIPv6Address().
operator==()
bool dodo::network::Address::operator== (const Address & address) const
Test for equality.
The comparison is a byte compare on the internal sockaddr_in / sockaddr_in6 structures, which guarantees that Address objects assigned "::1" and "0:0:0:0:0:0:0:1" are considered equal.
Parameters
address The address to compare to.
Returns
True if the addresses are equal.
Definition at line 95 of file address.cpp.
References addr_, asIPv4Address(), and asIPv6Address().
setPort()
void dodo::network::Address::setPort (uint16_t port)
Set the port number.
Parameters
port The new port number.
Definition at line 139 of file address.cpp.
References addr_, asIPv4Address(), and asIPv6Address().
Referenced by Address().
Friends And Related Function Documentation
BaseSocket
friend class BaseSocket friend
BaseSocket may access this class directly.
Definition at line 300 of file address.hpp.
Socket
friend class Socket friend
Socket may access this class directly.
Definition at line 296 of file address.hpp.
Field Documentation
addr_
struct sockaddr_storage dodo::network::Address::addr_ private
The address storage (for either ipv4 or ipv6).
Definition at line 291 of file address.hpp.
Referenced by Address(), asString(), dodo::network::BaseSocket::bind(), getNameInfo(), getPort(), init(), operator=(), operator==(), dodo::network::Socket::sendTo(), and setPort().
The documentation for this class was generated from the following files:
src/include/network/address.hpp
src/lib/network/address.cpp