dodo: dodo::network::HTTPRequest Class Reference
dodo::network::HTTPRequest Class Reference
HTTPRequest class.
#include <httprequest.hpp>
Data Structures
class HTTPRequestLine
HTTPRequestLine class.
Public Types
enum Method {
meGET, meHEAD, mePOST, mePUT,
mePATCH, meDELETE, meCONNECT, meOPTIONS,
meTRACE, meINVALID
}
The HTTP request method.
Public Types inherited from dodo::network::HTTPFragment
enum ParseError : unsigned int {
peOk = 0, peIncomplete, peSystemError, peExpectCRLF,
peUnFinishedToken, peExpectingHeaderColon, peInvalidHeaderFieldValue, peInvalidHeaderListEnd,
peInvalidMethod, peInvalidHTTPVersion, peInvalidRequestLine, peInvalidContentLength,
peUnexpectedBody, peInvalidTransferEncoding, peInvalidChunkHex, peInvalidLastChunk,
peExpectingUnsignedInt
}
Parse results returned by the parse functions.
Public Member Functions
virtual std::string asString () const
Return the HTTPRequest as a string.
HTTPRequestLine & getRequestLine ()
Get the HTTPRequestLine.
virtual ParseResult parse (VirtualReadBuffer &data)
Read the HTTPRequest from the socket.
void setRequestLine (const HTTPRequestLine &req)
Set the HTTPRequestLine.
common::SystemError write (BaseSocket *socket) const
Write the HTTPRequest to the socket.
Public Member Functions inherited from dodo::network::HTTPMessage
HTTPMessage ()
Default constructor.
void addHeader (const std::string &key, const std::string &value)
Add a header to the HTTPMessage.
void clearHeaders ()
Clear all headers.
const std::string & getBody () const
Return the HTTTMessage body.
const std::map< std::string, std::string > & getHeaders () const
Return a reference to the headers map.
bool getHeaderValue (const std::string &key, std::string &value) const
Get a header value as a string into value.
bool getHeaderValue (const std::string &key, unsigned long &value) const
Get a header value as an unsigned long into value.
void replaceHeader (const std::string &key, const std::string &value)
Replace the value of a header.
void setBody (const std::string &body)
Set the body.
Static Public Member Functions
static bool methodAllowsBody (Method method)
Return true if the Method allows a body in the message.
static std::string methodAsString (Method method)
Translate a Method enum to a human readable string.
static Method methodFromString (const std::string &s)
Translate an uppercase string ('GET', "POST', ..) into a Method enum.
Static Public Member Functions inherited from dodo::network::HTTPFragment
static std::string getParseResultAsString (ParseError error)
Return the string description of a ParseError.
Protected Attributes
HTTPRequestLine request_line_
The HTTPRequestLine of the HTTPRequest.
Protected Attributes inherited from dodo::network::HTTPMessage
std::string body_
The message body (if any).
std::map< std::string, std::string > headers_
The message headers.
Additional Inherited Members
Static Public Attributes inherited from dodo::network::HTTPMessage
static const char charCR = char(13)
CR character.
static const char charHT = char(9)
Horizontal tab character.
static const char charLF = char(10)
LF character.
static const char charSP = char(32)
Space character.
Protected Member Functions inherited from dodo::network::HTTPMessage
ParseResult eatCRLF (VirtualReadBuffer &data)
Consume a CR LF sequence only when it is there.
ParseResult parseBody (VirtualReadBuffer &data)
Parse a body and resturn it as a single string.
ParseResult parseChunkedBody (VirtualReadBuffer &data)
Parse a chunked body (transfer-encoding: chunked) and resturn it as a single string.
ParseResult parseChunkHex (VirtualReadBuffer &data, unsigned long &value)
Parse a hexadecimal chunk size (a hex value followed by CR LF).
ParseResult parseCRLF (VirtualReadBuffer &data)
Consume a CR LF sequence.
ParseResult parseFieldValue (VirtualReadBuffer &data, std::string &value)
Parse a header field value.
ParseResult parseHeaders (VirtualReadBuffer &data)
Parse a header section and update headers_.
ParseResult parseToken (VirtualReadBuffer &buffer, std::string &token)
Parse a token (such as a header field name).
Static Protected Member Functions inherited from dodo::network::HTTPMessage
static common::SystemError eatSpace (VirtualReadBuffer &data)
Call buffer.next() as long as buffer.get() is whitespace (charSP or charHT).
static bool isCTL (char c)
Check is the char is a CTL character.
static bool isSeparator (char c)
Return true if the char is a separator.
static bool isSP (char c)
Return true if the char is whitespace character (charSP or charHT)
static ParseResult parseUInt (VirtualReadBuffer &data, unsigned int &value)
Parse an unsigned integer.
Detailed Description
HTTPRequest class.
Contains
A HTTPRequestLine
An optional body
Definition at line 40 of file httprequest.hpp.
Member Enumeration Documentation
Method
enum dodo::network::HTTPRequest::Method
The HTTP request method.
Enumerator
meINVALID
The parser was presented an invalid method.
Definition at line 46 of file httprequest.hpp.
Member Function Documentation
asString()
std::string dodo::network::HTTPRequest::asString () const virtual
Return the HTTPRequest as a string.
Returns
the HTTPRequest as a string.
Implements dodo::network::HTTPFragment.
Definition at line 86 of file httprequest.cpp.
References dodo::network::HTTPRequest::HTTPRequestLine::asString(), dodo::network::HTTPMessage::body_, dodo::network::HTTPMessage::charCR, dodo::network::HTTPMessage::charLF, dodo::network::HTTPRequest::HTTPRequestLine::getMethod(), dodo::network::HTTPMessage::headers_, methodAllowsBody(), and request_line_.
Referenced by write().
getRequestLine()
HTTPRequestLine& dodo::network::HTTPRequest::getRequestLine () inline
Get the HTTPRequestLine.
Returns
The HTTPRequestLine.
Definition at line 164 of file httprequest.hpp.
References request_line_.
methodAllowsBody()
bool dodo::network::HTTPRequest::methodAllowsBody (Method method) static
Return true if the Method allows a body in the message.
Parameters
method the Method to check.
Returns
if the Method allows a body.
Definition at line 60 of file httprequest.cpp.
Referenced by asString().
methodAsString()
std::string dodo::network::HTTPRequest::methodAsString (Method method) static
Translate a Method enum to a human readable string.
Parameters
method The method to translate.
Returns
the string.
Definition at line 32 of file httprequest.cpp.
Referenced by dodo::network::HTTPRequest::HTTPRequestLine::asString().
methodFromString()
HTTPRequest::Method dodo::network::HTTPRequest::methodFromString (const std::string & s) static
Translate an uppercase string ('GET', "POST', ..) into a Method enum.
Parameters
s The uppercase string to translate.
Returns
the Method (and meINVALID if the string is not a Method).
Definition at line 47 of file httprequest.cpp.
References meINVALID.
Referenced by dodo::network::HTTPRequest::HTTPRequestLine::parse().
parse()
HTTPMessage::ParseResult dodo::network::HTTPRequest::parse (VirtualReadBuffer & data) virtual
Read the HTTPRequest from the socket.
Parameters
data The VirtualReadBuffer to read from.
Returns
The ParseResult.
Implements dodo::network::HTTPFragment.
Definition at line 99 of file httprequest.cpp.
References dodo::network::HTTPMessage::charCR, dodo::network::HTTPMessage::charLF, dodo::common::SystemError::ecOK, dodo::network::HTTPFragment::ParseResult::eof(), dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::HTTPFragment::ParseResult::ok(), dodo::network::HTTPRequest::HTTPRequestLine::parse(), dodo::network::HTTPMessage::parseBody(), dodo::network::HTTPMessage::parseHeaders(), dodo::network::HTTPFragment::peOk, request_line_, and dodo::network::HTTPFragment::ParseResult::setSystemError().
setRequestLine()
void dodo::network::HTTPRequest::setRequestLine (const HTTPRequestLine & req)
Set the HTTPRequestLine.
Parameters
req The HTTPRequestLine to set.
write()
common::SystemError dodo::network::HTTPRequest::write (BaseSocket * socket) const
Write the HTTPRequest to the socket.
Parameters
socket The BaseSocket to write to.
Returns
The SystemError.
Definition at line 211 of file httprequest.cpp.
References asString(), and dodo::network::BaseSocket::send().
Field Documentation
request_line_
HTTPRequestLine dodo::network::HTTPRequest::request_line_ protected
The HTTPRequestLine of the HTTPRequest.
Definition at line 202 of file httprequest.hpp.
Referenced by asString(), getRequestLine(), and parse().
The documentation for this class was generated from the following files:
src/include/network/protocol/http/httprequest.hpp
src/lib/network/protocol/http/httprequest.cpp