dodo: dodo::network::VirtualReadBuffer Class Reference
dodo::network::VirtualReadBuffer Class Reference abstract
Interface to read individual bytes whilst the implementation can read from an actual source (such as a network buffer) in larger chunks, reducing the number of required system calls.
#include <socketreadbuffer.hpp>
Public Member Functions
virtual char get () const =0
Get the current char from VirtualReadBuffer.
size_t getUnderflowCount () const
virtual common::SystemError next ()=0
Move to the next char from the VirtualReadBuffer.
virtual common::SystemError underflow ()=0
If the buffer_ underflows, the buffer_ must be reset refilledwith new data from the source.
Protected Attributes
char * buffer_
The buffer.
ssize_t bufsize_
The size of buffer_.
size_t underflows_
Detailed Description
Interface to read individual bytes whilst the implementation can read from an actual source (such as a network buffer) in larger chunks, reducing the number of required system calls.
This is covenient when implementing protocols that need be char (byte) scanned to parse.
Note that this interface requires a source that blocks on read. A call to next() will advance the current byte, but this in turn will call underflow, which in turn might do a read if it reached the end of available bytes.
See also
SocketReadBuffer and FileReadBuffer - both concrete implementations.
Definition at line 44 of file socketreadbuffer.hpp.
Member Function Documentation
get()
virtual char dodo::network::VirtualReadBuffer::get () const pure virtual
Get the current char from VirtualReadBuffer.
Returns
The current character read.
See also
next()
Implemented in dodo::network::StringReadBuffer, dodo::network::FileReadBuffer, and dodo::network::SocketReadBuffer.
Referenced by dodo::network::protocol::http::HTTPMessage::eatCRLF(), dodo::network::protocol::http::HTTPMessage::eatSpace(), dodo::network::protocol::http::HTTPVersion::parse(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), dodo::network::protocol::http::HTTPResponse::parse(), dodo::network::protocol::http::HTTPRequest::parseBody(), dodo::network::protocol::http::HTTPResponse::parseBody(), dodo::network::protocol::http::HTTPMessage::parseChunkedBody(), dodo::network::protocol::http::HTTPMessage::parseChunkHex(), dodo::network::protocol::http::HTTPMessage::parseCRLF(), dodo::network::protocol::http::HTTPMessage::parseFieldValue(), dodo::network::protocol::http::HTTPMessage::parseHeaders(), dodo::network::protocol::http::HTTPMessage::parseToken(), and dodo::network::protocol::http::HTTPMessage::parseUInt().
next()
virtual common::SystemError dodo::network::VirtualReadBuffer::next () pure virtual
Move to the next char from the VirtualReadBuffer.
Note that call will return a SystemError::ecEAGAIN if there is no more data (received within the prevailing timeout).
Returns
SystemError::ecOK and c is valid, or an SystemError.
Implemented in dodo::network::StringReadBuffer, dodo::network::FileReadBuffer, and dodo::network::SocketReadBuffer.
Referenced by dodo::network::protocol::http::HTTPMessage::eatCRLF(), dodo::network::protocol::http::HTTPMessage::eatSpace(), dodo::network::protocol::http::HTTPVersion::parse(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), dodo::network::protocol::http::HTTPResponse::parse(), dodo::network::protocol::http::HTTPRequest::parseBody(), dodo::network::protocol::http::HTTPResponse::parseBody(), dodo::network::protocol::http::HTTPMessage::parseChunkedBody(), dodo::network::protocol::http::HTTPMessage::parseChunkHex(), dodo::network::protocol::http::HTTPMessage::parseCRLF(), dodo::network::protocol::http::HTTPMessage::parseFieldValue(), dodo::network::protocol::http::HTTPMessage::parseHeaders(), dodo::network::protocol::http::HTTPMessage::parseToken(), and dodo::network::protocol::http::HTTPMessage::parseUInt().
underflow()
virtual common::SystemError dodo::network::VirtualReadBuffer::underflow () pure virtual
If the buffer_ underflows, the buffer_ must be reset refilledwith new data from the source.
Returns
Systemerror::ecOK on succes.
Implemented in dodo::network::StringReadBuffer, dodo::network::FileReadBuffer, and dodo::network::SocketReadBuffer.
Field Documentation
buffer_
char* dodo::network::VirtualReadBuffer::buffer_ protected
The buffer.
See also
bufsize_
Definition at line 77 of file socketreadbuffer.hpp.
Referenced by dodo::network::FileReadBuffer::FileReadBuffer(), dodo::network::SocketReadBuffer::get(), dodo::network::FileReadBuffer::get(), dodo::network::SocketReadBuffer::SocketReadBuffer(), dodo::network::SocketReadBuffer::underflow(), dodo::network::FileReadBuffer::underflow(), and dodo::network::SocketReadBuffer::~SocketReadBuffer().
bufsize_
ssize_t dodo::network::VirtualReadBuffer::bufsize_ protected
The size of buffer_.
Definition at line 82 of file socketreadbuffer.hpp.
Referenced by dodo::network::FileReadBuffer::FileReadBuffer(), dodo::network::SocketReadBuffer::SocketReadBuffer(), dodo::network::SocketReadBuffer::underflow(), and dodo::network::FileReadBuffer::underflow().
The documentation for this class was generated from the following file:
src/include/network/socketreadbuffer.hpp