dodo: dodo::network::protocol::http::HTTPResponse::HTTPResponseLine Class Reference
dodo::network::protocol::http::HTTPResponse::HTTPResponseLine Class Reference
A HTTP response line.
#include <httpresponse.hpp>
Public Member Functions
HTTPResponseLine ()
Default constructor.
HTTPResponseLine (const HTTPVersion &version, HTTPCode http_code)
Explicit consructor.
virtual std::string asString () const
Convert the HTTPResponseLine to a HTTP string.
HTTPCode getHTTPCode () const
The HTTP return code of the HTTPResponse.
const HTTPVersion & getHTTPVersion () const
The HTTPVersion of the response line.
virtual ParseResult parse (VirtualReadBuffer &data)
Read a complete HTTPFragment from a VirtualReadBuffer.
Private Attributes
HTTPCode http_code_
The http_code.
HTTPVersion version_
The HTTPVersion.
Additional Inherited Members
Public Types inherited from dodo::network::protocol::http::HTTPFragment
enum ParseError : unsigned int {
peOk = 0, peIncomplete, peSystemError, peExpectCRLF,
peUnFinishedToken, peExpectingHeaderColon, peInvalidHeaderFieldValue, peInvalidHeaderListEnd,
peInvalidMethod, peInvalidHTTPVersion, peInvalidRequestLine, peInvalidContentLength,
peUnexpectedBody, peInvalidTransferEncoding, peInvalidChunkHex, peInvalidLastChunk,
peExpectingUnsignedInt
}
Parse results returned by the parse functions.
Static Public Member Functions inherited from dodo::network::protocol::http::HTTPFragment
static std::string getParseResultAsString (ParseError error)
Return the string description of a ParseError.
Detailed Description
A HTTP response line.
Definition at line 161 of file httpresponse.hpp.
Constructor & Destructor Documentation
HTTPResponseLine() [1/2]
dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::HTTPResponseLine () inline
Default constructor.
Definition at line 167 of file httpresponse.hpp.
HTTPResponseLine() [2/2]
dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::HTTPResponseLine (const HTTPVersion & version, HTTPCode http_code) inline explicit
Explicit consructor.
Parameters
version The version to set.
http_code The HTTP code to set.
Definition at line 174 of file httpresponse.hpp.
Member Function Documentation
asString()
std::string dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::asString () const virtual
Convert the HTTPResponseLine to a HTTP string.
Returns
The HTTPResponseLine as a string.
Implements dodo::network::protocol::http::HTTPFragment.
Definition at line 99 of file httpresponse.cpp.
References dodo::network::protocol::http::HTTPVersion::asString(), dodo::network::protocol::http::HTTPMessage::charCR, dodo::network::protocol::http::HTTPMessage::charLF, dodo::network::protocol::http::HTTPMessage::charSP, http_code_, dodo::network::protocol::http::HTTPResponse::HTTPCodeAsString(), and version_.
Referenced by dodo::network::protocol::http::HTTPResponse::asString().
getHTTPCode()
HTTPCode dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::getHTTPCode () const inline
The HTTP return code of the HTTPResponse.
Returns
The HTTPCode.
Definition at line 194 of file httpresponse.hpp.
getHTTPVersion()
const HTTPVersion& dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::getHTTPVersion () const inline
The HTTPVersion of the response line.
Returns
The HTTPVersion
Definition at line 188 of file httpresponse.hpp.
References version_.
parse()
HTTPFragment::ParseResult dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse (VirtualReadBuffer & buffer) virtual
Read a complete HTTPFragment from a VirtualReadBuffer.
Parameters
buffer the VirtualReadBuffer to get characters from.
Returns
The ParseError.
Implements dodo::network::protocol::http::HTTPFragment.
Definition at line 111 of file httpresponse.cpp.
References dodo::network::protocol::http::HTTPMessage::charCR, dodo::network::protocol::http::HTTPMessage::charLF, dodo::network::protocol::http::HTTPMessage::eatSpace(), dodo::common::SystemError::ecOK, dodo::network::VirtualReadBuffer::get(), dodo::network::VirtualReadBuffer::next(), dodo::network::protocol::http::HTTPFragment::ParseResult::ok(), dodo::network::protocol::http::HTTPMessage::parseUInt(), dodo::network::protocol::http::HTTPFragment::peExpectCRLF, and dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError().
Referenced by dodo::network::protocol::http::HTTPResponse::parse().
Field Documentation
http_code_
HTTPCode dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::http_code_ private
The http_code.
Definition at line 200 of file httpresponse.hpp.
Referenced by asString().
version_
HTTPVersion dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::version_ private
The HTTPVersion.
Definition at line 194 of file httpresponse.hpp.
Referenced by asString(), and getHTTPVersion().
The documentation for this class was generated from the following files:
src/include/network/protocol/http/httpresponse.hpp
src/lib/network/protocol/http/httpresponse.cpp