dodo: dodo::network::X509Common Class Reference
dodo::network::X509Common Class Reference
Interface common to X509 documents.
#include <x509cert.hpp>
Data Structures
struct Identity
Attributes that together constitute a X509 identity.
struct SAN
Subject AltName record.
Public Types
enum SANType { SANType::stDNS = GEN_DNS, SANType::stURI = GEN_URI, SANType::stEMAIL = GEN_EMAIL, SANType::tsIP = GEN_IPADD }
The SubjectAltName type.
enum X509Type {
X509Type::Unknown, X509Type::PrivateKey, X509Type::PublicKey, X509Type::CertificateSigningRequest,
X509Type::Certificate
}
Enumeration of X509 document types.
Static Public Member Functions
static X509Type detectX509Type (const std::string file, std::string &tag)
Detects a X509 document type from a PEM file.
static std::string SANTypeAsString (const SANType &san_type)
Convert the SANType name to a string.
Static Protected Member Functions
static Identity parseIdentity (const std::string src)
Parse a subject or issuer string into an Identity.
Private Member Functions
X509Common ()=delete
Never construct, interface class.
~X509Common ()=delete
Never destruct, interface class.
Detailed Description
Interface common to X509 documents.
See Secure sockets for details on the role of this class.
Definition at line 39 of file x509cert.hpp.
Member Enumeration Documentation
SANType
enum dodo::network::X509Common::SANType strong
The SubjectAltName type.
Enumerator
stDNS
A DNS name such as myhost.mydomain.org.
stURI
An URI.
stEMAIL
An email address.
tsIP
An IPv4 or IPv6 address.
Definition at line 45 of file x509cert.hpp.
X509Type
enum dodo::network::X509Common::X509Type strong
Enumeration of X509 document types.
Enumerator
Unknown
Unknown PEM document.
PrivateKey
Private key PEM document (possibly encrypted).
PublicKey
Public key PEM document.
CertificateSigningRequest
CSR PEM document.
Certificate
Certificate PEM document.
Definition at line 165 of file x509cert.hpp.
Constructor & Destructor Documentation
X509Common()
dodo::network::X509Common::X509Common () private delete
Never construct, interface class.
~X509Common()
dodo::network::X509Common::~X509Common () private delete
Never destruct, interface class.
Member Function Documentation
detectX509Type()
X509Common::X509Type dodo::network::X509Common::detectX509Type (const std::string file, std::string & tag) static
Detects a X509 document type from a PEM file.
The PEM is not checked on validity, and a result other than X509Type::Unknown does not imply the document is well formed and valid. Note that both private key and encrypted private key PEM files are identified as X509Type::PrivateKey.
Parameters
file The file name to be content-checked.
tag Receives the PEM tag (eg 'CERTIFICATE','PRIVATE KEY',..).
Returns
the X509Type.
Definition at line 42 of file x509cert.cpp.
References Certificate, CertificateSigningRequest, PrivateKey, PublicKey, and Unknown.
parseIdentity()
X509Common::Identity dodo::network::X509Common::parseIdentity (const std::string src) static protected
Parse a subject or issuer string into an Identity.
Parameters
src The identity string
Returns
the Identity.
Definition at line 62 of file x509cert.cpp.
References dodo::network::X509Common::Identity::businessCategory, dodo::network::X509Common::Identity::commonName, dodo::network::X509Common::Identity::countryCode, dodo::network::X509Common::Identity::email, dodo::common::escapedSplit(), dodo::network::X509Common::Identity::jurisdictionC, dodo::network::X509Common::Identity::jurisdictionST, dodo::network::X509Common::Identity::locality, dodo::network::X509Common::Identity::organization, dodo::network::X509Common::Identity::organizationUnit, dodo::network::X509Common::Identity::other, dodo::network::X509Common::Identity::postalCode, dodo::network::X509Common::Identity::serialNumber, dodo::common::split(), dodo::network::X509Common::Identity::state, and dodo::network::X509Common::Identity::street.
Referenced by dodo::network::X509Certificate::getIssuer(), dodo::network::X509CertificateSigningRequest::getSubject(), and dodo::network::X509Certificate::getSubject().
SANTypeAsString()
static std::string dodo::network::X509Common::SANTypeAsString (const SANType & san_type) inline static
Convert the SANType name to a string.
Parameters
san_type The SANType to convert.
Returns
the string representation.
Definition at line 57 of file x509cert.hpp.
References stDNS, stEMAIL, stURI, and tsIP.
The documentation for this class was generated from the following files:
src/include/network/x509cert.hpp
src/lib/network/x509cert.cpp