dodo: dodo::BuildEnv Class Reference
dodo::BuildEnv Class Reference
Build information, generated by cmake during builds from buildenv.hpp.in.
#include <buildenv.hpp>
Public Types
enum cppStandard {
stUnknown, stPreCpp11, stCpp11, stCpp14,
stCpp17
}
C++ standard enum.
Static Public Member Functions
static std::string getBinaryDirectory ()
In very rare cases (examples requiring artefacts build in source checkouts), this is usefull.
static std::string getBuildDate ()
Get the build date.
static std::string getBuildSystem ()
Get the compiler host.
static std::string getBuildTarget ()
Get the build target / architecture.
static std::string getBuildTime ()
Get the build time.
static std::string getCMakeBuildType ()
Get the build type.
static std::string getCMakeVersion ()
Get the cmake version.
static std::string getCompilerId ()
Get the C++ compiler id, see https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html.
static std::string getCompilerVersion ()
Get the compiler version.
static cppStandard getCppStandard ()
Get the C++ standard in effect during compiling.
static std::string getCppStandardString ()
Get the C++ standard in effect during compiling as a string.
static std::string getDescription ()
Get a description of the build environment.
static std::string getProjectName ()
Get the project name.
static std::string getProjectVersion ()
Get the project version.
static int getProjectVersionMajor ()
Get the project version major.
static int getProjectVersionMinor ()
Get the project version minor.
static int getProjectVersionPatch ()
Get the project version patch.
static std::string getSourceDirectory ()
In rare cases (examples requiring artefacts build in source checkouts), this is usefull.
Detailed Description
Build information, generated by cmake during builds from buildenv.hpp.in.
CMAKE_CXX_COMPILER_ID GNU
CMAKE_CXX_COMPILER_VERSION 9.3.0
CMAKE_SYSTEM Linux-5.4.0-1041-azure
CMAKE_SYSTEM_PROCESSOR x86_64
PROJECT_NAME dodo
PROJECT_VERSION_STR 0.0.1
CMAKE_VERSION 3.19.7
CMAKE_BUILD_TYPE
Definition at line 20 of file buildenv.hpp.
Member Enumeration Documentation
cppStandard
enum dodo::BuildEnv::cppStandard
C++ standard enum.
Enumerator
stUnknown
Unknown C++ standard.
stPreCpp11
Before C++11.
stCpp11
C++ 11.
stCpp14
C++ 14.
stCpp17
C++ 17.
Definition at line 115 of file buildenv.hpp.
Member Function Documentation
getBinaryDirectory()
static std::string dodo::BuildEnv::getBinaryDirectory () inline static
In very rare cases (examples requiring artefacts build in source checkouts), this is usefull.
Returns
The source directory.
Definition at line 110 of file buildenv.hpp.
Referenced by getDescription().
getBuildDate()
static std::string dodo::BuildEnv::getBuildDate () inline static
Get the build date.
Returns
DATE.
Definition at line 92 of file buildenv.hpp.
Referenced by getDescription().
getBuildSystem()
static std::string dodo::BuildEnv::getBuildSystem () inline static
Get the compiler host.
Returns
CMAKE_SYSTEM.
Definition at line 38 of file buildenv.hpp.
Referenced by getDescription().
getBuildTarget()
static std::string dodo::BuildEnv::getBuildTarget () inline static
Get the build target / architecture.
Returns
CMAKE_SYSTEM_PROCESSOR.
Definition at line 44 of file buildenv.hpp.
Referenced by getDescription().
getBuildTime()
static std::string dodo::BuildEnv::getBuildTime () inline static
Get the build time.
Returns
TIME.
Definition at line 98 of file buildenv.hpp.
Referenced by getDescription().
getCMakeBuildType()
static std::string dodo::BuildEnv::getCMakeBuildType () inline static
Get the build type.
Returns
CMAKE_BUILD_TYPE.
Definition at line 86 of file buildenv.hpp.
Referenced by getDescription().
getCMakeVersion()
static std::string dodo::BuildEnv::getCMakeVersion () inline static
Get the cmake version.
Returns
CMAKE_VERSION.
Definition at line 80 of file buildenv.hpp.
Referenced by getDescription().
getCompilerId()
static std::string dodo::BuildEnv::getCompilerId () inline static
Get the C++ compiler id, see https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html.
Returns
CMAKE_CXX_COMPILER_ID.
Definition at line 26 of file buildenv.hpp.
Referenced by getDescription().
getCompilerVersion()
static std::string dodo::BuildEnv::getCompilerVersion () inline static
Get the compiler version.
Returns
CMAKE_CXX_COMPILER_VERSION.
Definition at line 32 of file buildenv.hpp.
Referenced by getDescription().
getCppStandard()
static cppStandard dodo::BuildEnv::getCppStandard () inline static
Get the C++ standard in effect during compiling.
Returns
The cppStandard.
Definition at line 142 of file buildenv.hpp.
References stCpp11, stCpp14, stCpp17, stPreCpp11, and stUnknown.
Referenced by getCppStandardString().
getCppStandardString()
static std::string dodo::BuildEnv::getCppStandardString () inline static
Get the C++ standard in effect during compiling as a string.
Returns
The cppStandard as a string.
Definition at line 127 of file buildenv.hpp.
References getCppStandard(), stCpp11, stCpp14, stCpp17, stPreCpp11, and stUnknown.
Referenced by getDescription().
getDescription()
static std::string dodo::BuildEnv::getDescription () inline static
Get a description of the build environment.
Returns
The description.
Definition at line 154 of file buildenv.hpp.
References getBinaryDirectory(), getBuildDate(), getBuildSystem(), getBuildTarget(), getBuildTime(), getCMakeBuildType(), getCMakeVersion(), getCompilerId(), getCompilerVersion(), getCppStandardString(), getProjectName(), getProjectVersion(), and getSourceDirectory().
getProjectName()
static std::string dodo::BuildEnv::getProjectName () inline static
Get the project name.
Returns
PROJECT_NAME.
Definition at line 50 of file buildenv.hpp.
Referenced by getDescription().
getProjectVersion()
static std::string dodo::BuildEnv::getProjectVersion () inline static
Get the project version.
Returns
PROJECT_VERSION_STR.
Definition at line 56 of file buildenv.hpp.
Referenced by getDescription().
getProjectVersionMajor()
static int dodo::BuildEnv::getProjectVersionMajor () inline static
Get the project version major.
Returns
PROJECT_VERSION_MAJOR.
Definition at line 62 of file buildenv.hpp.
getProjectVersionMinor()
static int dodo::BuildEnv::getProjectVersionMinor () inline static
Get the project version minor.
Returns
PROJECT_VERSION_MINOR.
Definition at line 68 of file buildenv.hpp.
getProjectVersionPatch()
static int dodo::BuildEnv::getProjectVersionPatch () inline static
Get the project version patch.
Returns
PROJECT_VERSION_PATCH.
Definition at line 74 of file buildenv.hpp.
getSourceDirectory()
static std::string dodo::BuildEnv::getSourceDirectory () inline static
In rare cases (examples requiring artefacts build in source checkouts), this is usefull.
Returns
The source directory.
Definition at line 104 of file buildenv.hpp.
Referenced by getDescription().
The documentation for this class was generated from the following file:
build/buildenv.hpp