dodo: dodo::common::OctetArray Class Reference
dodo::common::OctetArray Class Reference
An array of Octets with size elements.
#include <octetarray.hpp>
Public Types
enum MatchType { MatchType::Mismatch, MatchType::Contained, MatchType::Contains, MatchType::Full }
The way in which two OctetArray instances match.
Public Member Functions
OctetArray ()
Construct an empty OctetArray.
OctetArray (const std::string &s)
Construct and fill from a std::string, not including the NULL terminator (so size will be string.length()).
OctetArray (Octet *data, size_t size)
Construct an OctetArray by taking ownership of existing data (which will be freed when this object is destructed).
virtual ~OctetArray ()
Destruct and clean.
void append (const Octet *src, size_t n)
Append from arbitrary memory areas.
void append (const OctetArray &src)
Append another OctetArray.
void append (const OctetArray &src, size_t n)
Append the first n Octets from OctetArray.
void append (Octet src)
Append a single Octet.
std::string asString () const
Cast to a std::string.
OctetArray & decodeBase64 (const std::string &src)
Decodes the base64 string into this OctetArray.
std::string encodeBase64 () const
Encodes the this OctetArray into a base64-encoded string.
void free ()
Free and clear data.
Octet * getArray () const
Return the array.
Octet getOctet (size_t index) const
Return the Octet at index.
size_t getSize () const
Return the array size.
std::string hexDump (size_t n) const
hex dump the first n octets of the data.
MatchType match (const OctetArray &other, size_t index, size_t &octets)
Match this OctetArray from index to the other array (entirely).
OctetArray & operator= (const std::string &s)
Assign from std::string, not including a NULL terminator (so size will be string.length()).
void random (size_t octets)
Generate a random set of Octets.
void reserve (size_t size)
Reserve memory in the OctetArray.
Data Fields
const size_t alloc_block = 32
Always allocate chunks of this size.
Private Attributes
size_t allocated_size
The allocated size, always >= size.
Octet * array_
The Octet array.
size_t size_
The array size in Octets (using an int as that is what OpenSSL uses)
Detailed Description
An array of Octets with size elements.
Provides base64 conversion, random data generation, appending of data from various other sources. Memory management is implicit, resizing allocates at least a chunk.
Definition at line 40 of file octetarray.hpp.
Member Enumeration Documentation
MatchType
enum dodo::common::OctetArray::MatchType strong
The way in which two OctetArray instances match.
Enumerator
Mismatch
The local array does not match the other array.
Contained
The local array is contained in the other array, but the other array has more data.
Contains
The local array contains the other array, but the local array has more data.
Full
The local and other array are equal in content and size.
Definition at line 116 of file octetarray.hpp.
Constructor & Destructor Documentation
OctetArray() [1/3]
dodo::common::OctetArray::OctetArray () inline
Construct an empty OctetArray.
Definition at line 47 of file octetarray.hpp.
OctetArray() [2/3]
dodo::common::OctetArray::OctetArray (Octet * data, size_t size) inline
Construct an OctetArray by taking ownership of existing data (which will be freed when this object is destructed).
Parameters
data The data.
size The size of the data.
Definition at line 54 of file octetarray.hpp.
References array_.
OctetArray() [3/3]
dodo::common::OctetArray::OctetArray (const std::string & s) inline
Construct and fill from a std::string, not including the NULL terminator (so size will be string.length()).
Parameters
s The source string.
Definition at line 63 of file octetarray.hpp.
~OctetArray()
virtual dodo::common::OctetArray::~OctetArray () inline virtual
Destruct and clean.
Definition at line 70 of file octetarray.hpp.
References free().
Member Function Documentation
append() [1/4]
void dodo::common::OctetArray::append (const Octet * src, size_t n)
Append from arbitrary memory areas.
Parameters
src The memory to append from.
n The number of octets to append.
Definition at line 78 of file octetarray.cpp.
References array_, reserve(), and size_.
append() [2/4]
void dodo::common::OctetArray::append (const OctetArray & src)
Append another OctetArray.
Parameters
src The OctetArray to append.
Definition at line 65 of file octetarray.cpp.
References array_, reserve(), and size_.
Referenced by dodo::common::DataCrypt::decrypt(), dodo::network::protocol::stomp::Connect::generate(), and dodo::persist::KVStore::getValue().
append() [3/4]
void dodo::common::OctetArray::append (const OctetArray & src, size_t n)
Append the first n Octets from OctetArray.
Parameters
src The OctetArray to append from.
n The number of octets to append.
Definition at line 71 of file octetarray.cpp.
References array_, reserve(), size_, and throw_Exception.
append() [4/4]
void dodo::common::OctetArray::append (Octet src)
Append a single Octet.
Parameters
src The Octet to append.
Definition at line 84 of file octetarray.cpp.
References array_, reserve(), and size_.
asString()
std::string dodo::common::OctetArray::asString () const
Cast to a std::string.
Be aware that the string is read to either the first zero (NULL) or up to size. So if the decoded data contains intermediate zeros the string will not cover all octets.
Returns
A string representation of OctetArray.
Definition at line 98 of file octetarray.cpp.
References array_, and size_.
decodeBase64()
OctetArray & dodo::common::OctetArray::decodeBase64 (const std::string & src)
Decodes the base64 string into this OctetArray.
Parameters
src The base64-encoded source string.
Returns
A reference to this OctetArray
Definition at line 114 of file octetarray.cpp.
References array_, reserve(), and throw_Exception.
Referenced by dodo::common::DataCrypt::decrypt().
encodeBase64()
std::string dodo::common::OctetArray::encodeBase64 () const
Encodes the this OctetArray into a base64-encoded string.
Returns
The base64 encoded data of the OctetArray.
Definition at line 136 of file octetarray.cpp.
References array_, size_, and throw_Exception.
Referenced by dodo::common::DataCrypt::encrypt().
free()
void dodo::common::OctetArray::free ()
Free and clear data.
Definition at line 56 of file octetarray.cpp.
References allocated_size, array_, and size_.
Referenced by dodo::network::protocol::stomp::Connect::generate(), dodo::persist::KVStore::getValue(), and ~OctetArray().
getArray()
Octet* dodo::common::OctetArray::getArray () const inline
Return the array.
Returns
a pointer to the array of Octets.
Definition at line 182 of file octetarray.hpp.
References array_.
Referenced by dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), dodo::persist::KVStore::insertKey(), dodo::network::TCPConnectionData::readBuffer(), and dodo::persist::KVStore::setKey().
getOctet()
Octet dodo::common::OctetArray::getOctet (size_t index) const inline
Return the Octet at index.
Only in debug builds the index is asserted to be within range.
Parameters
index The index of the Octet
Returns
The Octet.
Definition at line 195 of file octetarray.hpp.
References array_, and size_.
Referenced by dodo::network::protocol::stomp::Frame::readCommand().
getSize()
size_t dodo::common::OctetArray::getSize () const inline
Return the array size.
Returns
the array size.
Definition at line 188 of file octetarray.hpp.
References size_.
Referenced by dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), dodo::persist::KVStore::insertKey(), dodo::network::TCPConnectionData::readBuffer(), dodo::network::protocol::stomp::Frame::readCommand(), and dodo::persist::KVStore::setKey().
hexDump()
std::string dodo::common::OctetArray::hexDump (size_t n) const
hex dump the first n octets of the data.
Parameters
n The number of octets to dump.
Returns
a string with hex numbers.
Definition at line 183 of file octetarray.cpp.
References array_, and size_.
Referenced by dodo::network::TCPConnectionData::readBuffer().
match()
OctetArray::MatchType dodo::common::OctetArray::match (const OctetArray & other, size_t index, size_t & octets)
Match this OctetArray from index to the other array (entirely).
Parameters
other The other OctetArray.
index The start index into the local array to match from.
octets The number of Octets, from the start of the arrays, that match.
Returns
The MatchType.
Definition at line 162 of file octetarray.cpp.
References array_, Contained, Contains, Full, Mismatch, and size_.
operator=()
OctetArray & dodo::common::OctetArray::operator= (const std::string & s)
Assign from std::string, not including a NULL terminator (so size will be string.length()).
Parameters
s The base64 string to assign from.
Returns
This OctetArray.
Definition at line 89 of file octetarray.cpp.
References array_, and reserve().
random()
void dodo::common::OctetArray::random (size_t octets)
Generate a random set of Octets.
Parameters
octets The number of random Octets.
Definition at line 106 of file octetarray.cpp.
References array_, reserve(), and size_.
Referenced by dodo::common::DataCrypt::encrypt().
reserve()
void dodo::common::OctetArray::reserve (size_t size)
Reserve memory in the OctetArray.
Parameters
size The size in bytes to allocate .
Definition at line 33 of file octetarray.cpp.
References alloc_block, allocated_size, array_, size_, and throw_SystemException.
Referenced by append(), decodeBase64(), dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), operator=(), random(), and dodo::network::TCPConnectionData::readBuffer().
Field Documentation
alloc_block
const size_t dodo::common::OctetArray::alloc_block = 32
Always allocate chunks of this size.
Any OctetArray that has been called with reserve(n > 1) will at least allocate 1 chunk of alloc_block bytes. Avoids frequent calls to realloc when using many append calls with small amount of data such as append(Octet).
Definition at line 176 of file octetarray.hpp.
Referenced by reserve().
allocated_size
size_t dodo::common::OctetArray::allocated_size private
The allocated size, always >= size.
Definition at line 211 of file octetarray.hpp.
Referenced by free(), and reserve().
array_
Octet* dodo::common::OctetArray::array_ private
The Octet array.
Definition at line 201 of file octetarray.hpp.
Referenced by append(), asString(), decodeBase64(), encodeBase64(), free(), getArray(), getOctet(), hexDump(), match(), OctetArray(), operator=(), random(), and reserve().
size_
size_t dodo::common::OctetArray::size_ private
The array size in Octets (using an int as that is what OpenSSL uses)
Definition at line 206 of file octetarray.hpp.
Referenced by append(), asString(), encodeBase64(), free(), getOctet(), getSize(), hexDump(), match(), random(), and reserve().
The documentation for this class was generated from the following files:
src/include/common/octetarray.hpp
src/lib/common/octetarray.cpp