dodo: dodo::network::SocketReadBuffer Class Reference
dodo::network::SocketReadBuffer Class Reference
SocketReadBuffer is a VirtualReadBuffer that reads from the BaseSocket in chunks internally.
#include <socketreadbuffer.hpp>
Public Member Functions
SocketReadBuffer (BaseSocket *socket, size_t bufsize=8192)
Construct a SocketReadBuffer.
virtual ~SocketReadBuffer ()
Destruct the SocketReadBuffer, de-allocate the internal buffer.
virtual char get () const
Get the current char from VirtualReadBuffer.
virtual common::SystemError next ()
Move to the next char from the VirtualReadBuffer.
virtual common::SystemError underflow ()
If the buffer_ is fully read.
Public Member Functions inherited from dodo::network::VirtualReadBuffer
size_t getUnderflowCount () const
Protected Attributes
ssize_t idx_
The current index of get(char &c) in buffer_.
ssize_t received_
The number of chars received in the last underflow().
BaseSocket * socket_
The associated network::BaseSocket*.
Protected Attributes inherited from dodo::network::VirtualReadBuffer
char * buffer_
The buffer.
ssize_t bufsize_
The size of buffer_.
size_t underflows_
Detailed Description
SocketReadBuffer is a VirtualReadBuffer that reads from the BaseSocket in chunks internally.
Note that the BaseSocket should be in blocking mode.
Definition at line 92 of file socketreadbuffer.hpp.
Constructor & Destructor Documentation
SocketReadBuffer()
dodo::network::SocketReadBuffer::SocketReadBuffer (BaseSocket * socket, size_t bufsize = 8192) explicit
Construct a SocketReadBuffer.
If BaseSocket::getBlocking() is false, an exception is thrown.
Parameters
socket The blocking BaseSocket to read from.
bufsize The buffer size to use
Definition at line 31 of file socketreadbuffer.cpp.
References dodo::network::VirtualReadBuffer::buffer_, dodo::network::VirtualReadBuffer::bufsize_, dodo::network::BaseSocket::getBlocking(), idx_, received_, socket_, and throw_Exception.
~SocketReadBuffer()
dodo::network::SocketReadBuffer::~SocketReadBuffer () virtual
Destruct the SocketReadBuffer, de-allocate the internal buffer.
Any bytes buffered will be lost.
Definition at line 40 of file socketreadbuffer.cpp.
References dodo::network::VirtualReadBuffer::buffer_.
Member Function Documentation
get()
char dodo::network::SocketReadBuffer::get () const virtual
Get the current char from VirtualReadBuffer.
Returns
The current character read.
See also
next()
Implements dodo::network::VirtualReadBuffer.
Definition at line 54 of file socketreadbuffer.cpp.
References dodo::network::VirtualReadBuffer::buffer_, and idx_.
next()
common::SystemError dodo::network::SocketReadBuffer::next () virtual
Move to the next char from the VirtualReadBuffer.
Note that call will return a SystemError::ecEAGAIN if there is no more data (received within the prevailing timeout).
Returns
SystemError::ecOK and c is valid, or an SystemError.
Implements dodo::network::VirtualReadBuffer.
Definition at line 58 of file socketreadbuffer.cpp.
References idx_, and underflow().
underflow()
common::SystemError dodo::network::SocketReadBuffer::underflow () virtual
If the buffer_ is fully read.
eset and read new data from the socket.
Returns
Systemerror::ecOK on succes.
Implements dodo::network::VirtualReadBuffer.
Definition at line 44 of file socketreadbuffer.cpp.
References dodo::network::VirtualReadBuffer::buffer_, dodo::network::VirtualReadBuffer::bufsize_, dodo::common::SystemError::ecOK, idx_, dodo::network::BaseSocket::receive(), received_, and socket_.
Referenced by next().
Field Documentation
idx_
ssize_t dodo::network::SocketReadBuffer::idx_ protected
The current index of get(char &c) in buffer_.
Definition at line 128 of file socketreadbuffer.hpp.
Referenced by get(), next(), SocketReadBuffer(), and underflow().
received_
ssize_t dodo::network::SocketReadBuffer::received_ protected
The number of chars received in the last underflow().
Definition at line 133 of file socketreadbuffer.hpp.
Referenced by SocketReadBuffer(), and underflow().
socket_
BaseSocket* dodo::network::SocketReadBuffer::socket_ protected
The associated network::BaseSocket*.
Definition at line 123 of file socketreadbuffer.hpp.
Referenced by SocketReadBuffer(), and underflow().
The documentation for this class was generated from the following files:
src/include/network/socketreadbuffer.hpp
src/lib/network/socketreadbuffer.cpp