dodo: dodo::common::Application Class Reference
dodo::common::Application Class Reference
Red tape wrapper class for applications, from command line to services.
#include <application.hpp>
Data Structures
struct StartParameters
Start parameters for the Application.
Public Types
enum HostType {
HostType::BareMetal, HostType::Docker, HostType::VirtualBox, HostType::VMWare,
HostType::KVM, HostType::GenericVM
}
The type of host the Application is running on.
Public Member Functions
Application (const StartParameters &param)
Construct an Application instance.
virtual ~Application ()
Destructor.
HostType getHostType () const
Return the HostType the Application is running on.
bool hasStopRequest () const
Return true when the main thread got a SIGTERM or SIGQUIT.
virtual int run ()
Override.
Private Member Functions
HostType detectHostType ()
Detect the HostType of the host the Application is running on.
void installSignalHandlers ()
Install the signal handlers.
void onSignal (int signal)
Called by signal_handler.
Static Private Member Functions
static void signal_handler (int signal)
Signal handler called by the OS.
Private Attributes
std::string config_file_
The configuration file name.
bool has_stop_request_
True when the Application main pid got a signal to stop (SIGTERM).
HostType hosttype_
The HostType, detected once in the Application constructor.
Logger * logger_
The Logger.
Static Private Attributes
static Application * application_ = nullptr
Singleton Application object.
Detailed Description
Red tape wrapper class for applications, from command line to services.
The Application class
initializes and closes the dodo library.
installs signal handlers, flag when the Application is requested to stop.
determining the HostType.
exposing and managing the configuration file
providing a logging mechanism
using namespace dodo::common;
class MyApp : public common::Application {
  public:
    MyApp( const StartParameters &param ) : common::Application( param ) {}
    virtual int run() { cout << "Hello world!" << endl; return 0; }
};
int main(int argc, char* argv[], char** envp) {
  try {
    MyApp app( { "myapp", "myapp.cnf", argc, argv, envp } );
    return app.run();
  }
  catch ( const std::exception &e ) {
    cerr << e.what() << endl;
    return 1;
  }
}
Definition at line 61 of file application.hpp.
Member Enumeration Documentation
HostType
enum dodo::common::Application::HostType strong
The type of host the Application is running on.
Enumerator
BareMetal
Bare metal deployment.
Docker
Docker container.
VirtualBox
VirtualBox.
VMWare
VMWare.
KVM
RedHat KVM.
GenericVM
An indeterminate virtual machine.
Definition at line 67 of file application.hpp.
Constructor & Destructor Documentation
Application()
dodo::common::Application::Application (const StartParameters & param)
Construct an Application instance.
Parameters
param The Application start parameters.
Exceptions
dodo::common::Exception when the name is empty, the config file is not empty and invalid.
Definition at line 33 of file application.cpp.
References application_, dodo::common::Application::StartParameters::config, detectHostType(), dodo::common::Config::getAppName(), has_stop_request_, hosttype_, dodo::common::Logger::Info, dodo::common::Config::initialize(), dodo::common::Logger::initialize(), dodo::initLibrary(), installSignalHandlers(), dodo::common::Logger::log(), and logger_.
~Application()
dodo::common::Application::~Application () virtual
Destructor.
Definition at line 44 of file application.cpp.
References dodo::common::Config::config_, and dodo::common::Logger::logger_.
Member Function Documentation
detectHostType()
Application::HostType dodo::common::Application::detectHostType () private
Detect the HostType of the host the Application is running on.
Returns
The HostType;
Definition at line 73 of file application.cpp.
References BareMetal, Docker, dodo::common::fileReadAccess(), dodo::common::fileReadStrings(), GenericVM, KVM, VirtualBox, and VMWare.
Referenced by Application().
getHostType()
HostType dodo::common::Application::getHostType () const inline
Return the HostType the Application is running on.
Returns
The HostType.
Definition at line 103 of file application.hpp.
References hosttype_.
hasStopRequest()
bool dodo::common::Application::hasStopRequest () const inline
Return true when the main thread got a SIGTERM or SIGQUIT.
Returns
true when the main thread got a SIGTERM or SIGQUIT.
Definition at line 109 of file application.hpp.
References has_stop_request_.
installSignalHandlers()
void dodo::common::Application::installSignalHandlers () private
Install the signal handlers.
Definition at line 54 of file application.cpp.
References signal_handler().
Referenced by Application().
onSignal()
void dodo::common::Application::onSignal (int signal) private
Called by signal_handler.
Note that this call can be made at any time interrupting the current thread, but no need for synchronization setting has_stop_request_ to true, other threads only read it.
Parameters
signal The received signal.
Definition at line 60 of file application.cpp.
References has_stop_request_, and log_Warning.
Referenced by signal_handler().
run()
virtual int dodo::common::Application::run () inline virtual
Override.
Returns
the return code as returned to the OS (exit code of the process).
Definition at line 117 of file application.hpp.
signal_handler()
void dodo::common::Application::signal_handler (int signal) static private
Signal handler called by the OS.
Depends on application_ to be valid.
Parameters
signal the signal received.
Returns
void
Definition at line 50 of file application.cpp.
References application_, and onSignal().
Referenced by installSignalHandlers().
Field Documentation
application_
Application * dodo::common::Application::application_ = nullptr static private
Singleton Application object.
Definition at line 149 of file application.hpp.
Referenced by Application(), and signal_handler().
config_file_
std::string dodo::common::Application::config_file_ private
The configuration file name.
Definition at line 154 of file application.hpp.
has_stop_request_
bool dodo::common::Application::has_stop_request_ private
True when the Application main pid got a signal to stop (SIGTERM).
Definition at line 164 of file application.hpp.
Referenced by Application(), hasStopRequest(), and onSignal().
hosttype_
HostType dodo::common::Application::hosttype_ private
The HostType, detected once in the Application constructor.
Definition at line 159 of file application.hpp.
Referenced by Application(), and getHostType().
logger_
Logger* dodo::common::Application::logger_ private
The Logger.
Definition at line 169 of file application.hpp.
Referenced by Application().
The documentation for this class was generated from the following files:
src/include/common/application.hpp
src/lib/common/application.cpp