dodo: dodo::persist::KVStore Class Reference
dodo::persist::KVStore Class Reference
A persistent, multi-threaded key-value store backed by sqlite3 database (file).
#include <kvstore.hpp>
Data Structures
struct MetaData
Meta data concerning the key.
Public Member Functions
KVStore (const std::filesystem::path &path)
Create the KVStore object against the path.
~KVStore ()
Destructor, cleanup sync and close the SQLLite database.
void checkpoint ()
Sync all to disk - issue a SQLite full checkpoint.
void commitTransaction ()
Commit a transaction.
bool deleteKey (const std::string &key)
Delete the key or return false if the key does not exist.
std::string ensureWithDefault (const std::string &key, const std::string &def)
If the key does not exist, create it with the default and return the default.
double ensureWithDefault (const std::string &key, double &def)
If the key does not exist, create it with the default and return the default.
int64_t ensureWithDefault (const std::string &key, int64_t &def)
If the key does not exist, create it with the default and return the default.
bool exists (const std::string &key) const
Check if the key exists.
void filterKeys (std::list< std::string > &keys, const std::string &filter)
Return a list of keys that match the filter.
double getDouble (const std::string &key)
Presumes the key exists, and throws an common::Exception if it does not.
MetaData getMetaData (const std::string &key)
Get MetaData for the key.
std::string getString (const std::string &key)
Presumes the key exists, and throws an common::Exception if it does not.
bool getValue (const std::string &key, common::Bytes &value) const
If the key exists, returns true and copies (overwrites) data to the Bytes.
bool getValue (const std::string &key, double &value) const
If the key exists, returns true and sets the value parameter.
bool getValue (const std::string &key, int64_t &value) const
If the key exists, returns true and sets the value parameter.
bool getValue (const std::string &key, std::string &value) const
If the key exists, returns true and sets the value parameter.
bool insertKey (const std::string &key, const common::Bytes &value)
Insert a (key, Bytes) pair.
bool insertKey (const std::string &key, const double &value)
Insert a (key, double) pair.
bool insertKey (const std::string &key, const int64_t &value)
Insert a (key, int64_t) pair.
bool insertKey (const std::string &key, const std::string &value)
Insert a (key, string) pair.
void optimize ()
Optimzime, preferably called after workload and implicitly called by the destructor.
void rollbackTransaction ()
Rollback a transaction.
bool setKey (const std::string &key, const common::Bytes &value)
Set the binary data/Bytes value of an existing key.
bool setKey (const std::string &key, const double &value)
Set the double value of an existing key.
bool setKey (const std::string &key, const int64_t &value)
Set the int64_t value of an existing key.
bool setKey (const std::string &key, const std::string &value)
Set the string value of an existing key.
void startTransaction ()
Start a transaction.
void vacuum ()
Vaccum - clean and defragment, which may increase efficiency after heavy deletion and/or modification.
Protected Member Functions
void createSchema ()
Create the SQLite schema.
void prepareSQL ()
Prepare all SQL statements.
Protected Attributes
sqlite::Database * db_
std::filesystem::path path_
The filesystem path to the kvstore.
sqlite::DML * stmt_delete_
Delete key pair statement handle.
sqlite::Query * stmt_exists_
sqlite::Query * stmt_getvalue_
Get-value-for-key statement handle.
sqlite::DML * stmt_insert_
Insert key pair statement handle.
sqlite::Query * stmt_key_filter_
Key filter statement handle.
sqlite::Query * stmt_key_value_filter_
Key + value filter statement handle.
sqlite::Query * stmt_metadata_
Get metadata statement handle.
sqlite::DML * stmt_update_
Update key pair statement handle.
Detailed Description
A persistent, multi-threaded key-value store backed by sqlite3 database (file).
If each thread uses its own KVStore object, no explicit synchronization is required between the threads. Cluster filesystems are not supported - two processes can only write to a single SQLite file if the processes run on the same host.
The KVStore is backed by the kvstore table. In SQLite, values in the same column can have different data types, so the table can store values of any of the supported data types:
DataType C++ type SQLite type
dtInteger int64_t SQLITE_INTEGER
dtFloat double SQLITE_FLOAT
dtText std::string SQLITE3_TEXT
dtBlob common::Bytes SQLITE_BLOB
dtUnknown used to indicate the unknown dataType of a non-existing key
In typical use the code is aware of the datatype of a key, so typical use would be
persist::KVStore store("mystore.db");
store.insertKey("pi", 3.14);         // insert as a double value
double pi = store.asDouble("pi");    // retrieve as a double value as we know it is a double.
Moreover, SQLite will convert (CAST) between types where possible, but revert to defaults when it can't. For example,
store.insertKey("key", "value");
cout <<  store.asInteger("key") << endl;
will output 0 as the string "value" does not convert to an integer. Use getMetaData to check if a key is of the expected DataType.
It is also possible to store dodo::common::Bytes (dtBlob / SQLITE_BLOB) types.
The SQLite database is initailized in WAL mode for performance. Make sure to use transactions to group bulk insertKey or setKey as that is much faster.
The examples/kvstore/kvstore.cpp is a simple speed test using a KVStore:
#include <iostream>
#include <dodo.hpp>
using namespace dodo;
using namespace std;
#define KEY_SPACE 160000
#define KEY_MAX_LENGTH 64
#define DATA_MAX_LENGTH 128
#define MAX_SETKEYS 1000
set<string> keys;
string random_string(size_t length) {
  auto randchar = []() -> char
  {
      const char charset[] =
      "0123456789"
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      "abcdefghijklmnopqrstuvwxyz";
      const size_t max_index = (sizeof(charset) - 1);
      return charset[ rand() % max_index ];
  };
  string str(length,0);
  generate_n( str.begin(), length, randchar );
  return str;
}
void setupTestData() {
  for ( size_t i = 0; i < KEY_SPACE; i++ ) {
    keys.insert( random_string( rand() % KEY_MAX_LENGTH ) );
  }
}
void insertKeys(persist::KVStore &store) {
  store.startTransaction();
  for ( const auto &k : keys ) {
    store.insertKey( k, random_string( rand() % DATA_MAX_LENGTH ) );
  }
  store.commitTransaction();
}
void fetchKeys(persist::KVStore &store) {
  for ( const auto &k : keys ) {
    string value = "";
    if ( ! store.getValue( k, value ) ) throw runtime_error( "key not found - cannot be!" );
  }
}
void updateKeys(persist::KVStore &store) {
  size_t count = 0;
  for ( const auto &k : keys ) {
    store.setKey( k, random_string( rand() % DATA_MAX_LENGTH ) );
    if ( ++count > MAX_SETKEYS ) break;
  }
}
int main() {
  try {
    persist::KVStore store( "kvstore.db" );
    common::StopWatch sw;
    double time_setup = 0.0;
    double time_insert = 0.0;
    double time_checkpoint = 0.0;
    double time_fetch = 0.0;
    double time_update = 0.0;
    sw.start();
    setupTestData();
    time_setup = sw.restart();
    insertKeys( store );
    time_insert = sw.restart();
    store.checkpoint();
    time_checkpoint = sw.restart();
    fetchKeys( store );
    time_fetch = sw.restart();
    updateKeys( store );
    time_update = sw.stop();
    cout << "setup " << time_setup << "s" << endl;
    cout << "insertKey (bulk) " << time_insert << "s" << endl;
    cout << "checkpoint " << time_checkpoint << "s" << endl;
    cout << "getValue " << time_fetch << "s" << endl;
    cout << "setKey (single) " << time_update << "s" << endl;
    cout << static_cast<double>(keys.size())/time_insert << " insertKey (bulk) per second" << endl;
    cout << static_cast<double>(keys.size())/time_fetch << " getValue per second" << endl;
    cout << static_cast<double>(MAX_SETKEYS)/time_update << " setKey (single) per second" << endl;
  }
  catch ( const runtime_error  &e ) {
    cerr << e.what() << endl;
  }
  return 0;
}
Definition at line 77 of file kvstore.hpp.
Constructor & Destructor Documentation
KVStore()
dodo::persist::KVStore::KVStore (const std::filesystem::path & path)
Create the KVStore object against the path.
If the KVStore does not exist yet, it is created. If it already exists, it is opened.
Parameters
path The filesystem path of the KVStore file.
Definition at line 34 of file kvstore.cpp.
References createSchema(), path_, prepareSQL(), stmt_delete_, stmt_getvalue_, stmt_insert_, stmt_key_filter_, stmt_key_value_filter_, stmt_metadata_, and stmt_update_.
~KVStore()
dodo::persist::KVStore::~KVStore ()
Destructor, cleanup sync and close the SQLLite database.
Definition at line 50 of file kvstore.cpp.
References checkpoint(), optimize(), stmt_delete_, stmt_getvalue_, stmt_insert_, stmt_key_filter_, stmt_key_value_filter_, stmt_metadata_, and stmt_update_.
Member Function Documentation
checkpoint()
void dodo::persist::KVStore::checkpoint ()
Sync all to disk - issue a SQLite full checkpoint.
Definition at line 64 of file kvstore.cpp.
References dodo::persist::sqlite::Database::checkPointFull().
Referenced by ~KVStore().
commitTransaction()
void dodo::persist::KVStore::commitTransaction ()
Commit a transaction.
Throws a dodo::common::Exception when no transaction has started.
Definition at line 68 of file kvstore.cpp.
References dodo::persist::sqlite::Database::commit().
createSchema()
void dodo::persist::KVStore::createSchema () protected
Create the SQLite schema.
Definition at line 72 of file kvstore.cpp.
References dodo::persist::sqlite::DDL::execute(), dodo::persist::sqlite::Statement::prepare(), and dodo::persist::sqlite::Query::step().
Referenced by KVStore().
deleteKey()
bool dodo::persist::KVStore::deleteKey (const std::string & key)
Delete the key or return false if the key does not exist.
Parameters
key The key.
Returns
True if the key existed.
Definition at line 90 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_delete_.
ensureWithDefault() [1/3]
std::string dodo::persist::KVStore::ensureWithDefault (const std::string & key, const std::string & def)
If the key does not exist, create it with the default and return the default.
If the key exists, return its value (which may not be the default).
Parameters
key The key.
def The string value for the key if it does not exist.
Returns
The key value.
Definition at line 97 of file kvstore.cpp.
References getValue(), and insertKey().
ensureWithDefault() [2/3]
double dodo::persist::KVStore::ensureWithDefault (const std::string & key, double & def)
If the key does not exist, create it with the default and return the default.
If the key exists, return its value (which may not be the default).
Parameters
key The key.
def The double value for the key if it does not exist.
Returns
The key value.
Definition at line 107 of file kvstore.cpp.
References getValue(), and insertKey().
ensureWithDefault() [3/3]
int64_t dodo::persist::KVStore::ensureWithDefault (const std::string & key, int64_t & def)
If the key does not exist, create it with the default and return the default.
If the key exists, return its value (which may not be the default).
Parameters
key The key.
def The int64_t value for the key if it does not exist.
Returns
The key value.
Definition at line 117 of file kvstore.cpp.
References getValue(), and insertKey().
exists()
bool dodo::persist::KVStore::exists (const std::string & key) const
Check if the key exists.
Unless the value is not required , it is more efficient to get the value in one go by calling the getString(), getDouble(), getInt64() and getData() members, which return false if the key does not exist.
Parameters
key The key to check for.
Returns
False if the key does not exist.
Definition at line 127 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getInt(), dodo::persist::sqlite::Statement::reset(), and dodo::persist::sqlite::Query::step().
filterKeys()
void dodo::persist::KVStore::filterKeys (std::list< std::string > & keys, const std::string & filter)
Return a list of keys that match the filter.
Parameters
keys The list that receives the keys. The list is cleared before assigning keys so it may turn up empty if the filter matches no keys.
filter The SQL-style case-sensitive filter as in 'match', 'match'
Definition at line 135 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getText(), dodo::persist::sqlite::Statement::reset(), dodo::persist::sqlite::Query::step(), and stmt_key_filter_.
getDouble()
double dodo::persist::KVStore::getDouble (const std::string & key)
Presumes the key exists, and throws an common::Exception if it does not.
Otherwise, return the value for the key as a double.
Parameters
key
Returns
The double value for the key.
getMetaData()
KVStore::MetaData dodo::persist::KVStore::getMetaData (const std::string & key)
Get MetaData for the key.
Parameters
key The key.
Returns
the MetaData for the key.
Definition at line 144 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getDataType(), dodo::persist::sqlite::Query::getDouble(), dodo::persist::sqlite::Query::getInt64(), dodo::persist::KVStore::MetaData::last_modified, dodo::persist::sqlite::Statement::reset(), dodo::persist::sqlite::Query::step(), stmt_metadata_, dodo::persist::KVStore::MetaData::type, and dodo::persist::KVStore::MetaData::update_count.
getString()
std::string dodo::persist::KVStore::getString (const std::string & key)
Presumes the key exists, and throws an common::Exception if it does not.
Otherwise, return the value for the key as a string.
Parameters
key
Returns
The string value for the key.
getValue() [1/4]
bool dodo::persist::KVStore::getValue (const std::string & key, common::Bytes & value) const
If the key exists, returns true and copies (overwrites) data to the Bytes.
Parameters
key The key to get the value for.
value The Bytes that will receive the data.
Returns
False if the key does not exist.
Definition at line 189 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getBytes(), dodo::persist::sqlite::Statement::reset(), dodo::persist::sqlite::Query::step(), and stmt_getvalue_.
getValue() [2/4]
bool dodo::persist::KVStore::getValue (const std::string & key, double & value) const
If the key exists, returns true and sets the value parameter.
Parameters
key The key to get the value for.
value The destination value to set.
Returns
False if the key does not exist.
Definition at line 167 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getDouble(), dodo::persist::sqlite::Statement::reset(), dodo::persist::sqlite::Query::step(), and stmt_getvalue_.
getValue() [3/4]
bool dodo::persist::KVStore::getValue (const std::string & key, int64_t & value) const
If the key exists, returns true and sets the value parameter.
Parameters
key The key to get the value for.
value The destination value to set.
Returns
False if the key does not exist.
Definition at line 178 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getInt64(), dodo::persist::sqlite::Statement::reset(), dodo::persist::sqlite::Query::step(), and stmt_getvalue_.
getValue() [4/4]
bool dodo::persist::KVStore::getValue (const std::string & key, std::string & value) const
If the key exists, returns true and sets the value parameter.
Parameters
key The key to get the value for.
value The destination value to set.
Returns
False if the key does not exist.
Definition at line 156 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::Query::getText(), dodo::persist::sqlite::Statement::reset(), dodo::persist::sqlite::Query::step(), and stmt_getvalue_.
Referenced by ensureWithDefault().
insertKey() [1/4]
bool dodo::persist::KVStore::insertKey (const std::string & key, const common::Bytes & value)
Insert a (key, Bytes) pair.
Note that the size of the data cannot exceed INT_MAX, and exception is thrown if the Bytes is larger.
Parameters
key The key.
oa The Bytes to insert.
Returns
True if the key was created, false if the key already exists.
Definition at line 226 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_insert_.
insertKey() [2/4]
bool dodo::persist::KVStore::insertKey (const std::string & key, const double & value)
Insert a (key, double) pair.
Parameters
key The key.
value The double value to set.
Returns
True if the key was created, false if the key already exists.
Definition at line 208 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_insert_.
insertKey() [3/4]
bool dodo::persist::KVStore::insertKey (const std::string & key, const int64_t & value)
Insert a (key, int64_t) pair.
Parameters
key The key.
value The int64_t value to set.
Returns
True if the key was created, false if the key already exists.
Definition at line 217 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_insert_.
insertKey() [4/4]
bool dodo::persist::KVStore::insertKey (const std::string & key, const std::string & value)
Insert a (key, string) pair.
Parameters
key The key.
value The string value to set.
Returns
True if the key was created, false if the key already exists.
Definition at line 200 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_insert_.
Referenced by ensureWithDefault().
optimize()
void dodo::persist::KVStore::optimize ()
Optimzime, preferably called after workload and implicitly called by the destructor.
Definition at line 235 of file kvstore.cpp.
References dodo::persist::sqlite::DDL::execute(), and dodo::persist::sqlite::Statement::prepare().
Referenced by ~KVStore().
prepareSQL()
void dodo::persist::KVStore::prepareSQL () protected
Prepare all SQL statements.
Definition at line 241 of file kvstore.cpp.
References dodo::persist::sqlite::DDL::execute(), dodo::persist::sqlite::Statement::prepare(), stmt_delete_, stmt_getvalue_, stmt_insert_, stmt_key_filter_, stmt_key_value_filter_, stmt_metadata_, and stmt_update_.
Referenced by KVStore().
rollbackTransaction()
void dodo::persist::KVStore::rollbackTransaction ()
Rollback a transaction.
Throws a dodo::common::Exception when no transaction has started.
Definition at line 256 of file kvstore.cpp.
References dodo::persist::sqlite::Database::rollback().
setKey() [1/4]
bool dodo::persist::KVStore::setKey (const std::string & key, const common::Bytes & value)
Set the binary data/Bytes value of an existing key.
The function returns false if the key does not exist.
Parameters
key The key.
value The Bytes to set.
Returns
True if the key exists, in which case it is also updated.
Definition at line 284 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_update_.
setKey() [2/4]
bool dodo::persist::KVStore::setKey (const std::string & key, const double & value)
Set the double value of an existing key.
The function returns false if the key does not exist.
Parameters
key The key.
value The double value to set.
Returns
True if the key exists, in which case it is also updated.
Definition at line 268 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_update_.
setKey() [3/4]
bool dodo::persist::KVStore::setKey (const std::string & key, const int64_t & value)
Set the int64_t value of an existing key.
The function returns false if the key does not exist.
Parameters
key The key.
value The int64_t value to set.
Returns
True if the key exists, in which case it is also updated.
Definition at line 276 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_update_.
setKey() [4/4]
bool dodo::persist::KVStore::setKey (const std::string & key, const std::string & value)
Set the string value of an existing key.
The function returns false if the key does not exist.
Parameters
key The key.
value The string value to set.
Returns
True if the key exists, in which case it is also updated.
Definition at line 260 of file kvstore.cpp.
References dodo::persist::sqlite::DML::bind(), dodo::persist::sqlite::DML::execute(), dodo::persist::sqlite::Statement::reset(), and stmt_update_.
startTransaction()
void dodo::persist::KVStore::startTransaction ()
Start a transaction.
If insertKey or setKey calls are not inside a started transaction, each will commit automatically and indvidually, which is mach (much!) slower for bulk operations.
Definition at line 292 of file kvstore.cpp.
References dodo::persist::sqlite::DDL::execute(), and dodo::persist::sqlite::Statement::prepare().
vacuum()
void dodo::persist::KVStore::vacuum ()
Vaccum - clean and defragment, which may increase efficiency after heavy deletion and/or modification.
Definition at line 298 of file kvstore.cpp.
References dodo::persist::sqlite::DDL::execute(), and dodo::persist::sqlite::Statement::prepare().
Field Documentation
path_
std::filesystem::path dodo::persist::KVStore::path_ protected
The filesystem path to the kvstore.
Definition at line 319 of file kvstore.hpp.
Referenced by KVStore().
stmt_delete_
sqlite::DML* dodo::persist::KVStore::stmt_delete_ protected
Delete key pair statement handle.
Definition at line 332 of file kvstore.hpp.
Referenced by deleteKey(), KVStore(), prepareSQL(), and ~KVStore().
stmt_getvalue_
sqlite::Query* dodo::persist::KVStore::stmt_getvalue_ protected
Get-value-for-key statement handle.
Definition at line 326 of file kvstore.hpp.
Referenced by getValue(), KVStore(), prepareSQL(), and ~KVStore().
stmt_insert_
sqlite::DML* dodo::persist::KVStore::stmt_insert_ protected
Insert key pair statement handle.
Definition at line 329 of file kvstore.hpp.
Referenced by insertKey(), KVStore(), prepareSQL(), and ~KVStore().
stmt_key_filter_
sqlite::Query* dodo::persist::KVStore::stmt_key_filter_ protected
Key filter statement handle.
Definition at line 338 of file kvstore.hpp.
Referenced by filterKeys(), KVStore(), prepareSQL(), and ~KVStore().
stmt_key_value_filter_
sqlite::Query* dodo::persist::KVStore::stmt_key_value_filter_ protected
Key + value filter statement handle.
Definition at line 341 of file kvstore.hpp.
Referenced by KVStore(), prepareSQL(), and ~KVStore().
stmt_metadata_
sqlite::Query* dodo::persist::KVStore::stmt_metadata_ protected
Get metadata statement handle.
Definition at line 344 of file kvstore.hpp.
Referenced by getMetaData(), KVStore(), prepareSQL(), and ~KVStore().
stmt_update_
sqlite::DML* dodo::persist::KVStore::stmt_update_ protected
Update key pair statement handle.
Definition at line 335 of file kvstore.hpp.
Referenced by KVStore(), prepareSQL(), setKey(), and ~KVStore().
The documentation for this class was generated from the following files:
src/include/persist/kvstore/kvstore.hpp
src/lib/persist/kvstore/kvstore.cpp