dodo: dodo::common::Exception Class Reference
dodo::common::Exception Class Reference
An Exception is thrown in exceptional circumstances, and its occurrence should generally imply that the program should stop, as it has entered a state it was never designed to handle.
#include <exception.hpp>
Public Member Functions
Exception (const std::string &file, unsigned int line, const std::string &what)
Construct an Exception.
Exception (const std::string &file, unsigned int line, const std::string &what, const DebugObject *thing)
Construct an Exception.
const std::string & getFile () const
Return the source file where the exception was thrown.
unsigned int getLine () const
Return the line number in the source file where the exception was thrown.
virtual const char * what () const noexcept
Return the exception message.
Protected Attributes
std::string file_
The source file.
unsigned int line_
The source line number.
std::string msg_
The exception message.
Detailed Description
An Exception is thrown in exceptional circumstances, and its occurrence should generally imply that the program should stop, as it has entered a state it was never designed to handle.
When used in conjunction with the throw_Exception() and throw_SystemException() macros, the source file and line number where the Exception is thrown are picked up automatically.
Definition at line 83 of file exception.hpp.
Constructor & Destructor Documentation
Exception() [1/2]
dodo::common::Exception::Exception (const std::string & file, unsigned int line, const std::string & what)
Construct an Exception.
Use the throw_Exception() macro to construct and throw Exceptions.
Parameters
file The source file where the exception was raised.
line The line number where the exception was raised.
what The exception message.
Definition at line 55 of file exception.cpp.
References file_, line_, msg_, and what().
Exception() [2/2]
dodo::common::Exception::Exception (const std::string & file, unsigned int line, const std::string & what, const DebugObject * thing)
Construct an Exception.
Use the throw_ExceptionObject() macro to construct and throw Exceptions.
Parameters
file The source file where the exception was raised.
line The line number where the exception was raised.
what The exception message.
thing The exception context.
Definition at line 62 of file exception.cpp.
References dodo::common::DebugObject::debugString(), file_, line_, msg_, and what().
Member Function Documentation
getFile()
const std::string& dodo::common::Exception::getFile () const inline
Return the source file where the exception was thrown.
Returns
The source file where the exception was thrown.
Definition at line 118 of file exception.hpp.
References file_.
getLine()
unsigned int dodo::common::Exception::getLine () const inline
Return the line number in the source file where the exception was thrown.
Returns
The line number in the source file where the exception was thrown.
Definition at line 124 of file exception.hpp.
References line_.
what()
const char * dodo::common::Exception::what () const virtual noexcept
Return the exception message.
Returns
the exception message.
Definition at line 73 of file exception.cpp.
References msg_.
Referenced by Exception(), and dodo::network::TCPListener::run().
Field Documentation
file_
std::string dodo::common::Exception::file_ protected
The source file.
Definition at line 124 of file exception.hpp.
Referenced by Exception(), and getFile().
line_
unsigned int dodo::common::Exception::line_ protected
The source line number.
Definition at line 129 of file exception.hpp.
Referenced by Exception(), and getLine().
msg_
std::string dodo::common::Exception::msg_ protected
The exception message.
Definition at line 131 of file exception.hpp.
Referenced by Exception(), and what().
The documentation for this class was generated from the following files:
src/include/common/exception.hpp
src/lib/common/exception.cpp