dodo: dodo::network::TCPServer Class Reference
dodo::network::TCPServer Class Reference abstract
Used in conjunction with TCPListener to implement high speed, multithreaded TCP services.
#include <tcpserver.hpp>
Public Types
enum ServerState {
ssWait = 0, ssAwoken = 1, ssHandshake = 2, ssHandshakeDone = 3,
ssReadSocket = 4, ssReadSocketDone = 5, ssShutdown = 6, ssShutdownDone = 7,
ssReleaseWork = 8, ssReleaseWorkDone = 9
}
The possible states of a TCPServer.
Public Member Functions
TCPServer (TCPListener &listener)
Construct a TCPServer for the TCPListener.
virtual TCPServer * addServer ()=0
Spawn a new TCPServer.
double getIdleSeconds ()
Get the number of secodns the TCPServer has been idle.
bool getRequestStop () const
Return true if the TCPServer was requested to stop.
ServerState getState () const
Return the current ServerState.
virtual bool handShake (network::BaseSocket *socket, ssize_t &received, ssize_t &sent)=0
Override to perform a protocol handshake.
bool hasStopped () const
Return true if the TCPServer has stopped working.
bool isBusy () const
Return true if the TCPServer is busy.
virtual TCPConnectionData * newConnectionData () const
Return a new TCPConnectionData pointer or override to return a descendant of TCPConnectionData.
virtual common::SystemError readSocket (TCPListener::SocketWork &work, ssize_t &sent)=0
Override to perform a request-response cycle.
void requestStop ()
Set the request_stop_ flag, this call returns immediately, stopping will follow.
virtual void run ()
Run the TCPServer thread.
virtual void shutDown (network::BaseSocket *socket)=0
Override to perform a shutdown.
Public Member Functions inherited from dodo::threads::Thread
Thread ()
Constructor.
virtual ~Thread ()
Destructor.
double getAvgBlkInRate ()
Get the average block in rate since thread start()
double getAvgBlkOutRate ()
Get the average block out rate since thread start()
double getAvgICtx ()
Get the average involuntary context switch rate since thread start()
double getAvgMajFltRate ()
Get the average major fault rate since thread start()
double getAvgMinFltRate ()
Get the average minor fault rate since thread start()
double getAvgSysCPU ()
Get the average system mode cpu (cpu seconds/second) since thread start()
double getAvgUserCPU ()
Get the average user mode cpu (cpu seconds/second) since thread start()
double getAvgVCtx ()
Get the average voluntary context switch rate since thread start()
std::thread::id getId () const
Get the thread id.
double getLastBlkInRate ()
Get last block in rate since last sample.
double getLastBlkOutRate ()
Get last block out rate since last sample.
double getLastICtx ()
Get involuntary context switch rate since last sample.
double getLastMajFltRate ()
Get the major fault rate since last sample.
double getLastMinFltRate ()
Get the minor fault rate since last sample.
double getLastSysCPU ()
Get the system mode cpu (cpu seconds/second) since last sample.
double getLastUserCPU ()
Get the user mode cpu (cpu seconds/second) since last sample.
double getLastVCtx ()
Get voluntary context switch rate since last sample.
long getMaxRSS ()
Get the maximum resident set size seen on the thread.
double getRunTime ()
Time, in seconds, since thread start.
double getSnapDiffTime ()
Time, in seconds, since last statistic update.
pid_t getTID () const
Return the tid.
void snapRUsage ()
Take a snapshot of the thread's resource usage.
void start ()
Start the thread.
void wait ()
Wait for the thread to join the current thread / wait for the thread to finish.
Protected Attributes
bool busy_
If true, the TCPServer is processing a request.
bool has_stopped_
If true, the TCPServer has stopped.
struct timeval last_active_
Time of last request handling.
TCPListener & listener_
The TCPListener the TCPServer is working for.
bool request_stop_
If true, the TCPServer should stop.
ServerState state_
State of the TCPServer.
Protected Attributes inherited from dodo::threads::Thread
struct rusage prev_rusage_
Previous statistics.
struct timeval prev_snap_time_
Time of previous statistics snapshot.
struct rusage rusage_
Last statistics.
struct timeval snap_time_
Time of last statistics snapshot.
struct timeval start_time_
Time Thread started.
std::thread * thread_
The std::tread object.
Additional Inherited Members
Detailed Description
Used in conjunction with TCPListener to implement high speed, multithreaded TCP services.
Subclass TCPServer and implement virtual
bool handShake(network::BaseSocket*, ssize_t&, ssize_t&)
bool readSocket(TCPListener::SocketWork &work, ssize_t &sent)
void shutDown(BaseSocket*)
TCPServer* addServer()
Each TCPServer is a thread that consumes work from the TCPListener. There can be multiple TCPServer threads consuming work together, and the TCPListener auto-scales TCPServers depending on the load.
A TCPServer is tied to a TCPListener, The TCPListener produces work to the pool of TCPServer, either
new sockets.
readable sockets (incoming data present).
shutdown sockets (The TCPListener is informing the pool of TCPServer objects the BaseSocket will disappear).
At any given moment, each TCPServer is in one of the TCPServer::ServerState states.
See also
TCPListener
Definition at line 56 of file tcpserver.hpp.
Member Enumeration Documentation
ServerState
enum dodo::network::TCPServer::ServerState
The possible states of a TCPServer.
See also
getState()
Enumerator
ssWait
The TCPServer has entered waiting for activity or wait timeout.
ssAwoken
The TCPServer has woken up from a wait either due to an event or the wait timing out.
ssHandshake
The TCPServer is about to invoke handShake(BaseSocket*).
ssHandshakeDone
ssHandshake completed.
ssReadSocket
The TCPServer is about to invoke readSocket(BaseSocket*).
ssReadSocketDone
ssReadSocket completed.
ssShutdown
The TCPServer is about to invoke shutdown(BaseSocket*).
ssShutdownDone
ssShutdown completed.
ssReleaseWork
The TCPServer is releasing the request.
ssReleaseWorkDone
ssReleaseWork completed.
Definition at line 63 of file tcpserver.hpp.
Constructor & Destructor Documentation
TCPServer()
dodo::network::TCPServer::TCPServer (TCPListener & listener)
Construct a TCPServer for the TCPListener.
Parameters
listener TCPListener.
Definition at line 36 of file tcpserver.cpp.
References last_active_.
Member Function Documentation
addServer()
virtual TCPServer* dodo::network::TCPServer::addServer () pure virtual
Spawn a new TCPServer.
Returns
a pointer to a new TCPServer
Referenced by dodo::network::TCPListener::addServers(), dodo::network::TCPListener::cleanStoppedServers(), and dodo::network::TCPListener::run().
getIdleSeconds()
double dodo::network::TCPServer::getIdleSeconds ()
Get the number of secodns the TCPServer has been idle.
Returns
The idle seconds.
Definition at line 183 of file tcpserver.cpp.
References dodo::common::getSecondDiff(), and last_active_.
getRequestStop()
bool dodo::network::TCPServer::getRequestStop () const inline
Return true if the TCPServer was requested to stop.
Returns
true if the TCPServer was requested to stop.
Definition at line 158 of file tcpserver.hpp.
References request_stop_.
getState()
ServerState dodo::network::TCPServer::getState () const inline
Return the current ServerState.
Returns
The current ServerState.
Definition at line 164 of file tcpserver.hpp.
handShake()
virtual bool dodo::network::TCPServer::handShake (network::BaseSocket * socket, ssize_t & received, ssize_t & sent) pure virtual
Override to perform a protocol handshake.
Note that the TCP handshake has already taken place, and handShake() will only be called for new sockets.
Parameters
socket A pointer to the socket to handshake. If this returns false,. the socket will be closed.
received The number of bytes received by the call.
sent The number of bytes sent by the call.
Returns
true if the handshake succeeded.
Referenced by run().
hasStopped()
bool dodo::network::TCPServer::hasStopped () const inline
Return true if the TCPServer has stopped working.
Returns
True if the TCPServer has stopped on request.
Definition at line 135 of file tcpserver.hpp.
References has_stopped_.
Referenced by dodo::network::TCPListener::cleanStoppedServers().
isBusy()
bool dodo::network::TCPServer::isBusy () const inline
Return true if the TCPServer is busy.
Returns
True if busy.
Definition at line 141 of file tcpserver.hpp.
References busy_.
newConnectionData()
virtual TCPConnectionData* dodo::network::TCPServer::newConnectionData () const inline virtual
Return a new TCPConnectionData pointer or override to return a descendant of TCPConnectionData.
Returns
the new TCPConnectionData*.
Definition at line 129 of file tcpserver.hpp.
Referenced by dodo::network::TCPListener::run().
readSocket()
virtual common::SystemError dodo::network::TCPServer::readSocket (TCPListener::SocketWork & work, ssize_t & sent) pure virtual
Override to perform a request-response cycle.
Parameters
work The work to perform.
sent The number of bytes sent by the call.
Returns
common::SystemError::ecOK if all is well, the request is received completely, it is handled and a response is sent.
common::SystemError::ecEAGAIN if all is well but the data in work.data is not a complete request yet.
common::SystemError::ecECONNABORTED if the socket needs to be closed (for example by client request).
Referenced by run().
requestStop()
void dodo::network::TCPServer::requestStop () inline
Set the request_stop_ flag, this call returns immediately, stopping will follow.
Definition at line 152 of file tcpserver.hpp.
References request_stop_.
run()
void dodo::network::TCPServer::run () virtual
Run the TCPServer thread.
Returns
void
Implements dodo::threads::Thread.
Definition at line 44 of file tcpserver.cpp.
References dodo::network::TCPListener::addReceivedSentBytes(), dodo::network::Address::asString(), busy_, dodo::network::TCPListener::SocketWork::data, dodo::common::DebugObject::debugString(), dodo::common::SystemError::ecEAGAIN, dodo::common::SystemError::ecECONNABORTED, dodo::common::SystemError::ecOK, dodo::network::BaseSocket::getFD(), dodo::network::BaseSocket::getPeerAddress(), dodo::common::getSecondDiff(), handShake(), has_stopped_, last_active_, listener_, log_Debug, log_Error, log_Fatal, dodo::network::TCPListener::New, dodo::network::TCPListener::None, dodo::network::TCPListener::popWork(), dodo::network::TCPListener::Read, dodo::network::TCPConnectionData::readBuffer(), readSocket(), dodo::network::TCPListener::releaseWork(), request_stop_, dodo::network::TCPListener::Shut, shutDown(), dodo::threads::Thread::snapRUsage(), dodo::network::TCPListener::SocketWork::socket, ssAwoken, ssHandshake, ssHandshakeDone, ssReadSocket, ssReadSocketDone, ssReleaseWork, ssReleaseWorkDone, ssShutdown, ssShutdownDone, ssWait, dodo::network::TCPListener::SocketWork::state, state_, and dodo::network::TCPListener::waitForActivity().
shutDown()
virtual void dodo::network::TCPServer::shutDown (network::BaseSocket * socket) pure virtual
Override to perform a shutdown.
Parameters
socket The socket to work on.
Returns
void
Referenced by run().
Field Documentation
busy_
bool dodo::network::TCPServer::busy_ protected
If true, the TCPServer is processing a request.
Definition at line 186 of file tcpserver.hpp.
Referenced by isBusy(), and run().
has_stopped_
bool dodo::network::TCPServer::has_stopped_ protected
If true, the TCPServer has stopped.
Definition at line 181 of file tcpserver.hpp.
Referenced by hasStopped(), and run().
last_active_
struct timeval dodo::network::TCPServer::last_active_ protected
Time of last request handling.
Definition at line 191 of file tcpserver.hpp.
Referenced by getIdleSeconds(), run(), and TCPServer().
listener_
TCPListener& dodo::network::TCPServer::listener_ protected
The TCPListener the TCPServer is working for.
Definition at line 164 of file tcpserver.hpp.
Referenced by run().
request_stop_
bool dodo::network::TCPServer::request_stop_ protected
If true, the TCPServer should stop.
Definition at line 176 of file tcpserver.hpp.
Referenced by getRequestStop(), requestStop(), and run().
state_
ServerState dodo::network::TCPServer::state_ protected
State of the TCPServer.
Definition at line 196 of file tcpserver.hpp.
Referenced by run().
The documentation for this class was generated from the following files:
src/include/network/tcpserver.hpp
src/lib/network/tcpserver.cpp