dodo: dodo Namespace Reference
dodo Namespace Reference
A C++ platform interface to lean linux services tailored for containerized deployment.
Namespaces
common
Common and utility interfaces.
network
Interface for network communication.
store
Interface to persistent storage.
threads
Interface for Thread programming.
Data Structures
class BuildEnv
Build information, generated by cmake during builds from buildenv.hpp.in.
Functions
void closeLibrary ()
Close the dodo library.
void initLibrary ()
Initialize the dodo library.
Detailed Description
A C++ platform interface to lean linux services tailored for containerized deployment.
Function Documentation
closeLibrary()
void dodo::closeLibrary ()
Close the dodo library.
See also
dodo::common::Application
Definition at line 51 of file dodo.hpp.
References dodo::threads::closeLibrary(), dodo::common::closeLibrary(), and dodo::network::closeLibrary().
initLibrary()
void dodo::initLibrary ()
Initialize the dodo library.
See also
dodo::common::Application
Definition at line 41 of file dodo.hpp.
References dodo::threads::initLibrary(), dodo::network::initLibrary(), and dodo::common::initLibrary().
Referenced by dodo::common::Application::Application().