dodo: dodo::common Namespace Reference
dodo::common Namespace Reference
Common and utility interfaces.
Data Structures
class Application
Red tape wrapper class for applications, from command line to services.
class Config
Singleton class representing the deployment configuration, combining deployment constants from the configuration file, environment variables (whose names start with the appname) and some operating system quantities useful to developers, like the CPU count or an imposed memory limit.
class DataCrypt
Interface to encrypt and decrypt OctetArray data to/from a secure string.
class DebugObject
Interface to objects that support dumping their state to a string.
class Exception
An Exception is thrown in exceptional circumstances, and its occurence should generally imply that the program should stop, as it has entered a state it was never designed to handle.
class Logger
A Logger interface.
struct OctetArray
An array of Octets with size elements.
class Puts
Helper class to write strings in stream format, eg.
class StopWatch
StopWatch timing class.
class SystemError
Linux system error primitive to provide a consistent interface to Linux error codes.
class SystemException
Descending from Exception, exceptions based on a dodo::common::SystemError code.
class UnitTest
Unit test assitence class.
Typedefs
typedef uint8_t Octet
Octet aka 'byte'.
Functions
bool availableFileSpace (const std::string &path, size_t &avail)
Return true when the free space could be determined, and set in avail.
std::string bio2String (BIO *bio)
Convert the data contents of an OpenSSL BIO to a std::string.
void closeLibrary ()
Close the common library.
bool directoryExists (const std::string &path)
Return true when the directory exists.
bool directoryWritable (const std::string &path)
Return true when the directory exists and is writable to the caller.
void dumpBinaryData (std::ostream &out, const std::string &s, size_t width)
Dump binary data to a std::ostream.
std::vector< std::string > escapedSplit (const std::string &src, std::set< char > escape, char delimiter=' ')
Split a string into substrings by delimiter - unless the delimiter is escaped.
bool fileReadAccess (const std::string &path)
Return true when the file exists and the calling user has read access.
bool fileReadInt (const std::string &file, int &i)
Read from a file, expecting it to contain a (signed) int.
std::string fileReadString (const std::string &filename)
Read the file as a single string.
std::vector< std::string > fileReadStrings (const std::string &filename)
Read the file as vector of strings.
std::vector< std::string > fileReadStrings (const std::string &filename, const std::regex &exp)
Read the file as vector of strings, return only regexp matches.
std::string formatDateTimeUTC (const struct timeval &tv)
Return a datetime string in UTC (2020-07-01T20:14:36.442929Z)
size_t getFileSize (const std::string &path)
Return the size of the file.
double getSecondDiff (struct timeval &t1, struct timeval &t2)
Return difference in seconds as a double.
std::string getSSLErrors (char terminator)
Get all OpenSSL errors as a single string, and clear their error state.
void initLibrary ()
Initialize the common library.
std::vector< std::string > split (const std::string &src, char delimiter=' ')
Split a string into substrings.
std::string strASCII (char c)
Return ASCII representation of char.
size_t writeSSLErrors (std::ostream &out, char terminator)
Write OpenSSL errors occurred in this thread to ostream, and clear their error state.
template<typename T >
T YAML_assign_by_key (const YAML::Node &node, const std::string &key)
Template function to check existence and assign YAML values of arbitrary type.
template bool YAML_assign_by_key< bool > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for bool.
template double YAML_assign_by_key< double > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for double.
template int YAML_assign_by_key< int > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for int.
template long YAML_assign_by_key< long > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for long.
template size_t YAML_assign_by_key< size_t > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for size_t.
template std::string YAML_assign_by_key< std::string > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for std::string.
template uint16_t YAML_assign_by_key< uint16_t > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for uint16_t.
template unsigned int YAML_assign_by_key< unsigned int > (const YAML::Node &, const std::string &)
Instantiate template YAML_assign_by_key for unsigned int.
template<typename T >
T YAML_assign_by_key_with_default (const YAML::Node &node, const std::string &key, const T &default_value)
Template function to check existence and assign YAML values of arbitrary type.
template bool YAML_assign_by_key_with_default< bool > (const YAML::Node &, const std::string &, const bool &)
Instantiate template YAML_assign_by_key for bool.
template double YAML_assign_by_key_with_default< double > (const YAML::Node &, const std::string &, const double &)
Instantiate template YAML_assign_by_key for double.
template int YAML_assign_by_key_with_default< int > (const YAML::Node &, const std::string &, const int &)
Instantiate template YAML_assign_by_key for int.
template long YAML_assign_by_key_with_default< long > (const YAML::Node &, const std::string &, const long &)
Instantiate template YAML_assign_by_key for long.
template size_t YAML_assign_by_key_with_default< size_t > (const YAML::Node &, const std::string &, const size_t &)
Instantiate template YAML_assign_by_key for size_t.
template std::string YAML_assign_by_key_with_default< std::string > (const YAML::Node &, const std::string &, const std::string &)
Instantiate template YAML_assign_by_key for std::string.
template unsigned int YAML_assign_by_key_with_default< unsigned int > (const YAML::Node &, const std::string &, const unsigned int &)
Instantiate template YAML_assign_by_key for unsigned int.
Detailed Description
Common and utility interfaces.
Typedef Documentation
Octet
typedef uint8_t dodo::common::Octet
Octet aka 'byte'.
Definition at line 33 of file octetarray.hpp.
Function Documentation
availableFileSpace()
bool dodo::common::availableFileSpace (const std::string & path, size_t & avail)
Return true when the free space could be determined, and set in avail.
Parameters
path The path on which to check.
avail The available free space.
Returns
False if the free space could not be determined (for example, when the file does not exist).
Definition at line 226 of file util.cpp.
bio2String()
std::string dodo::common::bio2String (BIO * bio)
Convert the data contents of an OpenSSL BIO to a std::string.
Parameters
bio The source BIO.
Returns
The string representation of the BIO contents.
Definition at line 132 of file util.cpp.
Referenced by dodo::network::X509Certificate::getIssuer(), dodo::network::X509CertificateSigningRequest::getSubject(), and dodo::network::X509Certificate::getSubject().
closeLibrary()
void dodo::common::closeLibrary ()
Close the common library.
Definition at line 57 of file common.hpp.
Referenced by dodo::closeLibrary().
directoryExists()
bool dodo::common::directoryExists (const std::string & path)
Return true when the directory exists.
Parameters
path The path to the directory.
Returns
True when the directory exists.
Definition at line 207 of file util.cpp.
Referenced by dodo::common::Logger::getFileParams().
directoryWritable()
bool dodo::common::directoryWritable (const std::string & path)
Return true when the directory exists and is writable to the caller.
Parameters
path The path to the directory.
Returns
True when the directory exists and is writable to the caller.
Definition at line 216 of file util.cpp.
Referenced by dodo::common::Logger::getFileParams().
dumpBinaryData()
void dodo::common::dumpBinaryData (std::ostream & out, const std::string & s, size_t width)
Dump binary data to a std::ostream.
Parameters
out The std::stream to dump to.
s The char stream.
width The max character width of the output.
Definition at line 105 of file util.cpp.
References strASCII().
escapedSplit()
std::vector<std::string> dodo::common::escapedSplit (const std::string & src, std::set< char > escape, char delimiter = ' ') inline
Split a string into substrings by delimiter - unless the delimiter is escaped.
Passing ('one:two$:three', '$', ':') splits into ['one','two:three']. Passing ('one:t
$wo
hree', '
', ':') splits into ['one','t$$wo','three']. So the escape character only has effect when followed by a delimiter, otherwise taken as input.
Parameters
src The string to split from.
escape The escape characters to use
delimiter The delimiter to use.
Returns
A vector of strings.
Definition at line 150 of file util.hpp.
Referenced by dodo::network::X509Common::parseIdentity().
fileReadAccess()
bool dodo::common::fileReadAccess (const std::string & path)
Return true when the file exists and the calling user has read access.
Parameters
path The path to the file.
Returns
True when the file exists and can be read.
Definition at line 197 of file util.cpp.
Referenced by dodo::common::Application::detectHostType().
fileReadInt()
bool dodo::common::fileReadInt (const std::string & file, int & i)
Read from a file, expecting it to contain a (signed) int.
Parameters
file The file name.
i The int read.
Returns
False if the read or conversion failed.
Definition at line 39 of file util.cpp.
Referenced by dodo::network::TCPListener::construct().
fileReadString()
std::string dodo::common::fileReadString (const std::string & filename)
Read the file as a single string.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
Returns
the file contents as a string.
Definition at line 161 of file util.cpp.
References throw_Exception.
fileReadStrings() [1/2]
std::vector< std::string > dodo::common::fileReadStrings (const std::string & filename)
Read the file as vector of strings.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
Returns
the file as a vector of strings
Definition at line 170 of file util.cpp.
References throw_Exception.
Referenced by dodo::common::Application::detectHostType().
fileReadStrings() [2/2]
std::vector< std::string > dodo::common::fileReadStrings (const std::string & filename, const std::regex & exp)
Read the file as vector of strings, return only regexp matches.
Exceptions
Oops when the file cannot be read.
Parameters
filename the file to read from.
exp the regex that must match.
Returns
the file as a vector of strings.
Definition at line 183 of file util.cpp.
References throw_Exception.
formatDateTimeUTC()
std::string dodo::common::formatDateTimeUTC (const struct timeval & tv)
Return a datetime string in UTC (2020-07-01T20:14:36.442929Z)
Parameters
tv The tv time struct.
Returns
The formatted datetime.
Definition at line 239 of file util.cpp.
Referenced by dodo::common::Logger::checkRotate(), and dodo::common::Logger::formatMessage().
getFileSize()
size_t dodo::common::getFileSize (const std::string & path)
Return the size of the file.
If the file does not exist or is otherwise inaccessible, returns 0.
Parameters
path The path of the file.
Returns
The file size
Definition at line 233 of file util.cpp.
Referenced by dodo::common::Logger::checkRotate(), dodo::common::Logger::getFileParams(), and dodo::store::kvstore::KVStore::open().
getSecondDiff()
double dodo::common::getSecondDiff (struct timeval & t1, struct timeval & t2) inline
Return difference in seconds as a double.
t2 must be > t1 for the return value to be positive.
Parameters
t1 The earlier time.
t2 The later time.
Returns
the difference in seconds from t1 to t2.
Definition at line 119 of file util.hpp.
Referenced by dodo::network::TCPServer::getIdleSeconds(), dodo::threads::Thread::getRunTime(), dodo::threads::Thread::getSnapDiffTime(), dodo::network::TCPListener::logStats(), and dodo::network::TCPServer::run().
getSSLErrors()
std::string dodo::common::getSSLErrors (char terminator)
Get all OpenSSL errors as a single string, and clear their error state.
Parameters
terminator The terminator character for a single error line. If 0, no character will be appended.
Returns
The string.
See also
writeSSLErrors(ostream& out)
Definition at line 154 of file util.cpp.
References writeSSLErrors().
Referenced by dodo::network::TLSSocket::accept(), dodo::network::TLSSocket::connect(), dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), dodo::network::X509CertificateSigningRequest::getFingerPrint(), dodo::network::X509Certificate::getFingerPrint(), dodo::network::X509CertificateSigningRequest::loadPEM(), dodo::network::X509Certificate::loadPEM(), dodo::network::TLSContext::loadPEMIdentity(), dodo::network::TLSContext::loadPKCS12(), dodo::network::TLSSocket::receive(), dodo::network::TLSSocket::send(), dodo::network::TLSContext::setTrustPaths(), dodo::network::TLSContext::TLSContext(), and dodo::network::TLSSocket::TLSSocket().
initLibrary()
void dodo::common::initLibrary ()
Initialize the common library.
Definition at line 47 of file common.hpp.
References throw_Exception.
Referenced by dodo::initLibrary().
split()
std::vector<std::string> dodo::common::split (const std::string & src, char delimiter = ' ') inline
Split a string into substrings.
Parameters
src The string to split from.
delimiter The delimiter to use.
Returns
A vector of strings.
Definition at line 129 of file util.hpp.
Referenced by dodo::common::DataCrypt::decode(), and dodo::network::X509Common::parseIdentity().
strASCII()
std::string dodo::common::strASCII (char c)
Return ASCII representation of char.
Parameters
c The char.
Returns
the ASCII representation.
Definition at line 50 of file util.cpp.
Referenced by dumpBinaryData().
writeSSLErrors()
size_t dodo::common::writeSSLErrors (std::ostream & out, char terminator)
Write OpenSSL errors occurred in this thread to ostream, and clear their error state.
Parameters
out The std::ostream to write to.
terminator The char to use to separate lines.
Returns
The number of SSL errors written.
Definition at line 140 of file util.cpp.
Referenced by getSSLErrors().
YAML_assign_by_key()
template<typename T > T dodo::common::YAML_assign_by_key (const YAML::Node & node, const std::string & key)
Template function to check existence and assign YAML values of arbitrary type.
The key-value pair must must exist under node.
Parameters
node The YAML::Node containing the key-value pair
key The YAML::Node name.
Returns
the value of type T
Definition at line 253 of file util.cpp.
References throw_Exception.
YAML_assign_by_key< bool >()
template bool dodo::common::YAML_assign_by_key< bool > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for bool.
Returns
the value as a bool
YAML_assign_by_key< double >()
template double dodo::common::YAML_assign_by_key< double > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for double.
Returns
the value as a double
YAML_assign_by_key< int >()
template int dodo::common::YAML_assign_by_key< int > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for int.
Returns
the value as an int
YAML_assign_by_key< long >()
template long dodo::common::YAML_assign_by_key< long > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for long.
Returns
the value as a long
YAML_assign_by_key< size_t >()
template size_t dodo::common::YAML_assign_by_key< size_t > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for size_t.
Returns
the value as a size_t
YAML_assign_by_key< std::string >()
template std::string dodo::common::YAML_assign_by_key< std::string > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for std::string.
Returns
the value as a std::string
YAML_assign_by_key< uint16_t >()
template uint16_t dodo::common::YAML_assign_by_key< uint16_t > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for uint16_t.
Returns
the value as a uint16_t
Referenced by dodo::network::TCPListener::TCPListener().
YAML_assign_by_key< unsigned int >()
template unsigned int dodo::common::YAML_assign_by_key< unsigned int > (const YAML::Node & , const std::string &)
Instantiate template YAML_assign_by_key for unsigned int.
Returns
the value as an unsigned int
YAML_assign_by_key_with_default()
template<typename T > T dodo::common::YAML_assign_by_key_with_default (const YAML::Node & node, const std::string & key, const T & default_value)
Template function to check existence and assign YAML values of arbitrary type.
The key-value pair must must exist under node.
Parameters
node The YAML::Node containing the key-value pair
key The YAML::Node name.
default_value The default value to assign when the key is missing
Returns
the value of type T
Definition at line 308 of file util.cpp.
YAML_assign_by_key_with_default< bool >()
template bool dodo::common::YAML_assign_by_key_with_default< bool > (const YAML::Node & , const std::string & , const bool &)
Instantiate template YAML_assign_by_key for bool.
Returns
the value as a bool
Referenced by dodo::network::TCPListener::Params::Params().
YAML_assign_by_key_with_default< double >()
template double dodo::common::YAML_assign_by_key_with_default< double > (const YAML::Node & , const std::string & , const double &)
Instantiate template YAML_assign_by_key for double.
Returns
the value as a double
Referenced by dodo::network::TCPListener::Params::Params().
YAML_assign_by_key_with_default< int >()
template int dodo::common::YAML_assign_by_key_with_default< int > (const YAML::Node & , const std::string & , const int &)
Instantiate template YAML_assign_by_key for int.
Returns
the value as an int
Referenced by dodo::network::TCPListener::Params::Params().
YAML_assign_by_key_with_default< long >()
template long dodo::common::YAML_assign_by_key_with_default< long > (const YAML::Node & , const std::string & , const long &)
Instantiate template YAML_assign_by_key for long.
Returns
the value as a long
YAML_assign_by_key_with_default< size_t >()
template size_t dodo::common::YAML_assign_by_key_with_default< size_t > (const YAML::Node & , const std::string & , const size_t &)
Instantiate template YAML_assign_by_key for size_t.
Returns
the value as a size_t
Referenced by dodo::network::TCPListener::Params::Params().
YAML_assign_by_key_with_default< std::string >()
template std::string dodo::common::YAML_assign_by_key_with_default< std::string > (const YAML::Node & , const std::string & , const std::string &)
Instantiate template YAML_assign_by_key for std::string.
Returns
the value as a std::string
YAML_assign_by_key_with_default< unsigned int >()
template unsigned int dodo::common::YAML_assign_by_key_with_default< unsigned int > (const YAML::Node & , const std::string & , const unsigned int &)
Instantiate template YAML_assign_by_key for unsigned int.
Returns
the value as an unsigned int