dodo: dodo::network::protocol::http::HTTPFragment::ParseResult Struct Reference
dodo::network::protocol::http::HTTPFragment::ParseResult Struct Reference
Used to convey parsing succces.
#include <httpfragment.hpp>
Public Member Functions
ParseResult ()
Default constructor sets to { parseError = peOk; systemError = common::SystemError::ecOK; }
ParseResult (ParseError pe, common::SystemError se)
Explicit constructor.
std::string asString () const
Return the ParseResult as a human readable string.
bool eof () const
Test if systemError == common::SystemError::ecEAGAIN
common::SystemError getSystemError () const
Return the systemError.
bool ok () const
Test if parseError == peOk && systemError == common::SystemError::ecOK.
void setSystemError (common::SystemError se)
Set the systemError.
Private Attributes
ParseError parseError
The parse eror.
common::SystemError systemError
The common::SystemError is parseError == peSystemError, undefined otherwise.
Detailed Description
Used to convey parsing succces.
If parseError is peOk, the parse was succesfull. If parseError == peSystemError, systemError will be set to something else then SystemError::ecOK.
Definition at line 75 of file httpfragment.hpp.
Constructor & Destructor Documentation
ParseResult() [1/2]
dodo::network::protocol::http::HTTPFragment::ParseResult::ParseResult () inline
Default constructor sets to { parseError = peOk; systemError = common::SystemError::ecOK; }
Definition at line 80 of file httpfragment.hpp.
References dodo::common::SystemError::ecOK, parseError, dodo::network::protocol::http::HTTPFragment::peOk, and systemError.
ParseResult() [2/2]
dodo::network::protocol::http::HTTPFragment::ParseResult::ParseResult (ParseError pe, common::SystemError se) inline
Explicit constructor.
Parameters
pe The ParseError to set.
se The SystemError to set.
Definition at line 87 of file httpfragment.hpp.
References parseError, and systemError.
Member Function Documentation
asString()
std::string dodo::network::protocol::http::HTTPFragment::ParseResult::asString () const inline
Return the ParseResult as a human readable string.
Returns
The ParseResult as a string.
Definition at line 122 of file httpfragment.hpp.
References dodo::common::SystemError::asString(), dodo::network::protocol::http::HTTPFragment::getParseResultAsString(), parseError, and systemError.
eof()
bool dodo::network::protocol::http::HTTPFragment::ParseResult::eof () const inline
Test if systemError == common::SystemError::ecEAGAIN
Returns
true if there was more data expected.
Definition at line 99 of file httpfragment.hpp.
References dodo::common::SystemError::ecEAGAIN, and systemError.
Referenced by dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::parse(), dodo::network::protocol::http::HTTPMessage::parseChunkedBody(), and dodo::network::protocol::http::HTTPMessage::parseHeaders().
getSystemError()
common::SystemError dodo::network::protocol::http::HTTPFragment::ParseResult::getSystemError () const inline
Return the systemError.
Returns
thesystemError part.
Definition at line 116 of file httpfragment.hpp.
References systemError.
Referenced by dodo::network::protocol::http::HTTPVersion::parse().
ok()
bool dodo::network::protocol::http::HTTPFragment::ParseResult::ok () const inline
Test if parseError == peOk && systemError == common::SystemError::ecOK.
Returns
true when all is well.
Definition at line 93 of file httpfragment.hpp.
References dodo::common::SystemError::ecOK, parseError, dodo::network::protocol::http::HTTPFragment::peOk, and systemError.
Referenced by dodo::network::protocol::http::HTTPMessage::eatCRLF(), dodo::network::protocol::http::HTTPVersion::parse(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), dodo::network::protocol::http::HTTPResponse::parse(), dodo::network::protocol::http::HTTPRequest::parseBody(), dodo::network::protocol::http::HTTPResponse::parseBody(), dodo::network::protocol::http::HTTPMessage::parseChunkedBody(), dodo::network::protocol::http::HTTPMessage::parseChunkHex(), dodo::network::protocol::http::HTTPMessage::parseCRLF(), dodo::network::protocol::http::HTTPMessage::parseFieldValue(), dodo::network::protocol::http::HTTPMessage::parseHeaders(), dodo::network::protocol::http::HTTPMessage::parseToken(), and dodo::network::protocol::http::HTTPMessage::parseUInt().
setSystemError()
void dodo::network::protocol::http::HTTPFragment::ParseResult::setSystemError (common::SystemError se) inline
Set the systemError.
Implictly sets parseError to peOK ig se == common::SystemError::ecOK and to peSystemError if se != common::SystemError::ecOK
Parameters
se The SystemError to set.
Definition at line 106 of file httpfragment.hpp.
References dodo::common::SystemError::ecOK, parseError, dodo::network::protocol::http::HTTPFragment::peOk, dodo::network::protocol::http::HTTPFragment::peSystemError, and systemError.
Referenced by dodo::network::protocol::http::HTTPMessage::eatCRLF(), dodo::network::protocol::http::HTTPVersion::parse(), dodo::network::protocol::http::HTTPRequest::HTTPRequestLine::parse(), dodo::network::protocol::http::HTTPRequest::parse(), dodo::network::protocol::http::HTTPResponse::HTTPResponseLine::parse(), dodo::network::protocol::http::HTTPResponse::parse(), dodo::network::protocol::http::HTTPRequest::parseBody(), dodo::network::protocol::http::HTTPResponse::parseBody(), dodo::network::protocol::http::HTTPMessage::parseChunkedBody(), dodo::network::protocol::http::HTTPMessage::parseChunkHex(), dodo::network::protocol::http::HTTPMessage::parseCRLF(), dodo::network::protocol::http::HTTPMessage::parseFieldValue(), dodo::network::protocol::http::HTTPMessage::parseHeaders(), dodo::network::protocol::http::HTTPMessage::parseToken(), and dodo::network::protocol::http::HTTPMessage::parseUInt().
Field Documentation
parseError
ParseError dodo::network::protocol::http::HTTPFragment::ParseResult::parseError private
The parse eror.
Definition at line 126 of file httpfragment.hpp.
Referenced by asString(), ok(), ParseResult(), and setSystemError().
systemError
common::SystemError dodo::network::protocol::http::HTTPFragment::ParseResult::systemError private
The common::SystemError is parseError == peSystemError, undefined otherwise.
Definition at line 128 of file httpfragment.hpp.
Referenced by asString(), eof(), getSystemError(), ok(), ParseResult(), and setSystemError().
The documentation for this struct was generated from the following file:
src/include/network/protocol/http/httpfragment.hpp