dodo: dodo::common::OctetArray Struct Reference
dodo::common::OctetArray Struct Reference
An array of Octets with size elements.
#include <octetarray.hpp>
Public Types
enum MatchType { Mismatch, Partial, Full }
The way in which two OctetArray instances match.
Public Member Functions
OctetArray ()
Construct an empty OctetArray.
OctetArray (const std::string &s)
Construct and fill from a std::string, not including a NULL terminator (so size will be string.length()).
virtual ~OctetArray ()
Destruct and clean.
void append (const Octet *src, size_t n)
Append from arbitrary memory areas.
void append (const OctetArray &src)
Append another OctetArray.
void append (const OctetArray &src, size_t n)
Append the first n Octets from OctetArray.
void append (Octet src)
Append a single Octet.
std::string asString () const
Cast to a std::string.
OctetArray & decodeBase64 (const std::string &src)
Decodes the base64 string into this OctetArray.
std::string encodeBase64 () const
Encodes the this OctetArray into a base64-encoded string.
void free ()
Free and clear data.
std::string hexDump (size_t n) const
hex dump the first n octets of the data.
MatchType match (const OctetArray &other, size_t index, size_t &octets)
Match this OctetArray from index to the other array (entirely).
OctetArray & operator= (const std::string &s)
Assign from std::string, not including a NULL terminator (so size will be string.length()).
void random (size_t octets)
Generate a random set of Octets.
void reserve (size_t sz)
Reserve memory in the OctetArray.
Data Fields
const size_t alloc_block = 32
Always allocate chunks of this size.
Octet * array
The Octet array.
size_t size
The array size in Octets (using an int as that is what opensssl uses)
Private Attributes
size_t allocated_size
The allocated size, always >= size.
Detailed Description
An array of Octets with size elements.
Provides base64 conversion, random data, and appending of data form other sources. Memory management is implicit, but allocated in chunks of size alloc_block to avoid calling realloc on every size increase.
Definition at line 40 of file octetarray.hpp.
Member Enumeration Documentation
MatchType
enum dodo::common::OctetArray::MatchType strong
The way in which two OctetArray instances match.
Definition at line 114 of file octetarray.hpp.
Constructor & Destructor Documentation
OctetArray() [1/2]
dodo::common::OctetArray::OctetArray () inline
Construct an empty OctetArray.
Definition at line 45 of file octetarray.hpp.
OctetArray() [2/2]
dodo::common::OctetArray::OctetArray (const std::string & s) inline
Construct and fill from a std::string, not including a NULL terminator (so size will be string.length()).
Parameters
s The source string.
Definition at line 51 of file octetarray.hpp.
~OctetArray()
virtual dodo::common::OctetArray::~OctetArray () inline virtual
Destruct and clean.
Definition at line 58 of file octetarray.hpp.
References free().
Member Function Documentation
append() [1/4]
void dodo::common::OctetArray::append (const Octet * src, size_t n)
Append from arbitrary memory areas.
Parameters
src The memory to append from.
n The number of octets to append.
Definition at line 78 of file octetarray.cpp.
References array, reserve(), and size.
append() [2/4]
void dodo::common::OctetArray::append (const OctetArray & src)
Append another OctetArray.
Parameters
src The OctetArray to append.
Definition at line 65 of file octetarray.cpp.
References array, reserve(), and size.
Referenced by dodo::common::DataCrypt::decrypt(), and dodo::network::protocol::stomp::Connect::generate().
append() [3/4]
void dodo::common::OctetArray::append (const OctetArray & src, size_t n)
Append the first n Octets from OctetArray.
Parameters
src The OctetArray to append from.
n The number of octets to append.
Definition at line 71 of file octetarray.cpp.
References array, reserve(), size, and throw_Exception.
append() [4/4]
void dodo::common::OctetArray::append (Octet src)
Append a single Octet.
Parameters
src The Octet to append.
Definition at line 84 of file octetarray.cpp.
References array, reserve(), and size.
asString()
std::string dodo::common::OctetArray::asString () const
Cast to a std::string.
Be aware that the string is read to either the first zero (NULL) or up to size. So if the decoded data contains intermediate zeros the string will not cover all octets.
Returns
A string representation of OctetArray.
Definition at line 98 of file octetarray.cpp.
References array, and size.
decodeBase64()
OctetArray & dodo::common::OctetArray::decodeBase64 (const std::string & src)
Decodes the base64 string into this OctetArray.
Parameters
src The base64-encoded source string.
Returns
A reference to this OctetArray
Definition at line 114 of file octetarray.cpp.
References array, reserve(), and throw_Exception.
Referenced by dodo::common::DataCrypt::decrypt().
encodeBase64()
std::string dodo::common::OctetArray::encodeBase64 () const
Encodes the this OctetArray into a base64-encoded string.
Returns
The base64 encoded data of the OctetArray.
Definition at line 136 of file octetarray.cpp.
References array, size, and throw_Exception.
Referenced by dodo::common::DataCrypt::encrypt().
free()
void dodo::common::OctetArray::free ()
Free and clear data.
Definition at line 56 of file octetarray.cpp.
References allocated_size, array, and size.
Referenced by dodo::network::protocol::stomp::Connect::generate(), and ~OctetArray().
hexDump()
std::string dodo::common::OctetArray::hexDump (size_t n) const
hex dump the first n octets of the data.
Parameters
n The number of octets to dump.
Returns
a string with hex numbers.
Definition at line 180 of file octetarray.cpp.
References array, and size.
Referenced by dodo::network::TCPConnectionData::readBuffer().
match()
OctetArray::MatchType dodo::common::OctetArray::match (const OctetArray & other, size_t index, size_t & octets)
Match this OctetArray from index to the other array (entirely).
Parameters
other The other OctetArray.
index The start index into the local array to match from.
octets The number of Octets in this array that match.
Returns
Mismatch : The local array does not match the other array.
Partial : The local array matches the other array, but the other array is larger.
Full : The other array matches (contains) the local array completely, although the local array may have more octets.
Definition at line 162 of file octetarray.cpp.
References array, and size.
operator=()
OctetArray & dodo::common::OctetArray::operator= (const std::string & s)
Assign from std::string, not including a NULL terminator (so size will be string.length()).
Parameters
s The base64 string to assign from.
Returns
This OctetArray.
Definition at line 89 of file octetarray.cpp.
References array, and reserve().
random()
void dodo::common::OctetArray::random (size_t octets)
Generate a random set of Octets.
Parameters
octets The number of random Octets.
Definition at line 106 of file octetarray.cpp.
References array, reserve(), and size.
Referenced by dodo::common::DataCrypt::encrypt().
reserve()
void dodo::common::OctetArray::reserve (size_t sz)
Reserve memory in the OctetArray.
Parameters
sz The size in bytes to alloc .
Definition at line 33 of file octetarray.cpp.
References alloc_block, allocated_size, array, size, and throw_SystemException.
Referenced by append(), decodeBase64(), dodo::common::DataCrypt::decrypt(), dodo::common::DataCrypt::encrypt(), operator=(), random(), and dodo::network::TCPConnectionData::readBuffer().
Field Documentation
alloc_block
const size_t dodo::common::OctetArray::alloc_block = 32
Always allocate chunks of this size.
Any OctetArray that has been called with reserve(n > 1) will at least allocate 1 chunk of alloc_block bytes. Avoids frequent calls to realloc when using many append calls with small amount of data such as append(Octet).
Definition at line 177 of file octetarray.hpp.
Referenced by reserve().
allocated_size
size_t dodo::common::OctetArray::allocated_size private
The allocated size, always >= size.
Definition at line 183 of file octetarray.hpp.
Referenced by free(), and reserve().
array
Octet* dodo::common::OctetArray::array
The Octet array.
Definition at line 63 of file octetarray.hpp.
Referenced by append(), asString(), decodeBase64(), dodo::common::DataCrypt::decrypt(), encodeBase64(), dodo::common::DataCrypt::encrypt(), free(), hexDump(), match(), operator=(), random(), dodo::network::TCPConnectionData::readBuffer(), dodo::network::protocol::stomp::Frame::readCommand(), and reserve().
size
size_t dodo::common::OctetArray::size
The array size in Octets (using an int as that is what opensssl uses)
Definition at line 68 of file octetarray.hpp.
Referenced by append(), asString(), dodo::common::DataCrypt::decrypt(), encodeBase64(), dodo::common::DataCrypt::encrypt(), free(), hexDump(), match(), random(), dodo::network::TCPConnectionData::readBuffer(), dodo::network::protocol::stomp::Frame::readCommand(), and reserve().
The documentation for this struct was generated from the following files:
src/include/common/octetarray.hpp
src/lib/common/octetarray.cpp