dodo:
  common:
    application:
      name: dodo-service
    logger:
      console:
        level: debug
      file:
        level: info
        directory: log
        max-size-mib: 1
        max-file-trail: 4
      syslog:
        level: warning
        facility: 16