dodo:
  common:
    application:
      name: dodo-service
      key:
        source: file
        path: /run/secrets/dodo-service-key

    logger:
      console:
        level: trace
      file:
        level: info
        directory: log
        max-size-mib: 1
        max-file-trail: 4
      syslog:
        level: info
        facility: 1

server:
  listen-address: 0.0.0.0
  listen-port: 1968
  min-servers: 2
  max-servers: 8
  max-connections: 500
  send-buffer: 16384
  receive-buffer: 32768
  send-timeout-seconds: 10
  receive-timeout-seconds: 10
  stat-trc-interval-s: 60
  listener-sleep-ms: 500