dodo:
  common:
    application:
      name: dodo-service
      key:
        source: file
        path: /run/secrets/dodo-service-key

    logger:
      console:
        level: trace
      file:
        level: statistics
        directory: log
        max-size-mib: 1
        max-file-trail: 4
      syslog:
        level: warning
        facility: 1

server:
  listen-address: 192.168.1.2
  listen-port: 1968
  min-servers: 2
  max-servers: 8
  max-connections: 500
  send-buffer: 16384
  receive-buffer: 32768
  send-timeout-seconds: 10
  receive-timeout-seconds: 10
  stat-trc-interval-s: 300
  listener-sleep-ms: 200
  tcp-keep-alive: true
  whitelist-ip:
    - 127.0.0.1
  tls-context:
    private-key: id.rsa
    certificate: server.cert
    tls-min-version: 1.2
    ciphersuite: TLS_AES_256_GCM_SHA384
    # clients must offer trusted certs whose fingerprint appears in the list
    whitelist-fingerprint:
      # the hashing algorithm to apply
      sha256:
        - 44:B5:45:AA:8A:25:E6:5A:73:CA:15:DC:27:FC:36:D2:4C:1C:B9:95:3A:06:65:39:B1:15:82:DC:48:7B:48:33

