dodo:
  common:
    application:
      name: dodo-service
      key:
        source: file
        path: /run/secrets/dodo-service-key

    logger:
      console:
        level: trace
      file:
        level: statistics
        directory: log
        max-size-mib: 1
        max-file-trail: 4
      syslog:
        level: warning
        facility: 1

server:
  listen-address: 0.0.0.0
  listen-port: 1968
  min-servers: 2
  max-servers: 8
  max-connections: 500
  send-buffer: 16384
  receive-buffer: 32768
  send-timeout-seconds: 10
  receive-timeout-seconds: 10
  stat-trc-interval-s: 30
  listener-sleep-ms: 200
  tcp-keep-alive: true
  tls-context:
    private-key: id.rsa
    private-key-passphrase: ENC[]
    certificate: server.cert
    tls-min-version: 1.2
    ciphersuite: TLS_AES_256_GCM_SHA384
